### ISSUE TITLE
unable to handle scaling down from 3 to 1 CockroachDB nodes

### ISSUE THREAD

**Issue by johnrk** [cockroachdb/cockroach-operator#100]
The Operator needs to be able to gracefully handle scaling down from 3+ CockroachDB nodes to 1 CockroachDB node

**Comment by chrislovecnm** [comment]
@chrisseto is this allowed in crdb cloud?

**Comment by chrisseto** [comment]
It is currently not allowed. We plan to support it at some point in time but it's fairly low on the priorities list as we don't think it's _super_ useful to customers.

**Comment by johnrk** [comment]
@chrislovecnm , I thought you mentioned working on fixing something around at Standup on Tuesday. That's why I added this item.

**Comment by chrislovecnm** [comment]
I wanted to say that we need to determine if this is an edge case that we can or cannot support. @chrisseto should we stop the user from doing this?

**Comment by petermattis** [comment]
Moving from 3 to 1 nodes is not something that is well supported by CRDB at this time. Trying to support scaling down to 1 node in the operator before CRDB makes it easy is likely to be an exercise in frustration. So while it is a bit of a wart in the scaling story, I think it is one we should live with for the time being. @johnrk Please correct me if I'm wrong and there is work afoot in CRDB to making scaling down to 1 node easy. 

> I’m almost tempted to tell the user they cannot have less than 3 nodes.

If a user is running on replicated storage, the 1 node configuration does make sense in reducing cost. Unavailability during a node outage may be a bit higher, but you wouldn't lose data.
