### ISSUE TITLE
Release new version of operator supporting v23.1.26

### ISSUE THREAD

**Issue by Babbleshack** [cockroachdb/cockroach-operator#1049]
Hi we want to deploy `v23.1.26` cockroach-operator version `v2.14.0 only` support up to `v23.1.17` ([source](https://github.com/cockroachdb/cockroach-operator/blob/ab42b16aef53f1a13873d8a2d5c2bfaaf32179ed/config/manifests/bases/cockroach-operator.clusterserviceversion.yaml#L441))

Whilst on master the changes are already available ([source](https://github.com/cockroachdb/cockroach-operator/blob/72e37531e6a09b3c47e9f413d1cfb9b2112b0a96/config/manifests/bases/cockroach-operator.clusterserviceversion.yaml#L456)).

 Can we get a new tag/release?

**Comment by data-matt** [comment]
A new tag was released today 

Please see:

https://github.com/cockroachdb/cockroach-operator/releases/tag/v2.15.0
