### ISSUE TITLE
Push testing containers to registry

### ISSUE THREAD

**Issue by chrislovecnm** [cockroachdb/cockroach-operator#113]
This project uses two containers that are generated by running

```
make docker/build/code-gen
make docker/build/test-runner
```

We need to push those two containers into a container registry that is controlled by CR Labs.  Need to write a shell script to push these two containers to a registry.  The shell script will accept the name of the registry where we are pushing the containers to.

Modify the Makefile to accept the name of a versioned container.

**Comment by chrislovecnm** [comment]
cc @jlinder

**Comment by johnrk** [comment]
this is done
