### ISSUE TITLE
Code Cleanup Review by someone from SRE Team before sharing MVP with Customers

### ISSUE THREAD

**Issue by johnrk** [cockroachdb/cockroach-operator#116]
Before sharing Operator with customers, we need to ensure that the entire codebase complies with CC standards. For example, "hack" directory should be renamed.

**Comment by chrislovecnm** [comment]
"hack" directory is a go standard ...  but we can rename it if you like 😄 

Entire codebase compiling with CC standards means ALOT of code documentation needs to be done.

**Comment by johnrk** [comment]
> "hack" directory is a go standard ... but we can rename it if you like 😄

Ah ok, someone from Sales Engineering flagged it. Renaming just to be safe sounds good.

> Entire codebase compiling with CC standards means ALOT of code documentation needs to be done.

Agreed.

**Comment by chrislovecnm** [comment]
@johnrk A ton of projects that I have worked and know of have a hack directory.  So I think it is counterproductive to rename it TBH.  If a developer is familiar with k8s like repositories they are familiar with the hack directory.

Here are some examples:

- https://github.com/jetstack/cert-manager/ an operator
- Kubernetes/CNCF - it is part of there standard - see https://github.com/kubernetes/repo-infra or https://github.com/kubernetes/kubernetes
- kops - part of Kubernetes
- docker - https://github.com/docker/engine

If the directory layout is "standard" that I have seen a lot it saves devs like me time to understand a project.  Where is the "CC standard" documented?

At the end of the day, it is your call as the customer, but I'm explaining why this is a standard in a lot of Kubernetes related projects.

**Comment by chrislovecnm** [comment]
> Entire codebase compiling with CC standards means ALOT of code documentation needs to be done.

I would agree that this needs to occur when the code is beta level, even at this point I am unable to understand all of the code well enough to document the code.  This is a delay in the timeline that I would recommend pushing before an MVP.

**Comment by vladdy** [comment]
@chrislovecnm, feel free to let me know what parts are that opaque and I'll send a PR with comments for them. Also, if we are talking about CockroachCloud standards, I don't think I saw any.

**Comment by chrislovecnm** [comment]
@vladdy oh your offer to add documentation is very much appreciated!!  Let me see if we have a seperate issue open for code documentation.  If not I will open one.

**Comment by chrisseto** [comment]
@johnrk the `hack` directory is very common in go projects, especially kubernetes related projects.

My argument for keeping it is the ubiquity in the OSS space. It's where contributors will look for setup scripts, test scripts, manifests, etc.

Can you say more about the concern that was flagged?

**Comment by johnrk** [comment]
@chrisseto, got it. Keeping the "hack" directory is fine with me.

**Comment by vladdy** [comment]
Although `hack` folder is kind of standard in this kind of projects, in its current state, we can easily remove it to `scripts` or something like that.

**Comment by chrislovecnm** [comment]
We are going to keep the hack directory 😁

**Comment by johnrk** [comment]
cc @bdarnell , @keith-mcclellan , @JuanLeon1 , - here's the discussion about the hack directory.

@chrislovecnm , after speaking with the team today, we should reconsider our naming of the hack directory for config files that we expect our users to use.

**Comment by chrislovecnm** [comment]
@johnrk please explain more. The hack directory is not for users but for developers. So I am confused by your statement.
