### ISSUE TITLE
TeamCity: add cleanup step to the CI build configurations

### ISSUE THREAD

**Issue by jlinder** [cockroachdb/cockroach-operator#119]
Some of the CI steps leave files in the local checkout on the build agents. These can cause problems when the checkout is initialized for the next run of that build configuration. Solution: add a cleanup step to the CI build configurations.

**Comment by chrislovecnm** [comment]
@jlinder I can add a cleanup step, but CI/CD is gonna change big time.  The containers are going away pretty much.  As a temp fix we can do this if you like.
