### ISSUE TITLE
can't recover from scaling down from 3 pods

### ISSUE THREAD

**Issue by taroface** [cockroachdb/cockroach-operator#134]
When scaling from 3 pods down to 1 or 2 pods (by changing the `replicas` value in the manifest), the remaining pods become unready due to failing the health check readiness probe. They remain unready when:

- The unready pod is deleted
- The .yaml is deleted and `./hack/apply-crdb-example.sh -c $CLUSTER` is re-run
- `./hack/delete-crdb-example.sh -c $CLUSTER` is run

When attempting to scale the cluster back up to 3 (or more) pods, the unready pod(s) remain unready and no new pods are created.

**Comment by chrislovecnm** [comment]
@taroface scaling down to one pod is not supported by CRDB.  We probably need to point to the documentation that states this.
