### ISSUE TITLE
PDB Issue: minAvailable is incorrect

### ISSUE THREAD

**Issue by johnrk** [cockroachdb/cockroach-operator#137]
**Test Case:**

- minAvailable: 2
- maxUnavailable: 1

**Expected Result:** 
when running kubectl get poddisruptionbudget, it would return minAvailable: 2

**Actual Result:**
<img width="602" alt="Screen Shot 2020-08-12 at 2 03 58 PM" src="https://user-images.githubusercontent.com/1663752/90050786-b48b5980-dca4-11ea-8bbe-54f417ed9b4c.png">

**Full yaml:**
<img width="586" alt="Screen Shot 2020-08-12 at 2 05 02 PM" src="https://user-images.githubusercontent.com/1663752/90050878-d684dc00-dca4-11ea-9532-817d3811e6ee.png">

**Comment by chrislovecnm** [comment]
cc @alinadonisa
