### ISSUE TITLE
K8s Operator: Support the ability to change an insecure to a secure cluster

### ISSUE THREAD

**Issue by johnrk** [cockroachdb/cockroach-operator#139]
CockroachDB supports the ability to change a running insecure cluster to a secure one.

When running an insecure cluster with `tlsEnabled: true` and optionally `nodeTLSSecret` and `clientTLSSecret` to secure the cluster. (e.g. [3-nodes-secure-kube-cert.yaml](https://github.com/cockroachdb/cockroach-operator/blob/master/examples/3-nodes-secure-kube-cert.yaml#L20)).

**User story:** As an operator (user), I can change a running insecure cluster into a secure cluster, so that I make my cluster more less vulnerable to security breaches with no downtime.

According to @knz , "however this comes with a few pitfalls - all users created so far may have unclear privileges (or perhaps too much) so the resulting cluster may not be too secure after all, unless the operator audits all the user accounts and privileges, and/or removes all the user accounts first"

For now, we are saying this is out of scope for the MVP. In the Operator's current state, a user can have a secure cluster when initializing it properly.

@knz, @aaron-crl  , is there anything else that we should consider here?

**Comment by knz** [comment]
Yes the very main issue is that the k8s operator **should not be able to create insecure clusters to start with**.

We are going to deprecate (and remove) the `--insecure` flag in an upcoming release. It seems (to me) frivolous to invest cycles in supporting an "insecure mode" which we don't want anyone to use.

**Comment by aaron-crl** [comment]
I think I'd rather invest the engineering work in removing the expectation that anything is running in "insecure" mode to begin with?

**Comment by taroface** [comment]
> We are going to deprecate (and remove) the `--insecure` flag in an upcoming release. 

@knz Is there an issue tracking this work that I can reference?

**Comment by knz** [comment]
Here you are: https://github.com/cockroachdb/cockroach/issues/53404

**Comment by johnrk** [comment]
Closing this in favor of disabling insecure mode: https://github.com/cockroachdb/cockroach-operator/issues/153
