### ISSUE TITLE
Verify additionalArgs field works for node-specific settings such as locality

### ISSUE THREAD

**Issue by johnrk** [cockroachdb/cockroach-operator#141]
Coming out of this Helm Chart parity issue, @vladdy  raised that we support additionalArgs ([his comment](https://github.com/cockroachdb/cockroach-operator/issues/25#issuecomment-677667608)).

In the CRD, we define [additionalArgs](https://github.com/cockroachdb/cockroach-operator/blob/master/config/crd/bases/crdb.cockroachlabs.com_crdbclusters.yaml#L56) to handle additional command line arguments for the `cockroach`

We need to verify this can serve as a catch-all for node-specific settings, such as memory and cache usage, disk usage, networking, security, and locality, that are normally handled managed via cockroach start ([cockroach start docs](https://www.cockroachlabs.com/docs/v20.1/cockroach-start)).

**Comment by taroface** [comment]
Ideally, I think that a separate dedicated (and required) field could be used to define localities, rather than consigning this to `additionalArgs`, since distributing nodes across localities is a basic requirement of a resilient cluster. Perhaps this is what the `topology` object in some [examples](https://github.com/cockroachdb/cockroach-operator/blob/master/examples/3-nodes-insecure.yaml#L31) is meant to do?

If I understand correctly, [max-sql-memory](https://github.com/cockroachdb/cockroach-operator/blob/master/api/v1alpha1/cluster_types.go#L68) and [cache](https://github.com/cockroachdb/cockroach-operator/blob/master/api/v1alpha1/cluster_types.go#L64) already have their own fields.

**Comment by vladdy** [comment]
Yes, `max-sql-memory` and `cache`, we created as separate fields as those are usually the first fields set when the db runs in production. Regarding the `locality`, there is nothing what prevents it from being added as another field if it is needed. It is just would be needed to go through how it would be used from the client perspective.

For `topology`, it was a high level concept where, it was possible to define something like:

```
topology:
   'a':
      nodes: 6
   'b':
      nodes: 3
   'c':
      nodes: 3
```

and the operator set the required localities for the pods and the database to create 3 groups (i.e. datacenters/zones) of nodes: 'a' - 6 nodes, 'b' - 3 nodes and 'c' - 3 nodes. I ripped it off to avoid the complexity for MVP. Also similar thing can be done via the operator and 3 CRs after small tweaks to the code (such as allowing to specify another CR to get the join list as well as setting localities for the pods). Another approach could be having an additional CR specifying relationships and discovery info between different groups of nodes.

**Comment by keith-mcclellan** [comment]
@chrislovecnm I think this is working, but can you confirm we have an e2e test where we inject an additionalArg before we close this please?

**Comment by chrislovecnm** [comment]
@keith-mcclellan we should do this in a unit test IMO.  And no we do not have a unit test or an e2e test that does this.  What additionalArg should we test?

**Comment by keith-mcclellan** [comment]
We will need to set a locality flag and then run a query against the DB after it's started to make sure that locality got set properly.  I agree that this is best solved by building a unit test. the query we need to run is `SHOW LOCALITY;` (https://www.cockroachlabs.com/docs/v20.2/show-locality.html) and the additionalArg we need to set is `--locality=` (https://www.cockroachlabs.com/docs/v20.2/cockroach-start.html#locality)

**Comment by chrislovecnm** [comment]
@keith-mcclellan please provide more business requirements.  Testing `--locality` really seems like testing the database and not the operator.  We can do a e2e test where we add the locality, but I would rather add another parameter so that we are not doing such complex testing.

**Comment by keith-mcclellan** [comment]
We need to create a unit test that passes in a valid additionalArg and validate that it's getting set in the databse.  Locality is the most common argument we could set (to the point where later on we'll probably want to make it a defined value like sqlPort or grpcPort) that is also easy to validate, but in theory it could be any additional argument supported by `cockroach start` as listed here (https://www.cockroachlabs.com/docs/v20.2/cockroach-start.html)
