### ISSUE TITLE
RedHat package generation

### ISSUE THREAD

**Issue by chrislovecnm** [cockroachdb/cockroach-operator#146]
We would like to get bazel generating the files for RedHat and the modified crd file.  See https://docs.openshift.com/container-platform/4.5/operators/operator_sdk/osdk-generating-csvs.html

cc: @keith-mcclellan

**Comment by keith-mcclellan** [comment]
Chris - as we discussed, we're closer but still having issues.  I stashed my hand-edited metadata files and the log from the scorecard tests here: https://github.com/cockroachdb/cockroach-operator/blob/openshift-certification/metadata/ & https://github.com/cockroachdb/cockroach-operator/blob/openshift-certification/metadata/operator-scorecard-test.log.txt

On the plus side, the operator package for openshift does actually launch a cluster now so we're getting close-ish.

**Comment by keith-mcclellan** [comment]
@alinadonisa @chrislovecnm I think we can close this now that alina's latest changes are merged and we can programmatically produce a bundle.  Do you both agree?

**Comment by alinadonisa** [comment]
@keith-mcclellan  yes
