### ISSUE TITLE
Support Non-K8s Certificate Authority for the Operator

### ISSUE THREAD

**Issue by johnrk** [cockroachdb/cockroach-operator#152]
EKS does not support the K8s CA. For customers that need to create a secure cluster and want to use EKS, the flexibility to support a non-K8s CA is needed.

As described in this [Github issue](https://github.com/cockroachdb/cockroach/pull/27921) and demonstrated in this [forum post](https://forum.cockroachlabs.com/t/secure-cockroachdb-cluster-on-aws-eks/1824/22), customers trying to use CockroachDB with EKS have run into this pain point.

cc @taroface

**Comment by chrislovecnm** [comment]
We already have this functionality build in.  I have not tested it, but see 

https://github.com/cockroachdb/cockroach-operator/blob/master/api/v1alpha1/cluster_types.go#L48

**Comment by taroface** [comment]
@chrislovecnm Which parameter does that line refer to? `TLSEnabled` is a bool. I couldn't find a place in the config to specify `ca.crt`.

**Comment by chrislovecnm** [comment]
https://github.com/cockroachdb/cockroach-operator/blob/9e4ced68ba2f1351db734af72ad2f773830807b2/api/v1alpha1/cluster_types.go#L48-L54

These two values

**Comment by johnrk** [comment]
@taroface , this issue is still open but was determined to be a non-MVP issue.
