### ISSUE TITLE
Make Secure Mode the Default

### ISSUE THREAD

**Issue by johnrk** [cockroachdb/cockroach-operator#153]
We are going to make enabling an insecure cluster a discrete decision.

cc @keith-mcclellan

**Comment by chrislovecnm** [comment]
All of this code needs modification and remove the TLSEnabled API flag as well.

https://github.com/cockroachdb/cockroach-operator/search?q=TLSEnabled&unscoped_q=TLSEnabled

**Comment by johnrk** [comment]
@keith-mcclellan , can you comment on your concern about our introducing API breaking changes here?

**Comment by johnrk** [comment]
@chrislovecnm , we're changing this feature to allow users to use insecure clusters for internal testing.
