### ISSUE TITLE
TeamCity: add a build configuration for end-to-end tests

### ISSUE THREAD

**Issue by jlinder** [cockroachdb/cockroach-operator#158]
We want a new build configuration that runs the end-to-end tests in TeamCity.

Details:

- Make it a snapshot dependency for the `Operator GitHub CI` build configuration
- Name: End-to-End
- Location: Cockroach > Cockroach Operator
- What it needs to run:
   ```
   bazel test //e2e/...
   ```
- It probably needs to install bazel on the host like the `Test` build configuration

**Comment by chrislovecnm** [comment]
1. Run bazel install script
2. Execute bazel command

**Comment by jlinder** [comment]
I’ve created the new build configuration. Can you run an appropriate branch on it to check it works as expected? https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_CockroachOperator_EndToEnd?branch=&mode=builds

**Comment by jlinder** [comment]
This is done.
