### ISSUE TITLE
Add bazel build for RedHat Marketplace

### ISSUE THREAD

**Issue by chrislovecnm** [cockroachdb/cockroach-operator#159]
This issue is tracking the manual steps that we are doing for building the Marketplace release.  @keith-mcclellan please include any CSV updates that you are doing to this issue.

### Generate CSV

1. install operator-sdk curl -LO https://github.com/operator-framework/operator-sdk/releases/download/v0.19.2/operator-sdk-v0.19.2-x86_64-linux-gn
2. git clone https://github.com/operator-framework/operator-courier && docker build --tag operator-courier/operator-courier:v2.1.10 ./
3. new make targets
4. new bundle shell command

**Comment by johnrk** [comment]
@alinadonisa , can you confirm that this is done?

**Comment by alinadonisa** [comment]
@johnrk  I need to use SCRATCH image to close this
