### ISSUE TITLE
[OpenShift - release blocker] CSV generation doesn't auto-generate properly

### ISSUE THREAD

**Issue by keith-mcclellan** [cockroachdb/cockroach-operator#164]
Currently, the CSV being generated by the operator makefile does not properly fill out all of the required stanzas in a way that passes the OpenShift cert tooling.

**Comment by keith-mcclellan** [comment]
Now that we have a manually edited bundle that certifies and launches the operator, I pushed a copy of my local work to the openshift-certification branch - https://github.com/cockroachdb/cockroach-operator/tree/openshift-certification

**Comment by johnrk** [comment]
@keith-mcclellan , I assume this issue is no longer active?

**Comment by chrislovecnm** [comment]
@rail can we close this?

**Comment by rail** [comment]
Yes!
