### ISSUE TITLE
[OpenShift - release blocker] - Status block in CR not being updated as Operator Lifecycle Manager expects

### ISSUE THREAD

**Issue by keith-mcclellan** [cockroachdb/cockroach-operator#165]
We are not updating the status block in a way that the Operator Lifecycle Manager (which OpenShift relies on) knows the status of the operator and/or the cockroachdb cluster automatically, and it's causing us to fail to pass their certification tests.

**Comment by keith-mcclellan** [comment]
[sept8scorecard.log.txt](https://github.com/cockroachdb/cockroach-operator/files/5190568/sept8scorecard.log.txt)

**Comment by alinadonisa** [comment]
we added a field in the status to save when starting the operator.
