### ISSUE TITLE
[Openshift - Release Blocker] Operator is trying to "upgrade" to null version

### ISSUE THREAD

**Issue by keith-mcclellan** [cockroachdb/cockroach-operator#169]
Not 100% sure what's going on here, but the operator container seems to want to upgrade my cluster to a new version that is unset.

This is actually the error I'm getting in the openshift CI logs for certs so it might be what's blocking certification.

`k8s.io/apimachinery/pkg/util/wait.Until
	external/io_k8s_apimachinery/pkg/util/wait/wait.go:90
2020-09-08T17:47:28.588Z	INFO	controller.CrdbCluster	reconciling CockroachDB cluster	{"CrdbCluster": "default/crdb-tls-ryandemo"}
2020-09-08T17:47:28.588Z	INFO	action	checking upgrade opportunities	{"action": "upgrade", "CrdbCluster": "default/crdb-tls-ryandemo"}
2020-09-08T17:47:28.588Z	ERROR	controller.CrdbCluster	action failed	{"CrdbCluster": "default/crdb-tls-ryandemo", "error": "Unknown CockroachDB version in spec: "}
github.com/go-logr/zapr.(*zapLogger).Error
	external/com_github_go_logr_zapr/zapr.go:128
github.com/cockroachdb/cockroach-operator/pkg/controller.(*ClusterReconciler).Reconcile
	pkg/controller/cluster_controller.go:111
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	external/io_k8s_sigs_controller_runtime/pkg/internal/controller/controller.go:256
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	external/io_k8s_sigs_controller_runtime/pkg/internal/controller/controller.go:232
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
	external/io_k8s_sigs_controller_runtime/pkg/internal/controller/controller.go:211
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
	external/io_k8s_apimachinery/pkg/util/wait/wait.go:155
k8s.io/apimachinery/pkg/util/wait.BackoffUntil
	external/io_k8s_apimachinery/pkg/util/wait/wait.go:156
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	external/io_k8s_apimachinery/pkg/util/wait/wait.go:133
k8s.io/apimachinery/pkg/util/wait.Until
	external/io_k8s_apimachinery/pkg/util/wait/wait.go:90
2020-09-08T17:47:28.588Z	ERROR	controller-runtime.controller	Reconciler error	{"controller": "crdbcluster", "request": "default/crdb-tls-ryandemo", "error": "Unknown CockroachDB version in spec: "}
github.com/go-logr/zapr.(*zapLogger).Error
	external/com_github_go_logr_zapr/zapr.go:128
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	external/io_k8s_sigs_controller_runtime/pkg/internal/controller/controller.go:258
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	external/io_k8s_sigs_controller_runtime/pkg/internal/controller/controller.go:232
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
	external/io_k8s_sigs_controller_runtime/pkg/internal/controller/controller.go:211
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
	external/io_k8s_apimachinery/pkg/util/wait/wait.go:155
k8s.io/apimachinery/pkg/util/wait.BackoffUntil
	external/io_k8s_apimachinery/pkg/util/wait/wait.go:156
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	external/io_k8s_apimachinery/pkg/util/wait/wait.go:133
k8s.io/apimachinery/pkg/util/wait.Until
	external/io_k8s_apimachinery/pkg/util/wait/wait.go:90
2020-09-08T17:47:29.588Z	INFO	controller.CrdbCluster	reconciling CockroachDB cluster	{"CrdbCluster": "default/crdb-tls-ryandemo"}
2020-09-08T17:47:29.588Z	INFO	action	checking upgrade opportunities	{"action": "upgrade", "CrdbCluster": "default/crdb-tls-ryandemo"}
2020-09-08T17:47:29.588Z	ERROR	controller.CrdbCluster	action failed	{"CrdbCluster": "default/crdb-tls-ryandemo", "error": "Unknown CockroachDB version in spec: "}
github.com/go-logr/zapr.(*zapLogger).Error
	external/com_github_go_logr_zapr/zapr.go:128
github.com/cockroachdb/cockroach-operator/pkg/controller.(*ClusterReconciler).Reconcile
	pkg/controller/cluster_controller.go:111
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	external/io_k8s_sigs_controller_runtime/pkg/internal/controller/controller.go:256
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	external/io_k8s_sigs_controller_runtime/pkg/internal/controller/controller.go:232
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
	external/io_k8s_sigs_controller_runtime/pkg/internal/controller/controller.go:211
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
	external/io_k8s_apimachinery/pkg/util/wait/wait.go:155
k8s.io/apimachinery/pkg/util/wait.BackoffUntil
	external/io_k8s_apimachinery/pkg/util/wait/wait.go:156
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	external/io_k8s_apimachinery/pkg/util/wait/wait.go:133
k8s.io/apimachinery/pkg/util/wait.Until
	external/io_k8s_apimachinery/pkg/util/wait/wait.go:90
2020-09-08T17:47:29.588Z	ERROR	controller-runtime.controller	Reconciler error	{"controller": "crdbcluster", "request": "default/crdb-tls-ryandemo", "error": "Unknown CockroachDB version in spec: "}
github.com/go-logr/zapr.(*zapLogger).Error
	external/com_github_go_logr_zapr/zapr.go:128
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	external/io_k8s_sigs_controller_runtime/pkg/internal/controller/controller.go:258
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	external/io_k8s_sigs_controller_runtime/pkg/internal/controller/controller.go:232
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
	external/io_k8s_sigs_controller_runtime/pkg/internal/controller/controller.go:211
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
	external/io_k8s_apimachinery/pkg/util/wait/wait.go:155
k8s.io/apimachinery/pkg/util/wait.BackoffUntil
	external/io_k8s_apimachinery/pkg/util/wait/wait.go:156
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	external/io_k8s_apimachinery/pkg/util/wait/wait.go:133
k8s.io/apimachinery/pkg/util/wait.Until
	external/io_k8s_apimachinery/pkg/util/wait/wait.go:90
2020-09-08T17:57:11.600Z	INFO	controller.CrdbCluster	reconciling CockroachDB cluster	{"CrdbCluster": "default/crdb-tls-ryandemo"}
2020-09-08T17:57:11.600Z	INFO	action	checking upgrade opportunities	{"action": "upgrade", "CrdbCluster": "default/crdb-tls-ryandemo"}
2020-09-08T17:57:11.600Z	ERROR	controller.CrdbCluster	action failed	{"CrdbCluster": "default/crdb-tls-ryandemo", "error": "Unknown CockroachDB version in spec: "}
github.com/go-logr/zapr.(*zapLogger).Error
	external/com_github_go_logr_zapr/zapr.go:128
github.com/cockroachdb/cockroach-operator/pkg/controller.(*ClusterReconciler).Reconcile
	pkg/controller/cluster_controller.go:111
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	external/io_k8s_sigs_controller_runtime/pkg/internal/controller/controller.go:256
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	external/io_k8s_sigs_controller_runtime/pkg/internal/controller/controller.go:232
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
	external/io_k8s_sigs_controller_runtime/pkg/internal/controller/controller.go:211
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
	external/io_k8s_apimachinery/pkg/util/wait/wait.go:155
k8s.io/apimachinery/pkg/util/wait.BackoffUntil
	external/io_k8s_apimachinery/pkg/util/wait/wait.go:156
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	external/io_k8s_apimachinery/pkg/util/wait/wait.go:133
k8s.io/apimachinery/pkg/util/wait.Until
	external/io_k8s_apimachinery/pkg/util/wait/wait.go:90`

**Comment by keith-mcclellan** [comment]
[sept8scorecard.log.txt](https://github.com/cockroachdb/cockroach-operator/files/5190553/sept8scorecard.log.txt)
Latest scorecard log - same stacktrace as I am seeing when I run locally.

**Comment by alinadonisa** [comment]
we will have another implementation and we already passed the certification so I would close this.
