### ISSUE TITLE
[OpenShift - Release Blocker] serviceAccount needs to be set for pods created by operator

### ISSUE THREAD

**Issue by keith-mcclellan** [cockroachdb/cockroach-operator#172]
New pods created outside the default namespace throw the following error:

```
++ echo crdb-tls-disabled-0
+ exec /cockroach/cockroach start --join=crdb-tls-disabled-0.crdb-tls-disabled.zach-test:26257 --advertise-host=crdb-tls-disabled-0.crdb-tls-disabled.zach-test --logtostderr=INFO --insecure --http-port=8080 --port=26257 --cache=25% --max-sql-memory=25%
/bin/sh: -: Permission denied
```

To resolve this, a serviceAccount needs to be created as a part of the crdbcluster creation and attached to the pods per Zach at IBM.

**Comment by chrislovecnm** [comment]
I just verified that this is an openshift oddity.  This works on GKE just fine.

**Comment by keith-mcclellan** [comment]
Chris's research determined that this is due to the containers default behavior of running as root inside the container.  He's working on a change for this, plus we determined we had several bugs in our containerized deployment guidance that need to be resolved.

**Comment by alinadonisa** [comment]
we added a service account for the cockroach db
