### ISSUE TITLE
Make logging configurable for database

### ISSUE THREAD

**Issue by chrislovecnm** [cockroachdb/cockroach-operator#175]
Currently, the database logging level is hardcoded.  

https://github.com/cockroachdb/cockroach-operator/blob/4c5f71bd4ee2370129b8f105e997aa211cc02b50/pkg/resource/statefulset.go#L280

Move this configuration into the API value, in case we need to turn on debug logging or another level.

**Comment by johnrk** [comment]
@keith-mcclellan to discuss this with @chrislovecnm

**Comment by chrislovecnm** [comment]
Closing
