### ISSUE TITLE
Test development instructions

### ISSUE THREAD

**Issue by chrislovecnm** [cockroachdb/cockroach-operator#190]
Please get the project building locally. You may have challenges with two things

1. The image line in the operator may need to change to a previous value, as I am not certain bazel is replacing it properly
2. When you run --stamp with bazel it uses https://github.com/cockroachdb/cockroach-operator/blob/master/hack/build/print-workspace-status.sh for env variables.  These variables point to which cluster bazel is deploying to.  I am not certain this is working properly.

We probably should add a couple of development targets to the makefile as well

bazel run //hack:update-deps
bazel run //hack:update-bazel

cc @alinadonisa @johnrk

**Comment by chrislovecnm** [comment]
There is also an issue open that you have to have realpath installed on the mac.  I have used Linux mostly for dev, so you may run into a couple of mac specific edge cases.

**Comment by johnrk** [comment]
this works, according to @keith-mcclellan
