### ISSUE TITLE
run e2e tests in parallel and refactor e2e tests

### ISSUE THREAD

**Issue by chrislovecnm** [cockroachdb/cockroach-operator#193]
The e2e tests do not seem to run in parallel and are already taking 8 minutes to write.  The test suite that we are using does not respect the -test.parallel flag and I am uncertain why.

**Comment by johnrk** [comment]
@keith-mcclellan to follow up with @chrislovecnm on this.

**Comment by chrislovecnm** [comment]
We need to refactor the e2e tests into separate go files. Each go test file needs to be in a separate package.
