### ISSUE TITLE
Update of one of the fields from  CrdbCluster CRD finishes with errors 

### ISSUE THREAD

**Issue by alinadonisa** [cockroachdb/cockroach-operator#197]
When a field from CrdbCluster Spec is edited, it triggers an reconcile on all the resources, StatefullSet included and it tries to update fileds from StatefullSet  that cannot be updated, throwing an error.

The update functionality should be reviewed to set the correct behaviour.

**Comment by johnrk** [comment]
@alinadonisa , is this still an issue?
