### ISSUE TITLE
Implement delete CrdbCluster CRD functionality

### ISSUE THREAD

**Issue by alinadonisa** [cockroachdb/cockroach-operator#198]
When deleting a  CrdbCluster CRD from the cluster, we should review the lifecycle of the PV resource.

**Comment by chrislovecnm** [comment]
@alinadonisa please add more details to this

**Comment by alinadonisa** [comment]
@chrislovecnm  PV should be deleted only manually?

**Comment by chrislovecnm** [comment]
@alinadonisa yes we should not delete the PV or PVC automatically.  Closing
