### ISSUE TITLE
Configurations for updates

### ISSUE THREAD

**Issue by chrislovecnm** [cockroachdb/cockroach-operator#203]
We probably want to allow the user to configure

1. Pod Update Timeout (set at 10 min)
2. Pod Max Polling Intervales (set at 30 min)
3. Sleeper (set at 1 min)
4. Context, set at a really large number now

**Comment by chrislovecnm** [comment]
@chrisseto should these configurations be per operator or per crdb?

**Comment by johnrk** [comment]
@chrislovecnm , what's the status of this?
