### ISSUE TITLE
Remove emptyDir

### ISSUE THREAD

**Issue by chrislovecnm** [cockroachdb/cockroach-operator#206]
CRDB cannot run when using emptyDir.  Check that the PVC that was defined is not an empty dir.

**Comment by vktr-brlv** [comment]
@chrislovecnm Could you please clarify more on the issue? Thanks!

**Comment by chrislovecnm** [comment]
In the api you are able to use an empydir disk type. Remove that and fix the tests to use pvc’s

**Comment by chrislovecnm** [comment]
This is fixed, please test
