### ISSUE TITLE
After abruptly stopping dev-deploy-crdb script, K8s Cluster isn't able to create any CrdbCluster

### ISSUE THREAD

**Issue by johnrk** [cockroachdb/cockroach-operator#211]
In an attempt to test out rolling upgrades, I've been looping on the hack/dev-deploy.sh script. At the moment, my cluster is in a state that I can't create a new CrdbCluster. Below, I've included:
1. Repro Steps
2. Screen shot of repro steps
3. Logs of the Operator Pod
4. Copy of the slightly modified dev-deploy-crdb script (I commented out the make k8s/apply command)

**Repro Steps:**

1. Following, [developer.md](https://github.com/cockroachdb/cockroach-operator/blob/master/DEVELOPER.md) docs, installed Operator
2. Using dev-deploy-crdb.sh started new CrdbCluster
3. And successfully performed upgrade
4. force deleted CrdbCluster (kubectl delete CrdbCluster crdb-update)
5. force deleted all persistent volumes and persistent volume claims (kubectl delete all pv,pvc)
6. In attempt to start a new cluster again, re-ran dev-deploy-crdb with all previous resources deleted
7. force quit the script with ctrl-c
8. went through the same deletion steps as before
9. attempted to start the dev-deploy-crdb script again, and received "Error from server (NotFound): statefulsets.aps "crdb-update" not found
10. After that script failed, I attempted to try creating a cluster with a diff name/config with the other hack/apply-crdb-example.sh - that also failed with this same error as in the previous step.

Expected Results:
CrdbCluster is created with the dev-deploy-crdb script and with the apply-crdb-example script

Actual Results: the clusters are not found. In addition when running kubectl get Crdbclusters, they exist, but no pods exist.

**Screenshots of Repro Steps:**
Unable to create CrdbCluster:
<img width="859" alt="repro steps failing to create CrdbCluster" src="https://user-images.githubusercontent.com/1663752/97479087-3a27b880-1928-11eb-9450-83f12c885a78.png">

After repro steps, dump of kubectl describe crdb-no-topo (kubectl get pods doesn't show any pods for this Crdbcluster):
<img width="1171" alt="kubectl describe crdb-no-topo" src="https://user-images.githubusercontent.com/1663752/97479170-50ce0f80-1928-11eb-8249-9175d39a50f2.png">

After repro steps, dump of kubectl describe crdb-update (kubectl get pods doesn't show any pods for this Crdbcluster):
<img width="1164" alt="kubectl describe crdb-update" src="https://user-images.githubusercontent.com/1663752/97479221-64797600-1928-11eb-925a-119b6234d847.png">

**Logs of Operator Pod:**
[operator-logs.txt](https://github.com/cockroachdb/cockroach-operator/files/5454001/operator-logs.txt)

**Screenshot of Slightly Modified dev-deploy-crdb script**
<img width="1145" alt="dev-deploy-crdb script" src="https://user-images.githubusercontent.com/1663752/97478275-1748d480-1927-11eb-9856-23a913c65965.png">

**Comment by chrislovecnm** [comment]
This is no longer relevant with Bazel.  Closing issue
