### ISSUE TITLE
Enable Pod Security Policies (placeholder)

### ISSUE THREAD

**Issue by johnrk** [cockroachdb/cockroach-operator#216]
A large customer requested support for [Pod Security Policies](https://kubernetes.io/docs/concepts/policy/pod-security-policy/).

**Comment by johnrk** [comment]
Pod Security Policies are being deprecated: https://github.com/kubernetes/kubernetes/pull/97171

**Comment by chrislovecnm** [comment]
@johnrk nothing is stopping users from creating their own PSPs.  Can we document this?

**Comment by johnrk** [comment]
ok, great.

I'll open an issue for our documenting this guidance, as one of our customers requested this support.

Closing.
