### ISSUE TITLE
CRDB operator fails on Openshift installation with GCP

### ISSUE THREAD

**Issue by alinadonisa** [cockroachdb/cockroach-operator#217]
On Openshift installation with GCP,  creating a new crdbclusters CR fails with logs:

I201104 17:01:29.613743 66 server/server.go:1514  [n?] no stores bootstrapped and --join flag specified, awaiting init command or join with an already initialized node.
W201104 17:01:29.714369 92 gossip/gossip.go:1296  [n?] invalid bootstrap address: &{typ:tcp addr:crdb-no-tls-example-1.crdb-no-tls-example.alina:26257}, lookup crdb-no-tls-example-1.crdb-no-tls-example.alina on 172.30.0.10:53: no such host
W201104 17:01:29.779054 92 gossip/gossip.go:1296  [n?] invalid bootstrap address: &{typ:tcp addr:crdb-no-tls-example-2.crdb-no-tls-example.alina:26257}, lookup crdb-no-tls-example-2.crdb-no-tls-example.alina on 172.30.0.10:53: no such host
I201104 17:01:31.614027 95 cli/start.go:656  initial startup completed.
Node will now attempt to join a running cluster, or wait for `cockroach init`.

**Comment by chrislovecnm** [comment]
@alinadonisa did we fix this or figure out the bug?

**Comment by alinadonisa** [comment]
Partially solved. It was related to permissions on Open Shift. We passed this but we get another error. I am still working on it with @chrisseto

**Comment by johnrk** [comment]
@alinadonisa , is this done?

**Comment by alinadonisa** [comment]
@johnrk  it is done, @chrisseto  made also a patch for this
