### ISSUE TITLE
CRDB Operator throws an error when deleting CR, PV's and PVC's

### ISSUE THREAD

**Issue by alinadonisa** [cockroachdb/cockroach-operator#218]
When deleting a CV , all the PV's and all PVC's from the namespace, the operator returns an error.

2020-11-04T17:47:26.303Z	DEBUG	controller-runtime.controller	Successfully Reconciled	{"controller": "crdbcluster", "request": "alina/crdb-no-tls-example"}
2020-11-04T17:47:26.304Z	INFO	controller.CrdbCluster	reconciling CockroachDB cluster	{"CrdbCluster": "alina/crdb-no-tls-example"}
2020-11-04T17:47:26.304Z	ERROR	controller.CrdbCluster	failed to retrieve CrdbCluster resource	{"CrdbCluster": "alina/crdb-no-tls-example", "error": "CrdbCluster.crdb.cockroachlabs.com \"crdb-no-tls-example\" not found"}
github.com/go-logr/zapr.(*zapLogger).Error
	external/com_github_go_logr_zapr/zapr.go:128
github.com/cockroachdb/cockroach-operator/pkg/controller.(*ClusterReconciler).Reconcile
	pkg/controller/cluster_controller.go:84
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	external/io_k8s_sigs_controller_runtime/pkg/internal/controller/controller.go:256
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	external/io_k8s_sigs_controller_runtime/pkg/internal/controller/controller.go:232
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
	external/io_k8s_sigs_controller_runtime/pkg/internal/controller/controller.go:211
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
	external/io_k8s_apimachinery/pkg/util/wait/wait.go:155
k8s.io/apimachinery/pkg/util/wait.BackoffUntil
	external/io_k8s_apimachinery/pkg/util/wait/wait.go:156
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	external/io_k8s_apimachinery/pkg/util/wait/wait.go:133
k8s.io/apimachinery/pkg/util/wait.Until
	external/io_k8s_apimachinery/pkg/util/wait/wait.go:90

**Comment by johnrk** [comment]
@alinadonisa , is this still an issue? If not, I'll close.

**Comment by chrislovecnm** [comment]
This is still open but not really an issue. It is a timing thing. Not certain how to fix
