### ISSUE TITLE
[crdb-operator] [bug] unable to make changes (e.g. crdb version, cache size, # of nodes, size of pvc) to an existing k8s cluster

### ISSUE THREAD

**Issue by johnrk** [cockroachdb/cockroach-operator#22]
**Unable to make changes to an existing k8s cluster**
As one of the expected features in the [K8s Operator MVP](https://docs.google.com/document/d/1_ctNL6P9w8f4PZ7vQvN_UDcS_8OQ3MxyT82iM-oXBPU/edit
), it appears the Operator is not watching for any changes to a Cockroach cluster. When starting up a new cluster, it appears to properly apply the spec. 

I think Vlad intended to watch for changes here: https://github.com/cockroachdb/crdb-operator/blob/master/pkg/controller/cluster_controller.go#L103

**Test Details**
1. Setup a K8s cluster deployed on GCP, following these instructions: https://www.cockroachlabs.com/docs/stable/orchestrate-cockroachdb-with-kubernetes.html
- gcloud container clusters create cockroachdb --machine-type n1-standard-4
- kubectl create clusterrolebinding $USER-cluster-admin-binding --clusterrole=cluster-admin --user=<your.google.cloud.email@example.org>
2. Apply CRD: kubectl apply -f ./config/crd/bases/crdb.cockroachlabs.com_crdbclusters.yaml
3. Apply deployment file (in PR):  kubectl apply -f deploy/operator.yaml
4. Apply example config to create new cockroachdb pods: kubectl apply -f config/examples/example.yaml
- at this point it works
5. then make minor change to config/examples/example.yaml, such as major version, minor version, number of nodes, size of persistent volume, cache

**Expected Result:** K8s is watching the status of the pods, notices a discrepancy between the status of the pods and their spec, in reconcile function, updates the pods

**Actual Result:** no restarts happen, when looking at the node in gcp and when opening a crdb client, nothing changed

**Comment by vladdy** [comment]
@johnrk, it would be good to have more details about the setup, but more than likely that should be fixed in #20

**Comment by johnrk** [comment]
Thanks, @vladdy. I'll test it again with that change (#20). And I'll share more details later.

**Comment by johnrk** [comment]
@vladdy , circling back on this, I applied the repro steps as described above in the issue:
Setup a K8s cluster deployed on GCP, following these instructions: https://www.cockroachlabs.com/docs/stable/orchestrate-cockroachdb-with-kubernetes.html
gcloud container clusters create cockroachdb --machine-type n1-standard-4
kubectl create clusterrolebinding $USER-cluster-admin-binding --clusterrole=cluster-admin --user=your.google.cloud.email@example.org
Apply CRD: kubectl apply -f ./config/crd/bases/crdb.cockroachlabs.com_crdbclusters.yaml
Apply deployment file (in PR): kubectl apply -f deploy/operator.yaml
Apply example config to create new cockroachdb pods: kubectl apply -f config/examples/example.yaml

Here's an example of before and after of the example.yaml that I used. With your latest PR (#20), I tried changing major version and number of nodes.

**Before:**
apiVersion: crdb.cockroachlabs.com/v1alpha1
kind: CrdbCluster
metadata:
  name: crdb
spec:
  dataStore:
    emptyDir: {}
  tlsEnabled: true
  nodeTLSSecret: GENERATED
  image: cockroachdb/cockroach-unstable:v20.1.0
  nodes: 1 

**After:**
apiVersion: crdb.cockroachlabs.com/v1alpha1
kind: CrdbCluster
metadata:
  name: crdb
spec:
  dataStore:
    emptyDir: {}
  tlsEnabled: true
  nodeTLSSecret: GENERATED
  image: cockroachdb/cockroach-unstable:v20.1.0
  nodes: 2

**Comment by vladdy** [comment]
Thank you for providing all those details. A couple of additional questions:

1. How did you run the operator with the PR?
2. What was the state of the StatefulSet before and after the update? You can get it via `kubectl get sts crdb -o yaml`?

**Comment by johnrk** [comment]
**1. How I ran the Operator with the PR:**
1. I pulled your changes
git checkout -b vladdy-refactor-resource-reconciliation master
git pull https://github.com/vladdy/crdb-operator.git refactor-resource-reconciliation
2. started a new cluster
3. and ran the tests above

**2. state of the StatefulSet right now:**
Johns-MacBook-Pro:crdb-operator johnkendall$ kubectl get sts crdb -o yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: "2020-05-22T19:48:12Z"
  generation: 1
  labels:
    app.kubernetes.io/component: database
    app.kubernetes.io/instance: crdb
    app.kubernetes.io/managed-by: crdb-operator
    app.kubernetes.io/name: cockroachdb
    app.kubernetes.io/part-of: cockroachdb
  name: crdb
  namespace: default
  ownerReferences:
  - apiVersion: crdb.cockroachlabs.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: CrdbCluster
    name: crdb
    uid: 19e1f69f-9c65-11ea-baa1-42010a8e00b9
  resourceVersion: "8404"
  selfLink: /apis/apps/v1/namespaces/default/statefulsets/crdb
  uid: 2b569c5f-9c65-11ea-baa1-42010a8e00b9
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: database
      app.kubernetes.io/instance: crdb
      app.kubernetes.io/name: cockroachdb
  serviceName: crdb
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: database
        app.kubernetes.io/instance: crdb
        app.kubernetes.io/name: cockroachdb
    spec:
      containers:
      - args:
        - shell
        - -ecx
        - '>- exec /cockroach/cockroach start --join=crdb-0.crdb.default:26257 --advertise-host=$(hostname
          -f) --logtostderr=INFO --certs-dir=/cockroach/cockroach-certs/ --http-port=8080
          --port=26257 --cache=25% --max-sql-memory=25%'
        env:
        - name: COCKROACH_CHANNEL
          value: kubernetes-helm
        image: cockroachdb/cockroach-unstable:v20.1.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: http
            scheme: HTTPS
          initialDelaySeconds: 30
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        name: db
        ports:
        - containerPort: 26257
          name: grpc
          protocol: TCP
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 2
          httpGet:
            path: /health?ready=1
            port: http
            scheme: HTTPS
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /cockroach/cockroach-data/
          name: datadir
        - mountPath: /cockroach/cockroach-certs/
          name: certs
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 60
      volumes:
      - emptyDir: {}
        name: datadir
      - name: certs
        projected:
          defaultMode: 256
          sources:
          - secret:
              items:
              - key: ca.crt
                path: ca.crt
              - key: tls.crt
                path: node.crt
              - key: tls.key
                path: node.key
              name: crdb-node
          - secret:
              items:
              - key: tls.crt
                path: client.root.crt
              - key: tls.key
                path: client.root.key
              name: crdb-root
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
status:
  collisionCount: 0
  currentReplicas: 1
  currentRevision: crdb-6f8bc5448f
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updateRevision: crdb-6f8bc5448f
  updatedReplicas: 1

**Comment by johnrk** [comment]
After doing kubectl delete -f config/examples/example.yaml,
Here's kubectl get sts crdb -o yaml output for before applying example.yaml, after applying example.yaml, and applying a changed example.yaml:

1. before applying example.yaml:
`Error from server (NotFound): statefulsets.apps "crdb" not found`

2. after applying example.yaml:
```
kubectl get pods
Johns-MacBook-Pro:crdb-operator johnkendall$ kubectl get pods
NAME                            READY   STATUS    RESTARTS   AGE
crdb-0                          1/1     Running   0          28s
crdb-operator-68d986bdd-xdch2   1/1     Running   0          107m

Johns-MacBook-Pro:crdb-operator johnkendall$ kubectl get sts crdb -o yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: "2020-05-22T21:34:17Z"
  generation: 1
  labels:
    app.kubernetes.io/component: database
    app.kubernetes.io/instance: crdb
    app.kubernetes.io/managed-by: crdb-operator
    app.kubernetes.io/name: cockroachdb
    app.kubernetes.io/part-of: cockroachdb
  name: crdb
  namespace: default
  ownerReferences:
  - apiVersion: crdb.cockroachlabs.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: CrdbCluster
    name: crdb
    uid: fd6beee8-9c73-11ea-a4f5-42010a8e00f1
  resourceVersion: "40842"
  selfLink: /apis/apps/v1/namespaces/default/statefulsets/crdb
  uid: fd72a8c7-9c73-11ea-baa1-42010a8e00b9
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: database
      app.kubernetes.io/instance: crdb
      app.kubernetes.io/name: cockroachdb
  serviceName: crdb
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: database
        app.kubernetes.io/instance: crdb
        app.kubernetes.io/name: cockroachdb
    spec:
      containers:
      - args:
        - shell
        - -ecx
        - '>- exec /cockroach/cockroach start --join=crdb-0.crdb.default:26257 --advertise-host=$(hostname
          -f) --logtostderr=INFO --certs-dir=/cockroach/cockroach-certs/ --http-port=8080
          --port=26257 --cache=25% --max-sql-memory=25%'
        env:
        - name: COCKROACH_CHANNEL
          value: kubernetes-helm
        image: cockroachdb/cockroach-unstable:v20.1.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: http
            scheme: HTTPS
          initialDelaySeconds: 30
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        name: db
        ports:
        - containerPort: 26257
          name: grpc
          protocol: TCP
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 2
          httpGet:
            path: /health?ready=1
            port: http
            scheme: HTTPS
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /cockroach/cockroach-data/
          name: datadir
        - mountPath: /cockroach/cockroach-certs/
          name: certs
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 60
      volumes:
      - emptyDir: {}
        name: datadir
      - name: certs
        projected:
          defaultMode: 256
          sources:
          - secret:
              items:
              - key: ca.crt
                path: ca.crt
              - key: tls.crt
                path: node.crt
              - key: tls.key
                path: node.key
              name: crdb-node
          - secret:
              items:
              - key: tls.crt
                path: client.root.crt
              - key: tls.key
                path: client.root.key
              name: crdb-root
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
status:
  collisionCount: 0
  currentReplicas: 1
  currentRevision: crdb-6f8bc5448f
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updateRevision: crdb-6f8bc5448f
  updatedReplicas: 1
```

3. changed number of nodes to 2. and applying example.yaml
```
Johns-MacBook-Pro:crdb-operator johnkendall$ kubectl get pods
NAME                            READY   STATUS    RESTARTS   AGE
crdb-0                          1/1     Running   0          20h
crdb-operator-68d986bdd-xdch2   1/1     Running   0          22h
Johns-MacBook-Pro:crdb-operator johnkendall$ kubectl get sts crdb -o yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: "2020-05-22T21:34:17Z"
  generation: 1
  labels:
    app.kubernetes.io/component: database
    app.kubernetes.io/instance: crdb
    app.kubernetes.io/managed-by: crdb-operator
    app.kubernetes.io/name: cockroachdb
    app.kubernetes.io/part-of: cockroachdb
  name: crdb
  namespace: default
  ownerReferences:
  - apiVersion: crdb.cockroachlabs.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: CrdbCluster
    name: crdb
    uid: fd6beee8-9c73-11ea-a4f5-42010a8e00f1
  resourceVersion: "40842"
  selfLink: /apis/apps/v1/namespaces/default/statefulsets/crdb
  uid: fd72a8c7-9c73-11ea-baa1-42010a8e00b9
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: database
      app.kubernetes.io/instance: crdb
      app.kubernetes.io/name: cockroachdb
  serviceName: crdb
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: database
        app.kubernetes.io/instance: crdb
        app.kubernetes.io/name: cockroachdb
    spec:
      containers:
      - args:
        - shell
        - -ecx
        - '>- exec /cockroach/cockroach start --join=crdb-0.crdb.default:26257 --advertise-host=$(hostname
          -f) --logtostderr=INFO --certs-dir=/cockroach/cockroach-certs/ --http-port=8080
          --port=26257 --cache=25% --max-sql-memory=25%'
        env:
        - name: COCKROACH_CHANNEL
          value: kubernetes-helm
        image: cockroachdb/cockroach-unstable:v20.1.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: http
            scheme: HTTPS
          initialDelaySeconds: 30
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        name: db
        ports:
        - containerPort: 26257
          name: grpc
          protocol: TCP
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 2
          httpGet:
            path: /health?ready=1
            port: http
            scheme: HTTPS
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /cockroach/cockroach-data/
          name: datadir
        - mountPath: /cockroach/cockroach-certs/
          name: certs
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 60
      volumes:
      - emptyDir: {}
        name: datadir
      - name: certs
        projected:
          defaultMode: 256
          sources:
          - secret:
              items:
              - key: ca.crt
                path: ca.crt
              - key: tls.crt
                path: node.crt
              - key: tls.key
                path: node.key
              name: crdb-node
          - secret:
              items:
              - key: tls.crt
                path: client.root.crt
              - key: tls.key
                path: client.root.key
              name: crdb-root
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
status:
  collisionCount: 0
  currentReplicas: 1
  currentRevision: crdb-6f8bc5448f
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updateRevision: crdb-6f8bc5448f
  updatedReplicas: 1


```

**Comment by vladdy** [comment]
I see that you had the operator running for some time around that moment ("crdb-operator-68d986bdd-xdch2"'s age was 22 hours). I think it would be useful to ensure you use the operator built with the latest changes. 

As an option, you can remove the deployed operator and just start the local one on top of the commit with `WATCH_NAMESPACE=default make run`. Also, I'm not sure if 2 nodes is a configuration supported by CockroachDB itself. I would offer to test the scaling to 3 nodes.

**Comment by johnrk** [comment]
I created a new cluster, ran it locally with this commit (#20 ) with 3 nodes, and it's still not working. Running "kubectl get pods" didn't show resources.

**Comment by vladdy** [comment]
I'm unable to replicate it in my env, but I'll try to test it in GKE tomorrow.

**Comment by vladdy** [comment]
@johnrk sorry, I did not realize this got closed when my PR was merged. Definitely, I did not expect that. I'm still unable to replicate the problem. Is it still not working for you?

**Comment by chrislovecnm** [comment]
@johnrk what is the status on this?

**Comment by johnrk** [comment]
@chrislovecnm , this issue is still open. We still need to make this work.

**Comment by chrislovecnm** [comment]
@johnrk can you break this bug apart into the separate issues that you had? For instance, I am able to change the size of the cluster and also the version of cdb container.

**Comment by johnrk** [comment]
You're correct that we can successfully changes number of (CockroachDB) nodes and versions.

However, changes to the pv and pvc doesn't appear to work. I've separated that out in this issue: https://github.com/cockroachdb/cockroach-operator/issues/91
