### ISSUE TITLE
proposal: rename "spec.nodes" to "spec.replicas"

### ISSUE THREAD

**Issue by robinbraemer** [cockroachdb/cockroach-operator#221]
I suggest naming the `spec.nodes` field in the `CrdbCluster` CR to `spec.replicas` in the next version, since such field is commonly named `replicas` in core Kubernetes (ReplicaSet, Deployment, StatefulSet, DaemonSet) and wide space of other CRDs out there.

**Comment by chrislovecnm** [comment]
@johnrk PTAL

**Comment by chrislovecnm** [comment]
@chrisseto thoughts?

**Comment by chrisseto** [comment]
I think I would prefer to keep it as `spec.nodes`. 
Internally and in our docs, a single instance of the cockroach process is [referred to as a node](https://www.cockroachlabs.com/docs/v20.2/cockroach-node.html)
An operator generally translates domain specific concepts into K8s concepts, so I don't see a need to keep the terminology consistent.

I'm also a bit worried that `replicas` could get conflated with the [replicas of data that cockroach stores](https://www.cockroachlabs.com/docs/v20.2/ui-replication-dashboard.html#replicas-per-store).

Do you have examples of other CRDs that use replicas? It looks like [cassandra uses `size`](https://github.com/datastax/cass-operator/blob/master/operator/example-cassdc-yaml/cassandra-3.11.x/example-cassdc-full.yaml#L21).

**Comment by johnrk** [comment]
Pods in CockroachDB are not replicas of one another. We will evaluate changing this to something less confusing in the future.
