### ISSUE TITLE
Generate client certificates

### ISSUE THREAD

**Issue by Nican** [cockroachdb/cockroach-operator#239]
We have a deployment of cockroach-operator on GCP, and we am looking to generate certificates for clients, as documented here: https://www.cockroachlabs.com/docs/v20.2/cockroach-cert#create-the-certificate-and-key-pair-for-a-client 

Where is `ca.key` stored? Or is there another way to generate client certificates? 

And are certificates automatically rotated with cockroach-operator?

**Comment by Nican** [comment]
Reading further into the documentation, it seems like it uses the kubernetes CA as the key, but I am still trying to figure out if only supporting a single client cert is a limitation of the cockroach-operator, or my lack of understanding.

**Comment by chrislovecnm** [comment]
@Nican thanks for the questions!

The operator, but default, uses the Kubernetes certificate manager to create TLS certificates for the database.  A root certificate is created and a node certificate is created.

I recommend using the certificate manager to issue a client certificate. Here is the documentation https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster/ - can can also use the root certificate to generate TLS certificates for the clients via openssl if you want to.

The statement in our documentation is a little off

> By default, the Operator uses the built-in Kubernetes CA to generate and approve 1 client and 1 node certificate for the cluster.

We do not create a client certificate by default, because a user will probably want to create multiple different client certificates.  We create a root and a node certificate, which a client should not use.

cc: @taroface do you mind updating the README?

Another note.  The operator also supports bringing your own certificates.  You are able to create a root cert and a node cert and then store them in secrets.  We have API settings that allow you to set the name of the cert, and then the operator uses your certificates.  This is handy because some k8s distros do not support the k8s tls manager.

@Nican please let us know if you have any feedback on the operator, and one thing that is on the roadmap is to support a CR database that spans multiple k8s cluster.

**Comment by Nican** [comment]
@chrislovecnm, thank you for taking your time for writing all this answer. I really appreciate it. 

I am looking over the link you posted, and it does not make much sense to me, but I will spend some time later this week reading on the subject. I am also looking at `actor/request_cert.go` to see how these certificates are generated.

**Comment by Nican** [comment]
Hello @chrislovecnm, 

Upon further research, it seems like there is a container called `cockroachdb/cockroach-k8s-request-cert` which seems to initialize certificates for applications. I found an example here: https://github.com/cockroachdb/cockroach/blob/master/cloud/kubernetes/example-app-secure.yaml#L19-L41 

It seems to be the best way to go, instead of me trying to manage the certificates myself. What do you think? Is this something that can work with the operator?

**Comment by chrislovecnm** [comment]
@chrisseto, will the request-cert container pull the correct certificate for a client?

cc @johnrk - John who can help with this?

**Comment by Nican** [comment]
I got it working. I also had to also create this 5 resources in the application (non-default) namespace: https://github.com/cockroachdb/cockroach/blob/master/cloud/kubernetes/cockroachdb-statefulset-secure.yaml#L1-L67

And after deployment, run `kubectl certificate approve <my application namespace>.client.root`

I am still trying to understand if I need to create a service account per namespace, or if there is anything better to do, but as far as I can tell, this seems to be a touchless deployment. 

(As a side note, I also had to change the permissions of the certificate files created with this https://stackoverflow.com/a/51195446/99966)

**Comment by chrislovecnm** [comment]
@Nican if you want to document what you did and submit a PR that would be awesome. 

Here would be great doc/client-cert.md!

I am also thinking that we might want to create a other CRD for client certificates. The operator has the code to issue the cert and approve or as well. Thoughts?

**Comment by Nican** [comment]
Sure. I can work on a PR. 

I am not very familiar with k8s, so my recommendations are limited. The current solution I am using seems to have the downside of granting the application access to generate any certificates, which seems against the principle of least privilege. 

But yes, it would be great to just have 1 additional resource to generate all the client certificate necessities would be nice.

**Comment by chrisseto** [comment]
> I am also thinking that we might want to create a other CRD for client certificates. The operator has the code to issue the cert and approve or as well. Thoughts?

+1 to this, having the operator manage client certs could go a very long way for usability.
It may even be reasonable to have the operator contain a CRD for spinning up a pod to access the cluster as well.

> @chrisseto, will the request-cert container pull the correct certificate for a client?

This is actually the first time I've seen that container. Based off the [provided link](https://github.com/cockroachdb/cockroach/blob/master/cloud/kubernetes/example-app-secure.yaml#L19-L41) it seems that the minted certificate will be accepted by any operator created cluster that uses the kubernetes CA.
...which is probably a bug now that I think about it.

Thanks for bringing this up @Nican!

What would be the ideal pattern for your use case? The options I see are:
1. Provide your own certificates to the operator and your application
2. Use an init container (like the one you posted) that will request certificates for accessing a cluster (We'll likely have to make an operator specific container)
3. Ahead of time, submit a CR to have the operator create a client certificate, retrieve that cert from k8s' api, and deploy it manually to your application

**Comment by Nican** [comment]
As a bit of background, as a security requirement for the company I work at requires certificate auto-rotation every 6 months. Part of the reason is that sometimes certificates would expire, and services would have day long outages as developers scramble to figure out how to generate a new certificate and deploy them all the necessary services.

I noticed that GCP's k8s CA certificate is set to expire in 5 years. I am reading over GCP's documentation on [Rotating your cluster credentials](https://cloud.google.com/kubernetes-engine/docs/how-to/credential-rotation) and CockroachDB's documentation on [Rotate Security Certificates](https://www.cockroachlabs.com/docs/stable/rotate-certificates.html), and someone needs to figure out if GCP's certificate rotation strategy also includes creating a combined CA, to ensure that it will not cause downtime for CRDB.

I am also wondering if the Operator's strategy of only generating a single certificate during creation, and if k8s does roll the certificates, if the operator is going to roll with the k8s CA. If I understand correctly, with my current setup, if k8s were to rotate the certificates, the nodes would no longer be able to talk to the application.

Again, I am not too familiar with K8s, but I think the best strategy here would be for certificates to be created with init containers, with an optional approval process. And if there is a way to do so, use a simpler container that does not require to grant permissions of creating certificate to the user's application.

**Comment by chrislovecnm** [comment]
@chrisseto we were just talking about this. @johnrk lets discuss during next standup.

@Nican does your company have a software package for generating certs?

**Comment by Nican** [comment]
Well- I am using CRDB as a pet hobby project to learn GCP.

But otherwise yes, the company I work for uses a program to automatically generate certs. ([Configure certificate auto-rotation in Key Vault](https://docs.microsoft.com/en-us/azure/key-vault/certificates/tutorial-rotate-certificates))

**Comment by lyuma** [comment]
Hey, is there any update on this?

The default client certificates that come with the cockroachdb helm chart expire after a year, and I want to know how to regenerate them.

Right now the cluster has failed and all nodes report the following error:
```
W210727 16:35:22.594634 259 vendor/google.golang.org/grpc/internal/channelz/logging.go:73 ⋮ ‹grpc: Server.Serve failed to complete security handshake from "pipe": remote error: tls: bad certificate›
W210727 16:35:22.594770 95 vendor/google.golang.org/grpc/internal/channelz/logging.go:73 ⋮ ‹grpc: addrConn.createTransport failed to connect to {cockroachdb-2.cockroachdb.default.svc.cluster.local:26257  <nil> 0 <nil>}. Err: connection error: desc = "transport: authentication handshake failed: x509: certificate has expired or is not yet valid". Reconnecting...›
W210727 16:35:22.599207 326 vendor/google.golang.org/grpc/internal/channelz/logging.go:73 ⋮ ‹grpc: addrConn.createTransport failed to connect to {cockroachdb-0.cockroachdb.default.svc.cluster.local:26257  <nil> 0 <nil>}. Err: connection error: desc = "transport: authentication handshake failed: x509: certificate has expired or is not yet valid". Reconnecting...›
```

CA certificate which is still valid:
```
$ openssl x509 -text -in ca.crt
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 0 (0x0)
        Signature Algorithm: ecdsa-with-SHA256
        Issuer: CN = k3s-server-ca@1595345112
        Validity
            Not Before: Jul 21 01:52:12 2020 GMT
            Not After : Jul 19 01:52:12 2030 GMT
```

Client certificate which expired:
```
$ openssl x509 -text -in clt.crt
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            redacted
        Signature Algorithm: ecdsa-with-SHA256
        Issuer: CN = k3s-server-ca@1595345112
        Validity
            Not Before: Jul 21 03:06:53 2020 GMT
            Not After : Jul 21 03:06:53 2021 GMT
```

I need to rotate the cockroachdb client cert, but I can't figure out how to do this.

**Comment by keith-mcclellan** [comment]
check out https://www.cockroachlabs.com/docs/v21.1/operate-cockroachdb-kubernetes.html for how to use a Custom CA for user-managed certs.  This is specific to the operator, we're working on updating our helm guidance but that'll be out soon.  Are you specifically having issues with the helm chart or the operator?

**Comment by lyuma** [comment]
I originally installed it in 2020 via helm chart:
```bash
sudo helm install cockroachdb --values cockroachdb.values.yaml cockroachdb/cockroachdb
sudo kubectl certificate approve default.node.cockroachdb-0
sudo kubectl certificate approve default.node.cockroachdb-1
sudo kubectl certificate approve default.node.cockroachdb-2
sudo kubectl certificate approve default.client.root

curl -o client-secure.yaml https://raw.githubusercontent.com/cockroachdb/cockroach/master/cloud/kubernetes/client-secure.yaml
sudo kubectl apply -f client-secure.yaml
sudo kubectl exec -it cockroachdb-client-secure -- ./cockroach sql --certs-dir=/cockroach-certs --host=cockroachdb-public
```

cockroachdb.values.yaml just has the following:
```yaml
cockroachdb.values.yaml
statefulset:
  resources:
    limits:
      memory: "8Gi"
    requests:
      memory: "8Gi"
conf:
  cache: "2Gi"
  max-sql-memory: "2Gi"
tls:
  enabled: true
```

Thanks for the link to the documentation. It seems to imply that `cockroach cert` is the correct way to replace the certs, but it's not how I originally created them.

Is the approach the helm chart uses still supported? helm sets the cockroachdb containers to run the following initContainer on startup, which is supposed to provision the certificates, but I'm having trouble getting it to renew the expired certs:
```yaml
  initContainers:
  - command:
    - /bin/ash
    - -ecx
    - /request-cert -namespace=${POD_NAMESPACE} -certs-dir=/cockroach-certs/ -symlink-ca-from=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt -type=node -addresses=localhost,127.0.0.1,$(hostname -f),$(hostname -f|cut -f 1-2 -d '.'),cockroachdb-public,cockroachdb-public.$(hostname -f|cut -f 3- -d '.')
    env:
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    image: cockroachdb/cockroach-k8s-request-cert:0.4
    imagePullPolicy: IfNotPresent
    name: init-certs
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /cockroach-certs/
      name: certs
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: cockroachdb-token-9ck55
      readOnly: true
```
