### ISSUE TITLE
Rename to cockroachdb-operator?

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach-operator#24]
I think we should probably rename this to `cockroachdb-operator` (or maybe `cockroach-operator`) for consistency with everything else - we don't really use `crdb` in formal contexts much. It'll get a lot harder to change after this ships, so if we're going to change it we should do it soon.

**Comment by johnrk** [comment]
I completely agree. I was thinking about this earlier.

**Comment by vladdy** [comment]
Let's do it!

**Comment by johnrk** [comment]
@jlinder , can you make this change? It appears I don't have the permissions to do so.

**Comment by jlinder** [comment]
Sure thing! Done. It's now `cockroach-operator`.

**Comment by bdarnell** [comment]
In addition to renaming the repo, we need to rename `cmd/crdb-operator` and any references to it.

**Comment by jlinder** [comment]
> In addition to renaming the repo, we need to rename `cmd/crdb-operator` and any references to it.

Ah! Then perhaps I should change it back while that PR is created? Is there someone I should coordinate with?

**Comment by vladdy** [comment]
@jlinder Feel free to leave it renamed. There is no relationship between the command name and the repo. I'll handle the command renaming later today.

**Comment by jlinder** [comment]
@vladdy Excellent. Done!
