### ISSUE TITLE
Refactor decommission feature code

### ISSUE THREAD

**Issue by alinadonisa** [cockroachdb/cockroach-operator#246]
We need to  create a single package database, remove some scale up code and, clean up a bit

**Comment by johnrk** [comment]
We should enable the feature gates by default. I don't think we should document it because that would go against what we'd recommend for end-users. 

In the operator.yaml - we should indicate that these feature gates are an internal flag for internal testing.

**Comment by johnrk** [comment]
@alinadonisa , can you provide more context?
