### ISSUE TITLE
Test decommission feature and partial updates

### ISSUE THREAD

**Issue by alinadonisa** [cockroachdb/cockroach-operator#247]
To test this you need to:

1. Push a new docker image on docker hub;

2. Follow steps  from README.md, but instead of **applying the operator manifest** from github run following steps:

```bash
export YAML_FILE='operator.yaml'
curl -L https://raw.githubusercontent.com/cockroachdb/cockroach-operator/master/manifests/operator.yaml | 
sed 's|# args: \[\"-feature-gates\",\"PartitionedUpdate=true,UseDecommission=true\"\]|args: ["-feature-gates","PartitionedUpdate=true,UseDecommission=true"]|g' >$YAML_FILE
kubectl apply -f $YAML_FILE
```
3. For decommission just go to the CRD and change the nodes field:

```bash
kubectl edit crdbcluster cockroachdb 
```

**Comment by johnrk** [comment]
@alinadonisa , is this a request for me to acceptance test the decommissioning improvements that you made?

**Comment by alinadonisa** [comment]
yes :) with database load and more complex scenarios if it is possible

**Comment by johnrk** [comment]
This is working.
