### ISSUE TITLE
Add documentation for feature gates

### ISSUE THREAD

**Issue by alinadonisa** [cockroachdb/cockroach-operator#248]
Add FeatureGates.MD file

**Comment by johnrk** [comment]
@taroface , to use partitioned updates and decommissioning properly, feature flags are required to be enabled.

In order to enable them, a user has to uncomment [this line](https://github.com/cockroachdb/cockroach-operator/blob/master/manifests/operator.yaml#L226) in the operator.yaml:

          # uncomment this to enable ParitionedUpdates
          # args: ["-feature-gates","PartitionedUpdate=true,UseDecommission=true"]

**Comment by johnrk** [comment]
@alinadonisa , @chrislovecnm , any other context that you think we should add to the README?

**Comment by taroface** [comment]
@johnrk I can add this instruction. But is there a reason the line can't be enabled by default?

**Comment by johnrk** [comment]
@alinadonisa , @chrislovecnm  ^

Is there a reason this isn't enabled by default?

**Comment by alinadonisa** [comment]
@johnrk  we wanted to test first and make sure that we won't affect the existing functionality. The user can enable/disable it.

**Comment by johnrk** [comment]
@alinadonisa , let's enable it by default then. It's more confusing to have it disabled.

**Comment by alinadonisa** [comment]
@johnrk the idea was to enable them after they pass the testing phase. After we receive a feedback from you we can do that.

**Comment by johnrk** [comment]
@alinadonisa , performing major version upgrades, scaling up/down worked using the steps you described in [this issue](https://github.com/cockroachdb/cockroach-operator/issues/247).

But the Operator pod failed to start when I ran kubectl apply -f manifests/operator.yaml with that one line uncommented.

Am I missing something?

**Comment by johnrk** [comment]
I don't think we should document it because that would go against what we'd recommend for end-users.

In the operator.yaml itself, we should indicate in the comments that these feature gates are an internal flag for internal testing.
