### ISSUE TITLE
Add option to define additonal custom labels and annotations

### ISSUE THREAD

**Issue by arminfelder** [cockroachdb/cockroach-operator#249]
Add an option to define custom labels and annotations to the CRD, which are then applied, to the StatefulSet as well as to the Pods

**Comment by chrislovecnm** [comment]
@johnrk PTAL

@arminfelder this to me sounds like a great idea!  We are always happy to have new contributors.

**Comment by vktr-brlv** [comment]
Hey @chrislovecnm, this one looks like a good start.
Any additional inputs from you appreciated. Thanks!

**Comment by chrislovecnm** [comment]
@vktr-brlv 

1. We need new API values
2. There is a common create labels fund, add the api values to that

**Comment by chrislovecnm** [comment]
Api values https://github.com/cockroachdb/cockroach-operator/blob/master/api/v1alpha1/cluster_types.go

The apis get generated with bazel run //hack:update-crds

**Comment by chrislovecnm** [comment]
https://github.com/cockroachdb/cockroach-operator/blob/master/pkg/labels/label.go

There is the common func

Update the stateful set unit test under /pkg/resources

If you are running any bazel commands we should probably add them to the Developer markdown document

**Comment by chrislovecnm** [comment]
@vktr-brlv let me know what I missed. The operator will deploy to k8s using the bazel commands. See the makefile

**Comment by vktr-brlv** [comment]
@chrislovecnm Thanks!

**Comment by semoac** [comment]
:wave: This is really important to enable integrations with Datadog and another similar agents.

**Comment by keith-mcclellan** [comment]
labels are implemented, Annotations are currently on hold. @chrislovecnm @udnay FYI
