### ISSUE TITLE
Deploy latest CRDB release to OpenShift

### ISSUE THREAD

**Issue by johnrk** [cockroachdb/cockroach-operator#250]
We need to update our listing on OpenShift

Current Bug: Database isn't starting. Known issue that we ran into the first time that we deployed to OpenShift. And we had to do workarounds to get it to work.

**Comment by alinadonisa** [comment]
We have fixed this. Now we need to release the operator first and than the bundle.

**Comment by johnrk** [comment]
@alinadonisa , Let's keep this open until it's successfully deployed

**Comment by keith-mcclellan** [comment]
@alinadonisa once you have the latest changes working on openshift, let's publish to the beta channel on OperatorHub so we can close this out.

**Comment by alinadonisa** [comment]
@keith-mcclellan  is it ok after the demo?

**Comment by keith-mcclellan** [comment]
yes thanks!

**Comment by chrislovecnm** [comment]
@alinadonisa make sure that we generate the csv from the current codebase.  I know I am changing the CRDs in some of my PRs, but not generating the CSV

**Comment by chrislovecnm** [comment]
@johnrk I'm closing this as it is completed
