### ISSUE TITLE
Document that StorageClasses should use reclaim policy: delete

### ISSUE THREAD

**Issue by chrisseto** [cockroachdb/cockroach-operator#251]
When scaling a cluster down, any PVCs created by that cluster will be deleted. However, the underlying PVs will only be cleaned up if the storage class uses the `Delete` reclaim policy.

If the reclaim policy is `Retain`, users may accidentally hemorrhage money via unused disks.
If the reclaim policy is `Recycle`, I have no idea what will happen.

cc @alinadonisa

**Comment by chrislovecnm** [comment]
@chrisseto what is the default in GKE?

**Comment by chrisseto** [comment]
To the best of my knowledge, the default is always `Retain`
