### ISSUE TITLE
Not cleaning up TLS secret

### ISSUE THREAD

**Issue by chrislovecnm** [cockroachdb/cockroach-operator#256]
When we delete a CR cluster the operator and k8s is not cleaning up the secrets.

@alinadonisa I do not think this is filed as a bug yet.  Are you fixing this in the openshift PR?

**Comment by chrislovecnm** [comment]
@keith-mcclellan this is one that fell through the cracks

**Comment by keith-mcclellan** [comment]
We are going to handle this by documenting that this needs to be manually cleaned up for the time being. @taroface I think you already have a ticket for this, correct?

**Comment by taroface** [comment]
I don't think that I do. @johnrk can you confirm?

**Comment by johnrk** [comment]
@taroface , we have one now: K8s Operator: [Guidance for manually deleting secrets #9830](https://github.com/cockroachdb/docs/issues/9830)
