### ISSUE TITLE
Red Hat Operator Image should be modified from bazel

### ISSUE THREAD

**Issue by alinadonisa** [cockroachdb/cockroach-operator#261]
The Red Hat operator image should be set from a single place when running bazel. 
This should be done on bundle/packagemanifest generation step.
Impacted targets are **release/update-pkg** and **gen-csv**.

**Comment by johnrk** [comment]
@alinadonisa , can you confirm that this is fixed?

**Comment by alinadonisa** [comment]
@johnrk  this is done, there will be another task for the release process
