### ISSUE TITLE
StatefulSet will not come back online 

### ISSUE THREAD

**Issue by Nican** [cockroachdb/cockroach-operator#262]
**Scenario:** 
While using K8s on GCP, I wanted to give the VMs more memory, so I created a new pool of nodes with different configuration, and then deleted the first pool. 

**Expected behavior:**
For the pods to roll over gracefully to the new nodes.

**What happened:** 
The first mistake seems like a problem in behavior from GCP, where I got into a state where all 3 CRDB pods were evicted from the old pool at the same time, causing some unavailability on the cluster. 

The second worse mistake is that the pods were not coming back online. From I could tell, the StatefulSet was bringing up one pod at a time. It was waiting for the first pod to become ready before starting up the second pod, but the first pod was never  becoming ready because it needed the second node to reach a quorum. 

**Mitigation:**
I tried modifying the StatefulSet to start all nodes at once, but I guess since that StatefulSet was being managed by the cockroach-operator, none of the changes seemed to work, and were just reverted back. I tried changing the [MaxUnavailable and MinAvailable](https://github.com/cockroachdb/cockroach-operator/blob/a2b8e0412e983f1eacccf50591fc06f7ee53c944/api/v1alpha1/cluster_types.go#L71-L80) settings of the operator, but it did not seem to have any effect. 

I eventually reached a mitigation where I uninstalled the operator
```
kubectl delete -f https://raw.githubusercontent.com/cockroachdb/cockroach-operator/master/manifests/operator.yaml
```
And then I modified the StatefulSet, by changing the `readinessProbe` from `/health?ready=1` to `/health`.
```
        readinessProbe:
          failureThreshold: 2
          httpGet:
            path: /health
            port: http
            scheme: HTTPS
```
The "trick" here is that by removing the `ready=1` from the readiness path, it causes the endpoint to always return 200, even though the json body contains an error, and k8s would consider that health, and roll out the next pod. 

After all the nodes were brought back online, I was able to reinstall the operator
```
kubectl apply -f https://raw.githubusercontent.com/cockroachdb/cockroach-operator/master/manifests/operator.yaml
```
And then the operator immediately overwrote the StatefulSet readiness probe back to `/health?ready=1`, and the cluster was back to normal. 

Does there exist a better way to solve this? How do restart a cluster once all nodes are brought offline?

**Comment by chrislovecnm** [comment]
> While using K8s on GCP, I wanted to give the VMs more memory, so I created a new pool of nodes with different configuration, and then deleted the first pool.

I do not understand what you mean. Did you edit the CR to give the database nodes more memory?

**Comment by Nican** [comment]
The nodes were too small, and did not have enough memory. I had to create new VMs with more memory, and migrate the pods over.

![image](https://user-images.githubusercontent.com/796294/102418845-6d470980-3fb3-11eb-9748-62e11b09eb99.png)

**Comment by chrislovecnm** [comment]
You could have done a kubectl rolling-update, and it would have moved the pods. These tasks are a more kube management process and not something the operator would do. 

You would cordón the old nodes and create a new node pool. Then do a rolling update restart with the statefulset. You can use kubectl to perform all of these tasks.

This is probably not something the operator should support since this is managing nodes and not the database. Please close this issue if I have answered your questions!

**Comment by Nican** [comment]
Let me get back to you on that one. 

The problem is not necessary the nodes, but really, a disaster scenario for the CRDB cluster. If I delete the availability set, but not delete the persistent disks, and try re-creating the CRDB cluster again with the same disks, the cluster might not come back online.

**Comment by johnrk** [comment]
@Nican , this should be fixed. Is this still the case with the latest?

**Comment by chrislovecnm** [comment]
Closing this
