### ISSUE TITLE
First Draft of Test Plan

### ISSUE THREAD

**Issue by chrislovecnm** [cockroachdb/cockroach-operator#265]
Release an alpha or beta version of the operator and use that version during the testing (you can also build off of a tag before the container is pushed)

1. Create a 5 node cluster with an older CR version
2. Update the cluster to the latest CR version
3. Downsize the cluster to 3 nodes - test cluster with SQL
4. Delete the cluster
5. Create a new cluster with 10 GB PVC with 3 nodes
6. Increase the PVC size to 20 GB
7. Increase the number of nodes to 5
8. Modify the MaxAvailable in the PDB
9. Change various API values for instance `GRPCPort`
10. Add `AdditionalArgs` to CR
11. Add Resource Limits to CR

What am I missing?  Should we test `PullPolicyName` and all the API values for instance?

**Comment by johnrk** [comment]
@chrislovecnm , two things:

1. Is our [Custom Resource Definition](https://github.com/cockroachdb/cockroach-operator/blob/master/config/crd/bases/crdb.cockroachlabs.com_crdbclusters.yaml) the source of truth of what we expose in our API for the Operator?
2. Can you specify which items in our API, such as PullPolicyName, are documented, tested, untested?

**Comment by johnrk** [comment]
?@chrislovecnm , a few additional follow up questions:
we need to update some of our docs to accomplish some of these tests for the bug bash by next Thursday. Can you clarify the following:
- In addition to my questions above, in this test case "Downsize the cluster to 3 nodes - test cluster with SQL" - I assume open a SQL shell on a pod and run a SQL command for the "test cluster with SQL" part of that?
- What are the steps for modifying API values (e.g. GRPCPort and MaxAvailable)? We don't have an example yaml for all of the API values, and new users may be unclear on how to structure a yaml file. What are the general steps for a user to use the API given example.yaml?
- How does "Add AdditionalArgs to CR" work?
- Lastly, can you clarify what you mean by "Add Resource Limits to CR"?

cc @taroface

**Comment by johnrk** [comment]
> - In addition to my questions above, in this test case "Downsize the cluster to 3 nodes - test cluster with SQL" - I assume open a SQL shell on a pod and run a SQL command for the "test cluster with SQL" part of that?
@chrislovecnm : Yes. and we should run some stress tests while scaling down. have someone run "cockroach demo." 

> - What are the steps for modifying API values (e.g. GRPCPort and MaxAvailable)? We don't have an example yaml for all of the API values, and new users may be unclear on how to structure a yaml file. What are the general steps for a user to use the API given example.yaml?
@chrislovecnm : make sure users understand PDBs. and point to the CRD definition: https://github.com/cockroachdb/cockroach-operator/blob/master/config/crd/bases/crdb.cockroachlabs.com_crdbclusters.yaml#L293

grpcPort in CRD: https://github.com/cockroachdb/cockroach-operator/blob/master/config/crd/bases/crdb.cockroachlabs.com_crdbclusters.yaml#L261

additionalArgs in CR: https://github.com/cockroachdb/cockroach-operator/blob/master/config/crd/bases/crdb.cockroachlabs.com_crdbclusters.yaml#L58

@chrislovecnm : ideally, we have API validation: https://github.com/cockroachdb/cockroach-operator/issues/87

Resource limits is documented in the readme: https://github.com/cockroachdb/cockroach-operator#set-resource-requests-and-limits
