### ISSUE TITLE
Red Hat Bug: Using Old Version of UBI | Causing us to not pass

### ISSUE THREAD

**Issue by johnrk** [cockroachdb/cockroach-operator#267]
It appears we're relying on a cached version of the UBI

What if we found a way to ensure that we use the correct UBI version?

Red Hat:
> I checked the logs, and could find two failed items, which cause the image status failed. "free_of_important_vulnerabilities" is a new test item, but which is not showed on the scan result page.
> 
> "isv_plugin_version": "2017101700",
> 
> "Results": [{"Custom":
> 
> {"failing_checks":
> 
> [
> "atomic_help_exists",
> "free_of_important_vulnerabilities"]
> 
> Could you help to run the command "podman inspect xxx" to inspect your image, to make sure the latest base image is used in your operator image? If not, update the base image and rerun the test.

**Comment by keith-mcclellan** [comment]
Looks like in `WORKSPACE` we pinned a specific sha for a base image rather than taking the latest tag:

current:
`container_pull(
    name = "redhat_ubi_minimal",
    registry = "registry.access.redhat.com",
    repository = "ubi8/ubi-minimal",
    digest = "sha256:3364fa3bd7a5aea2932e352a446ec7f46378885f6a8f03847acc64dd100aa4cc",
)
`

should be:

`container_pull(
    name = "redhat_ubi_minimal",
    registry = "registry.access.redhat.com",
    repository = "ubi8/ubi-minimal",
    digest = "sha256:latest",
)
`
I think.  If this doesn't work then `tag = "latest"` should.  @chrislovecnm what do you think?

**Comment by alinadonisa** [comment]
@keith-mcclellan  I already changed to tag latest and I will push again in one hour 🙂. Thanks

**Comment by alinadonisa** [comment]
@keith-mcclellan, @johnrk  it worked ...:) Now I will continue with the bundle :)

**Comment by keith-mcclellan** [comment]
![Screen Shot 2020-12-30 at 11 50 13 AM](https://user-images.githubusercontent.com/4730669/103368540-cc1d8000-4a95-11eb-91d9-a6dd34682cea.png)
I published it for you because I think @JuanLeon1 is OOO.  I think you can close this.
