### ISSUE TITLE
Contractors (Chris Love and Alina) Need Access to VMware, AWS, and Azure Environments

### ISSUE THREAD

**Issue by johnrk** [cockroachdb/cockroach-operator#268]
To ensure the Operator works in more environments, @chrislovecnm and @alinadonisa need access to VMware, AWS, and Azure environments for testing. We have only tested officially in GKE. 

Sales Engineering and customers have expressed support for these environments.

**Comment by kenliu** [comment]
@rail assigning this issue to you for your visibility. let's talk about what we can do here.
cc @jlinder

**Comment by kenliu-crl** [comment]
@udnay I'm going to close this request because it's not clear what exactly is needed here. I think we need to clarify what the k8s team wants to pursue as far as testing in AWS and Azure and then we can figure out what the dev-inf team needs to do to help get it set up.
