### ISSUE TITLE
Make the default config a 3 port configuration to separate GRPC and SQL traffic

### ISSUE THREAD

**Issue by keith-mcclellan** [cockroachdb/cockroach-operator#271]
Our best practices now recommend splitting the SQL port off from the GRPC port.  Not only does this enable us to allow SQL access from outside the cluster without exposing node to note comms, but it also allows admins to configure TLS encryption for client communications without requiring all those clients to trust the kubernetes CA.

**Comment by chrislovecnm** [comment]
Need to do this feature along with TLS or before.  I think I can do this before.

**Comment by keith-mcclellan** [comment]
`--sql-addr=:5432` should be the default addition to the cockroach start command, ref: https://www.cockroachlabs.com/docs/stable/cockroach-start.html#start-a-cluster-with-separate-rpc-and-sql-networks and https://www.cockroachlabs.com/docs/stable/cockroach-start.html

**Comment by chrislovecnm** [comment]
SQL: 5432
GRCP: 26257

Add API value to allow setting the SQL port.

**Comment by chrislovecnm** [comment]
Add public and private key for the SQL.

**Comment by keith-mcclellan** [comment]
split TLS - https://www.cockroachlabs.com/docs/v20.1/create-security-certificates-custom-ca#split-ca-certificates

**Comment by keith-mcclellan** [comment]
From @bdarnell - the cockroach cloud standard here is to use 26257 for sql and move the grpc port, which we can increment to 20258 by default.  We still want all three ports (db console, sql, and grpc) to be configurable so we can provide a CR example in the docs to show how to expose CRDB over the default psql port.

**Comment by chrislovecnm** [comment]
```
I think I'm 👎 on using port 5432 because we should use 26257 for consistency with other deployments, although there are also good arguments in favor using it (especially since 26257 is our only officially allocated port and if we're going to use separate RPC and SQL ports we have to use something for the port that's not getting 26257). Regardless, it's not something for the k8s operator to unilaterally decide, it's something we need to think about as we update other deployment docs for three-port configurations.
```

**Comment by chrislovecnm** [comment]
Here is the example from the documentation

```
cockroach start --sql-addr=:26267 --listen-addr=:26258 --join=node1:26258,node2:26258,node3:26258 --certs-dir=~/cockroach-certs
```
Am I following this?

**Comment by keith-mcclellan** [comment]
this looks right to me.
