### ISSUE TITLE
Operator needs to support auto-renew and rotate expiring TLS certificates when possible

### ISSUE THREAD

**Issue by keith-mcclellan** [cockroachdb/cockroach-operator#273]
Currently, we don't have an easy way to rotate TLS certificates when they expire.  By default, the internal CA issues certs that expire pretty quickly so this is a blocker for long-running clusters.

**Comment by chrislovecnm** [comment]
So we are not doing default CA certificates now.  Also, I need more business requirements in order to implement this.  I think CR Cloud does this now, can we use there code?

**Comment by keith-mcclellan** [comment]
We still need to be able to rotate the self-signed certs so maybe we repurpose this issue to that?

**Comment by pornpoi** [comment]
I found this problem too. Could you teach me about how to renewal cert?

**Comment by lyuma** [comment]
@keith-mcclellan hey I left a comment over here:
https://github.com/cockroachdb/cockroach-operator/issues/239#issuecomment-887667705
I'm wondering if this is actually the issue I'm running into.

Basically exactly one year after I started the cluster, all the nodes failed with expired certs, and the cluster is non-functional--even if I attempt to destroy and recreate the pods. The fact that the cluster can fail after one year seems like a big risk factor in using cockroachdb from kubernetes.

**Comment by keith-mcclellan** [comment]
This should be implemented now - what version of the operator are you using? Also, we only implemented this for our self-signed certs so user signed certs (or if you used something like cert-manager) you'll have to manage this yourself.  The docs on how to use the operator are available here btw: https://www.cockroachlabs.com/docs/v21.1/operate-cockroachdb-kubernetes.html

**Comment by keith-mcclellan** [comment]
If you're still having issues after all that, please open a new issue with your specific reproduction steps and we'll try to help you out.
