### ISSUE TITLE
Convert Calendar Versioning to a Semantic Versioning

### ISSUE THREAD

**Issue by chrislovecnm** [cockroachdb/cockroach-operator#283]
The cockroach database uses a date versioning and not a semantic version.

For instance, 20.1.1 becomes 201.0.1

We need to remove the first period and a ".0" in the middle of the numbeer

**Comment by keith-mcclellan** [comment]
@chrislovecnm I think @alinadonisa's latest PR makes this redundant since we're properly detecting feature releases now as demonstrated during her demo yesterday.  I'd like to close this if you concur.
