### ISSUE TITLE
Enable feature gates for Partition Updates and Decommissioning by default

### ISSUE THREAD

**Issue by johnrk** [cockroachdb/cockroach-operator#284]
Let's enable the Partitioned Updates and Use Decommissioning Feature by default. 

In addition, let's add a comment in the operator.yaml that clearly communicates that these are for internal use only. We will intentionally hide this from our public docs and README to discourage users from changing these flags.

**Comment by chrislovecnm** [comment]
Feature gates are typically not for just internal use.  Users can test new beta or alpha features.  This functionality models what k8s does.

**Comment by johnrk** [comment]
@chrislovecnm That's fair. But it's problematic if Partitioned Updates and Decommissioning are disabled by default. It would go against Cockroach Labs' best practices if customers are having them disabled.

**Comment by johnrk** [comment]
@chrislovecnm , this has been addressed, correct? If so, I'll close this.
