### ISSUE TITLE
In memory cache for cockroachVersion that can be installed in the cluster

### ISSUE THREAD

**Issue by alinadonisa** [cockroachdb/cockroach-operator#287]
Store the CRDB version <> image name mapping in memory. This allows the operator to not have to run a Job every time it reuses the same container.

**Comment by keith-mcclellan** [comment]
@chrislovecnm @alinadonisa was this covered in the Upgrade work that we've already merged?

**Comment by alinadonisa** [comment]
@keith-mcclellan you said you want to run the job each time, so this is no need it anymore
