### ISSUE TITLE
Save version history

### ISSUE THREAD

**Issue by alinadonisa** [cockroachdb/cockroach-operator#288]
1. Save the CRDB version in an annotation in the statefulset. When the image name or the cockroachVersion API fields we are able to determine if an update is possible or required. We save these values when the statefulset is created, and also when the statefulset is updated.

2. When we create or update a CRDB statefulsets the operator always stores the history of versions. Store a history of the versions in annotation, so that we have a history of updates of the database.

**Comment by johnrk** [comment]
If we currently don't save the version of CockroachDB, how are rolling updates working?

Or is this something else?

**Comment by johnrk** [comment]
Also, is this issue a duplicate and/or related to this issue ([In memory cache for cockroachVersion that can be installed in the cluster](https://github.com/cockroachdb/cockroach-operator/issues/287))?

**Comment by chrislovecnm** [comment]
This is done ... @johnrk close?
