### ISSUE TITLE
Validate version field usage

### ISSUE THREAD

**Issue by alinadonisa** [cockroachdb/cockroach-operator#289]
A user is able to set the CRDB version or the image name. The user cannot set both in the API.

**Comment by johnrk** [comment]
Why are we offering two ways to set the CRDB version in the API (1. CRDB version 2. image name)?

**Comment by johnrk** [comment]
Also, I am guessing that this issue is related to this issue ([Add new cockroachVersion field](https://github.com/cockroachdb/cockroach-operator/issues/286))?

**Comment by chrislovecnm** [comment]
@alinadonisa can we use kubebuilder flags for this?
