### ISSUE TITLE
Add 3 env var for cockroachdb related image on Openshift

### ISSUE THREAD

**Issue by alinadonisa** [cockroachdb/cockroach-operator#290]
1. If a user sets the CRDB version field we will use a container that is provided to the operator via one of the environment variables defined. Each of these environment variables is matched to the current supported CRDB versions.
if the environment variables do not exist the process will fail.

2. If the user sets the container image field the operator will use that container

**Comment by keith-mcclellan** [comment]
currently we are supporting 19.2, 20.1, and 20.2.  We will be removing 19.2 from support in the spring and replacing it with 21.1 once that release is GA.

**Comment by alinadonisa** [comment]
@keith-mcclellan  after speaking with @chrislovecnm  I added the env var value with exact match on the Version Tag. For instance instead of  19.2 we will use 19.2.5. This will help with the partial update code and the private repo issue.

**Comment by keith-mcclellan** [comment]
@chrislovecnm & @alinadonisa -  I'm confused, we discussed not having the full version number in the env variable.  What are the tradeoffs here?

**Comment by chrislovecnm** [comment]
The problem is upgrade path. We need the full semver. What happens when the operator manifest is updated for instance? I have already identified one edge case and I think there are more as well.

**Comment by chrislovecnm** [comment]
@keith-mcclellan as a user in gonna out in 19.2.3 for instance and not 19.2

**Comment by keith-mcclellan** [comment]
There are two upgrade paths - between feature releases and then between patch releases.  You can upgrade or downgrade between patch releases at will because they all use the same version of the database metadata.  That's why we don't require users to set `cluster.preserve_downgrade_option` for patch releases.  For feature releases (jumping from 20.1 to 20.2) there's the chance that the metadata has changes and/or we've deprecated functionality.  But you can go from any 20.1.x release directly to 20.2.x release.

**Comment by chrislovecnm** [comment]
@keith-mcclellan that does not help the operator much. That is how the db is updated not the meta information the user needs to provide the operators.

Here is the use case:

1. user creates two cr db's with 1.19 - alpha and beta
2. the env var is set to 1.19.2 image but is named 1.19
3. the user encounters an issue with alpha database, but not beta
4. the user needs to update alpha to 1.19.3, but not beta

The user cannot do that easily, especially in OpenShift.
