### ISSUE TITLE
TLS Certificate Generation 

### ISSUE THREAD

**Issue by keith-mcclellan** [cockroachdb/cockroach-operator#291]
See below for the feedback from Red Hat on how we're signing and issuing certificates in Kubernetes.

-----
We had several engineers review the Operator and found some issues.  This is a synopsis of internal communication to resolve the issue.

 

The cockroach operator appears to use CSRs in a way that is not compatible with the Kubernetes CSR/v1 API and will stop working in Kubernetes 1.22.  In addition, it relies on long rotation times that OpenShift wants to avoid as part of our security posture and operator managed platform.  Skip to Recommendations.

 

Background

As a platform, OpenShift takes security seriously and part of that stance involves comparatively frequent rotation of both key material and trust for the platform.  The CSR API is part of that and was created and is maintained in service of the platform.  OpenShift rotates the out of the box CSR signers on a regular basis and doing this ensures that trust can always be rotated smoothly.

 

It appears that the cockroach operator is using the CSR API to self-approve certificates that are valid for use against the kube-apiserver, but uses these certificates (both client and server) for cockroach communication.  This usage is unintended by the kubernetes API and was recently clarified in the upstream documentation (https://kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/#kubernetes-signers).  In addition, this usage results in a proliferation of credentials that can act against the kubernetes API and serving certificates that could be used to fool a kube-apiserver into thinking it was speaking to a kubelet.

 

 

Recommendations

If the cockroach operators needs way to create serving and client certificates for its own communication, I would suggest that they either

1 - Create their own CSR signer in their namespace.  The kubernetes API is built to allow this extension.  This would provide direct control over expiry.

2 - Manage their own signer, serving, and client certificates.  This isn't as hard as it sounds, we do this in OCP to manage certificates that cannot rely on the rest of the cluster.  See library-go (https://github.com/openshift/library-go/tree/master/pkg/operator/certrotation) for an example, but other implies can work.

3 - Add a dependency on cert manager and create a chain of trust to manage this.

 

 

Supporting reasoning

which may help other developers follow my train of thought.

 

Current Risks

1 - The usage of CSRs needs to be updated to reflect the CSR v1 API (https://kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/#kubernetes-signers).   This API has made the intent of the API more clear to consumers in v1, but the usage in cockroach-operator is likely to be impacted.

  a - The out of the box signers cover creating client-certificates to speak to the kube-apiserver, a signer for kubelet client certificates, and a signer for kubelet serving certificates.  They for are not intended for generic signing of generic use certificates

  b - The doc also clarifies the trust distribution

  c - The current signer used by cockroachdb is not valid in CSR v1

  d - The beta CSR implementation used by cockroachdb will no longer function in kubernetes 1.22 because the existing API will be removed.

2 - The approach of directly wiring against cert/key pairs instead of a CA bundle appears to preclude rotation by 

  a -  create new

  b - honor old and new

  c - use new 

  d - stop honoring old

 

Stream of investigation

1 - cockroach-operator creates and approves its own CSRs.  

2 - There is a combination serving and client certificate and a client certificate

3 - However, neither request is compatible with the v1 CSR API because it doesn't request a .spec.signerName.  See kube doc (https://kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/#request-signing-process) and the requesting code(https://github.com/cockroachdb/cockroach-operator/blob/3bdae1d4e8da4e179b98e4b718bfc953ac23e1e2/pkg/tls/csr.go#L50).

4 - The combination serving and client cert does not appear to match a valid usage and will be rejected in CSR v1.  See kube doc(https://kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/#kubernetes-signers).

5 - This means that the CSRs are all for .spec.signerName=kubernetes.io/legacy-unknown(http://kubernetes.io/legacy-unknown).  There is no uniform trust distribution for certificates signed this way.  See kube doc(https://kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/#kubernetes-signers).

6 - The combination serving and client certificate appears to be used as both a serving certificate and directly used to verify the connection.  See code(https://github.com/cockroachdb/cockroach-operator/blob/3bdae1d4e8da4e179b98e4b718bfc953ac23e1e2/pkg/actor/partitioned_update.go#L168).  This approach (not using a CA bundle) precludes rotation

7 - This means that even if the operator does update itself to review certificates on expiry, every connection has to be updated simultaneously for a smooth transition.

8 - The client certificate appears to be used to communicate to the cockroach and not to the kubernetes API

**Comment by keith-mcclellan** [comment]
I think this will probably turn into an Epic because I see several things we need to do here:

1) default to splitting the SQL port off the GRPC port so our node to node TLS doesn't impact client certs, and change our pods to expose 3 ports by default instead of two (the default pg sql port is port 5432 so that'd be my preference for the SQL port).
2) set up the GRPC port for a new way of signing mTLS node certs
3) set up the SQL port for a new way of signing client certs
4) set up the UI port for a new way of signing the DB Console cert

In the near-term, I'm not sure if our best path forward is a hard dependency on an external cert manager like Vault or cert-manager, or if we should use the `cockroach cert` tooling to self sign everything and stash the signing cert and the generated certs in cluster-specific secrets.  I'm hoping that if we split the node and client ports that'll make it so we can at least use the k8s CA for the node certs, but reading the latest CSR spec doesn't make me confident there.  I expect we're going to end up with at least two (if not more) cert signing patterns as our default behavior here though.

**Comment by keith-mcclellan** [comment]
Another thing that is unclear to me is how we're going to be able to manage pod health checks if the UI cert (which also gets used for the RESTful /health endpoints) doesn't have shared trust with k8s.

**Comment by andy-kimball** [comment]
I'm not sure I understand what the problem is here. Is it that we are not creating our own CA that's CRDB-specific, but instead relying on a default K8s CA? Or is the problem that the operator is not rotating node and client certificates regularly? Or both?

**Comment by keith-mcclellan** [comment]
@andy-kimball both, we're relying on the Kubernetes CA and they've deprecated that CA's ability to issue application certificates (it's being removed entirely in 1.22).  And we also don't auto rotate certificates.  We discovered this bug because while OpenShift will still let us issue these certificates using the internal CA, they have a very short lifespan (14 days) and they've disabled `kubeadm certs renew` so we can't manually rotate them.

**Comment by johnrk** [comment]
@keith-mcclellan , based on the feedback (above) from Red Hat, we could address the major risks here by updating our usage of the beta CSR implementation to the [v1 CSR implementation](https://kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/#kubernetes-signers)). This would work for our integration with OpenShift until version 1.22, which comes out later this year. Kubernetes v1.21 is in Alpha. Can you confirm?

**Comment by andy-kimball** [comment]
@keith-mcclellan, I don't see the connection between the two problems (using wrong CA and not supporting rotation) and your recommendations (updating how we set up GRPC, SQL, etc ports). Why would doing those things you suggest solve the problems that RedHat has brought up? Also, does the CRDB binary already support everything you want to do, and you're just saying you want to change the default configuration used by the Operator?

**Comment by bdarnell** [comment]
We're working on building cert generation into CRDB itself (will hopefully make it into 21.1, see https://github.com/cockroachdb/cockroach/pull/51991). Given that, I think the best short-term plan is to take control of the cert generation in the operator instead of updating to use newer k8s APIs. This could either mean executing `cockroach cert` commands from the operator, or if it's tricky to manage the external container, we could use other cert tools (including [`openssl`](https://www.cockroachlabs.com/docs/stable/create-security-certificates-openssl.html)) or copy [the relevant go code from the main repo](https://github.com/cockroachdb/cockroach/blob/master/pkg/security/certs.go). Generate the certs and keys and write them all to the k8s secret store.

> 2 - The approach of directly wiring against cert/key pairs instead of a CA bundle appears to preclude rotation by

CRDB does support rotation with a CA bundle as described here (I'm not sure if the operator is doing something that interferes with that or if there's a misunderstanding. From comment 6 it looks like the former). 

> 4 - The combination serving and client cert does not appear to match a valid usage and will be rejected in CSR v1.

We combine client and server usage in the same cert for simplicity, but if that's forbidden by policy we also support separating them: https://www.cockroachlabs.com/docs/stable/authentication.html#using-split-ca-certificates

> default to splitting the SQL port off the GRPC port so our node to node TLS doesn't impact client certs, and change our pods to expose 3 ports by default instead of two (the default pg sql port is port 5432 so that'd be my preference for the SQL port).

It's definitely a good idea to use separate ports here, but it's separate from any cert considerations. We don't currently support a separate cert for SQL usage whether it's on the same port or a different one. And when we do support separate certs, it won't be necessary to use separate ports to use them. https://github.com/cockroachdb/cockroach/issues/39326

I think I'm 👎  on using port 5432 because we should use 26257 for consistency with other deployments, although there are also good arguments in favor using it (especially since 26257 is our only officially allocated port and if we're going to use separate RPC and SQL ports we have to use *something* for the port that's not getting 26257). Regardless, it's not something for the k8s operator to unilaterally decide, it's something we need to think about as we update other deployment docs for three-port configurations.

**Comment by chrislovecnm** [comment]
per @bdarnell 

> sql.NormalizeAndValidateUsernameNoBlocklist just calls back out to security.MakeSQLUsernameFromUserInput, so you can avoid the pkg/sql dependency. but the security package function still depends on pkg/sql/lexbase. all that's happening here is that we're transforming the name to lowercase, restricting the character set and length. `const usernameHelp = "Usernames are case insensitive, must start with a letter, " +
	"digit or underscore, may contain letters, digits, dashes, periods, or underscores, and must not exceed 63 characters."
