### ISSUE TITLE
Update docs to include guidance on how to use Custom CA

### ISSUE THREAD

**Issue by johnrk** [cockroachdb/cockroach-operator#292]
For the Operator, Helm Chart, and other install patterns, @keith-mcclellan identified our need to have guidance on how to use a custom CA with the Operator.

1. Generate certs using **Cockroach Cert:** https://www.cockroachlabs.com/docs/v20.1/cockroach-cert.html

2. **Inject client certs into secret:** `kubectl create secret tls $clientTLSSecret --key="client.key" --cert="client.crt"`
3. **Inject node certs into secret:** `kubectl create secret tls $nodeTLSSecret --key="node.key" --cert="node.crt"`

@keith-mcclellan using TLS instead of Generic command is compatible with k8s. Keith's understanding.

To use the custom CA with the Operator, we need to use the following Operator API fields:
4. 
- [clientTLSSecret](https://github.com/cockroachdb/cockroach-operator/blob/master/config/crd/bases/crdb.cockroachlabs.com_crdbclusters.yaml#L68)
- [nodeTLSSecret](https://github.com/cockroachdb/cockroach-operator/blob/master/config/crd/bases/crdb.cockroachlabs.com_crdbclusters.yaml#L305)

Chris Love: we probably want an example in the examples folder.

@chrislovecnm , can you confirm this is correct? Can you specify what steps one should take to get a client TLS Secret and node TLS Secret?

@keith-mcclellan , what details should we include on how to use a custom CA with the Helm Chart? Is it the same as the Operator?

**Comment by chrislovecnm** [comment]
Please use the cockroach binary to generate the certificates.

**Comment by johnrk** [comment]
Guide on using the cockroach binary: https://www.cockroachlabs.com/docs/v20.2/secure-a-cluster.html#step-1-generate-certificates

**Comment by chrislovecnm** [comment]
`kubectl create secret tls test-tls --key="tls.key" --cert="tls.crt"` - this should help creating the secrets cc @johnrk

**Comment by taroface** [comment]
Closing in favor of #9359
