### ISSUE TITLE
Operator pod fails to start with zapLogger error

### ISSUE THREAD

**Issue by bootstrapsp** [cockroachdb/cockroach-operator#296]
Doc version :  
20.2.4

To reproduce : 
1. kubectl apply -f https://raw.githubusercontent.com/cockroachdb/cockroach-operator/master/config/crd/bases/crdb.cockroachlabs.com_crdbclusters.yaml 
2. kubectl apply -f https://raw.githubusercontent.com/cockroachdb/cockroach-operator/master/manifests/operator.yaml

`serviceaccount/cockroach-database-sa created
clusterrolebinding.rbac.authorization.k8s.io/cockroach-database-rolebinding created
role.rbac.authorization.k8s.io/cockroach-operator-role created
clusterrolebinding.rbac.authorization.k8s.io/cockroach-operator-rolebinding created
clusterrole.rbac.authorization.k8s.io/cockroach-operator-role created
serviceaccount/cockroach-operator-sa created
rolebinding.rbac.authorization.k8s.io/cockroach-operator-default created
deployment.apps/cockroach-operator created`

When checking for pods with

`kubectl get pods`

shows :
`cockroach-operator-8448dd9445-gb6qw               0/1     CrashLoopBackOff   5          4m49s`

kubectl logs cockroach-operator-8448dd9445-gb6qw shows following : 

`2021-01-24T16:25:41.932Z	ERROR	setup	unable to parse feature-gates flag	{"error": "unrecognized feature gate: Upgrade"}
github.com/go-logr/zapr.(*zapLogger).Error
	external/com_github_go_logr_zapr/zapr.go:128
main.main
	cmd/cockroach-operator/main.go:64
runtime.main
	GOROOT/src/runtime/proc.go:203`

**Comment by chrislovecnm** [comment]
Remove the Upgrade feature flag and add the PartionUpdate feature flag.

**Comment by bootstrapsp** [comment]
Thanks will check this out. For now we moved on with manual config.

**Comment by chrislovecnm** [comment]
Fixed with https://github.com/cockroachdb/cockroach-operator/pull/298

 Let me know if we can close this issue!

**Comment by bootstrapsp** [comment]
yes i am good to close this - thanks!
