### ISSUE TITLE
Operators Major Version Upgrade/Downgrades

### ISSUE THREAD

**Issue by chrislovecnm** [cockroachdb/cockroach-operator#30]
As an operator, I can perform major version upgrades via rolling restarts,
so that my application can take advantage of new features and use on a
more stable version of CockroachDB without losing availability.

**Comment by chrislovecnm** [comment]
When doing a major version upgrade one setting via a SQL call needs to be made.

**Comment by johnrk** [comment]
Also, major version upgrades require a finalization step.

**Comment by johnrk** [comment]
I've separated out the minor version upgrade work item into this issue: https://github.com/cockroachdb/cockroach-operator/issues/50

It requires less work because of the finalization step requirement with major version upgrades.

**Comment by chrislovecnm** [comment]
This should be implemented.  I need to check on the e2e test, and it may need improving, but we can open a separate issue for that.  Can you please test @johnrk
