### ISSUE TITLE
Bug: Operator Fails to deploy - 

### ISSUE THREAD

**Issue by johnrk** [cockroachdb/cockroach-operator#300]
Problem: I'm unable to deploy the latest Operator

**Repro steps:**
kubectl apply -f manifests/operator.yaml

**Expected Result:**
Operator in running state

**Actual Result:**
- STATUS: CrashLoopBackOff
- container is in restart loop and failing

**Screenshot:**
<img width="1920" alt="Screen Shot 2021-01-25 at 6 59 59 PM" src="https://user-images.githubusercontent.com/1663752/105781089-da997300-5f3f-11eb-88fa-798497279692.png">

**Comment by chrislovecnm** [comment]
@johnrk this is the problem with the older container deployed to dockerhub

**Comment by johnrk** [comment]
@chrislovecnm , ack

I'll leave this open until we address the problem

**Comment by keith-mcclellan** [comment]
@johnrk can you verify that the image @jlinder pushed last night fixes this issue?

**Comment by chrislovecnm** [comment]
Fixed in https://github.com/cockroachdb/cockroach-operator/pull/298

**Comment by johnrk** [comment]
It's working. Thanks, All
