### ISSUE TITLE
Operator logging is not configurable

### ISSUE THREAD

**Issue by chrislovecnm** [cockroachdb/cockroach-operator#304]
We need to take all of our logging and utilize logging levels.  At scale, the operator is going to produce way too much logging.  We need to implement and document DEBUG, INFO, WARN, and ERROR logging levels.

https://github.com/cockroachdb/cockroach-operator/blob/bb9aeafd821197863f73224255d12de46ebb12df/pkg/actor/decommission.go#L61

Is a great example where we should have DEBUG logging level and not INFO.  The logging library that we use allows for the implementation of different "v" logging levels.

For instance

https://github.com/go-logr/logr/blob/8fc6c73f3911f11de3d0c18ade9880f1114ae72f/examples/usage_example.go#L66

DEBUG = v 10
INFO = v 8
WARN = v 6
ERROR = v1

The operator should run with WARN as the default logging level.

**Comment by johnrk** [comment]
Here are docs on CockroachDB's existing logging levels: https://www.cockroachlabs.com/docs/stable/debug-and-error-logs.html#severity-levels

**Comment by johnrk** [comment]
This is related to this open bug: https://github.com/cockroachdb/cockroach-operator/issues/175
