### ISSUE TITLE
Status update improvements

### ISSUE THREAD

**Issue by chrislovecnm** [cockroachdb/cockroach-operator#305]
Once we have improved the Status capability via the OpenShift work, all of our actors need to update the status as they do work.  This will allow for better debugging functionality, and also, this will allow different actors to not do operations on a cluster when an error has occurred.  The operator has little functionality that allows the operator to stop working on a cluster, even if an error has occurred.  This can cause issues when say, an upgrade fails.  We do have some error handling, but it is limited.

**Comment by chrislovecnm** [comment]
@keith-mcclellan thoughts?

**Comment by keith-mcclellan** [comment]
how useful would this be outside of an OpenShift based deployment?  If it will work generically it's worth considering, otherwise we should put this in the backlog of future work.

**Comment by alinadonisa** [comment]
@keith-mcclellan , @chrislovecnm  it is already in progress and used on Openshift. For now it is very generic and simple. It sets 3 states: Failed, Starting and Finished. Starting is the state used mainly for Openshift to skip the timeout. Failed it logs the errors from the operator and Finished will signal that the reconciliation of the CRD finished without any error on any steps.

**Comment by keith-mcclellan** [comment]
As long as this work isn't so openshift specific that we end up having to reimplement this logic to work properly in a generic k8s environment I agree this is necessary for our next release

**Comment by chrislovecnm** [comment]
This is needed cross platform

**Comment by chrislovecnm** [comment]
This is complete.  Closing
