### ISSUE TITLE
Update CI - e2e command

### ISSUE THREAD

**Issue by chrislovecnm** [cockroachdb/cockroach-operator#354]
Hi all

We have changed our e2e command since we are working on getting GKE running.

```make
.PHONY: test/e2e/kind
test/e2e/kind:
        bazel run //hack:kind-start
        bazel test --stamp //e2e/...
        bazel run //hack:kind-stop
```

We have the above make command which can be run, or just run the bash command-line options.  If we can update the command in teamcity, that would be awesome!

**Comment by rail** [comment]
Done
