### ISSUE TITLE
Get GKE nightly build working

### ISSUE THREAD

**Issue by chrislovecnm** [cockroachdb/cockroach-operator#361]
Get this target running via a nightly build

https://github.com/cockroachdb/cockroach-operator/blob/95eea83c7233c93f7a66f01243d8ceb9a180ca45/Makefile#L126

We will need to set the parameters properly and also the build boxes will need permissions to create GKE clusters.  Also, we will want to look at a janitor for GKE clusters.

https://github.com/cockroachdb/cockroach-operator/blob/7bb3c0aa60a42a76a1f355bba6220bccf87cf545/Makefile#L101-L128

All of the env variables in the above Makefile snippet require setting.

Examples of setting the values are here

https://github.com/cockroachdb/cockroach-operator/blob/7bb3c0aa60a42a76a1f355bba6220bccf87cf545/Makefile#L25-L28

The test process will probably need to run `gcloud init` as well.

**Comment by chrislovecnm** [comment]
We will need:

1. a GCP project to do nightly builds
2. a service account that has permissions to launch a cluster
3. gcloud installed

Eventually, we will need a janitor, but for now, that is out of scope.

**Comment by rail** [comment]
I created a [TeamCity configuration](https://teamcity.cockroachdb.com/viewType.html?buildTypeId=Cockroach_CockroachOperator_Nightlies_GkeNightly&tab=buildTypeStatusDiv) for this. It will be running  daily at 6:00 UTC. (I randomly picked the time, let me know if you have any preferences).

It runs in the `cockroach-operator-nightlies` project in GCE. The system account granted  the `roles/container.serviceAgent` role and it looks like it can create and destroy clusters.

Let me know if I should change the roles for this account.

**Comment by rail** [comment]
Please reopen if we need to change anything.
