### ISSUE TITLE
Enable CI as blocking

### ISSUE THREAD

**Issue by chrislovecnm** [cockroachdb/cockroach-operator#362]
@keith-mcclellan can we put back CI to blocking?  I think we are ready.

**Comment by rail** [comment]
I enabled CI as blocking for the `master` branch. Let me know if it's too early, so I revert the change.

**Comment by rail** [comment]
Correct, it should block from merging PRs that don't pass the CI check.

**Comment by rail** [comment]
![image](https://user-images.githubusercontent.com/42865/111699045-f9b0d480-880d-11eb-972c-d2cb72efd74a.png)

This is how it looks now in a PR with failing CI.
