### ISSUE TITLE
Consider using GitHub Actions for CI

### ISSUE THREAD

**Issue by rail** [cockroachdb/cockroach-operator#363]
Pros:
* Better visibility (no TeamCity access required to see the logs)
* Self serve
* CI configs are versioned and don't need to be synced with the code changes

Cons:
* We may need to run some sensitive tasks (nightlies and releases) in TeamCity, so we need to support 2 CI systems

Any other thoughts?

**Comment by keith-mcclellan** [comment]
I would LOVE to move this to github actions. It will greatly help us encourage community contributions to the operator.

**Comment by keith-mcclellan** [comment]
@chrislovecnm thoughts?

**Comment by chrislovecnm** [comment]
@keith-mcclellan I have no experience with GitHub actions.  So I will let you and @rail decide.

**Comment by rail** [comment]
Thank yo. I'll merge it later today unless I hear any objections.

**Comment by rail** [comment]
I mean I will enable GitHub actions, but won't make it mandatory yet.

**Comment by rail** [comment]
Done
