### ISSUE TITLE
Remove teamcity as blocking

### ISSUE THREAD

**Issue by chrislovecnm** [cockroachdb/cockroach-operator#383]
Can we remove teamcity as blocking the builds as GitHub CI seems to run with far less flakes.

cc @keith-mcclellan

**Comment by rail** [comment]
The e2e tests are still very flaky... I wish there was a way to rerun a single action, right know you have to rerun all of them in order to green up the status.

@keith-mcclellan any objections to move forward?

**Comment by chrislovecnm** [comment]
We can break the tests into more actions. 🤷🏻‍♂️

**Comment by rail** [comment]
TeamCity is optional now. All GitHub Actions are required now. If we desire, we can make the e2e tests optional, because they are flaky.
