### ISSUE TITLE
[3/24 bug bash] additionalArgs field appears to not work

### ISSUE THREAD

**Issue by johnrk** [cockroachdb/cockroach-operator#386]
The additionalArgs field has not been tested, and it didn't work during the bug bash.

Can we investigate this?

We already have an [open docs issue](https://github.com/cockroachdb/docs/issues/9780) to document it, but it needs to be validated by engineering.

From the recent [K8s Operator bug bash on 3/24](https://docs.google.com/spreadsheets/d/1lWi5maGP5KCw7nx6U0TmHSISAz7g8BzPL6HjUQHKHxY/edit?usp=sharing), @taroface noted that:

> I tried adding the line:
> 
> additionalArgs: "--max-sql-memory=.3"
> 
> within the spec field of example.yaml
> 
> however, applying the example.yaml with kubectl apply -f didn't seem to have an effect ("crdbcluster.crdb.cockroachlabs.com/cockroachdb unchanged")
> 
> perhaps i'm not applying the syntax correctly? but has this field been tested yet?

**Comment by johnrk** [comment]
@taroface , the additionalArgs field worked for me when setting max cache size as an additional arg:
```
apiVersion: crdb.cockroachlabs.com/v1alpha1
kind: CrdbCluster
metadata:
  name: cockroachdb
spec:
  additionalArgs:
    - "--cache=.25"
```

However, I suspect that the additionalArg fields are only managed by the Operator for fields that exist in the [CRD](https://github.com/cockroachdb/cockroach-operator/blob/master/config/crd/bases/crdb.cockroachlabs.com_crdbclusters.yaml).

If that's the case, the additionalArgs field probably won't work for all [cockroach start flags](https://www.cockroachlabs.com/docs/v20.2/cockroach-start#general), such as **locality**.  

@keith-mcclellan , is this consistent with your understanding of how additionalArgs is currently working?

**Comment by taroface** [comment]
Closing this, because the syntax I used was simply incorrect (it's correct in @johnrk's example above).
