### ISSUE TITLE
Change how we handle developer defaults in the makefile and with bazel --stamp

### ISSUE THREAD

**Issue by keith-mcclellan** [cockroachdb/cockroach-operator#390]
To enable more developers to easily contribute to the development of the operator.

**Comment by chrislovecnm** [comment]
We have some concerns about how we are setting the defaults to variables in this file

https://github.com/cockroachdb/cockroach-operator/blob/7bb3c0aa60a42a76a1f355bba6220bccf87cf545/hack/build/print-workspace-status.sh#L36-L55

My vote is to move all defaults out of that file and into the Makefile.  In the Makefile, we either set defaults or force the user to set defaults.

It is easier for @alinadonisa and me to have defaults set.

We also need to access the defaults that are set for openshift, and ensure that those defaults do not cause the release process to fail.
