### ISSUE TITLE
Document Build process with Big Sur

### ISSUE THREAD

**Issue by chrislovecnm** [cockroachdb/cockroach-operator#393]
Please push a PR with the Big Sur build process.

**Comment by johnrk** [comment]
I created this PR: https://github.com/cockroachdb/cockroach-operator/pull/392/files#diff-3722d9ba8feb2d3feac8ce71a209a638d4b404e1c53f937188761181594023e2

**Comment by chrislovecnm** [comment]
This is fixed via updating go_rules
