### ISSUE TITLE
John and Keith Need Access to "openshift-sandbox"

### ISSUE THREAD

**Issue by johnrk** [cockroachdb/cockroach-operator#397]
@keith-mcclellan and @johnrk need access to "openshift-sandbox" 

**Repro Steps**
I'm trying to create an OpenShift cluster for testing by following the instructions in [OpenshiftGCP.md](https://github.com/cockroachdb/cockroach-operator/blob/master/OpenshiftGCP.md#create-an-openshift-cluster-on-gcp)

When running this command: `gcloud projects add-iam-policy-binding openshift-sandbox --member  "serviceAccount:open-shift-sa@openshift-sandbox-id.iam.gserviceaccount.com" --role "roles/owner"`

I'm receiving this error:
`ERROR: (gcloud.projects.add-iam-policy-binding) User [john@cockroachlabs.com] does not have permission to access projects instance [openshift-sandbox:getIamPolicy] (or it may not exist): The caller does not have permission`

**Comment by alinadonisa** [comment]
@johnrk , @keith-mcclellan  I gave you the permissions. Please check

**Comment by johnrk** [comment]
@alinadonisa , I received an invite from you to have "Owner" role of openshift-sandbox:

> alina@lionkube.com has granted you the following roles for project openshift-sandbox (openshift-sandbox-292620)
> 
> Owner
> Go to the Google Cloud Console to get started.
> 

And I accepted it by going to the Google Cloud Console.

However, I'm still receiving the same error, when following the instructions in [OpenshiftGCP.md](https://github.com/cockroachdb/cockroach-operator/blob/master/OpenshiftGCP.md#create-an-openshift-cluster-on-gcp)

```
Johns-MBP:~ johnkendall$ gcloud projects add-iam-policy-binding openshift-sandbox --member  "serviceAccount:open-shift-sa@openshift-sandbox-id.iam.gserviceaccount.com" --role "roles/owner"
ERROR: (gcloud.projects.add-iam-policy-binding) User [john@cockroachlabs.com] does not have permission to access projects instance [openshift-sandbox:getIamPolicy] (or it may not exist): The caller does not have permission
Johns-MBP:~ johnkendall$ 
```

Is there a cleanup that I should be doing for this role to go into effect?

**Comment by johnrk** [comment]
@alinadonisa , I'm following up on this.

**Comment by alinadonisa** [comment]
@johnrk  the service account already exist, it was created by me...this is the setup for a brand new project in GCP at first run.

**Comment by johnrk** [comment]
@alinadonisa , as we discussed on slack, I've attempted step 7 (after doing the `gcloud auth application-default login` command)

And I'm receiving the following error:

```
Johns-MBP:~ johnkendall$ gcloud iam service-accounts keys create ~/.gsp/osServiceAccount.json --iam-account open-shift-sa@openshift-sandbox-id.iam.gserviceaccount.com
ERROR: (gcloud.iam.service-accounts.keys.create) NOT_FOUND: Not found; Gaia id not found for email open-shift-sa@openshift-sandbox-id.iam.gserviceaccount.com
```

**Comment by chrislovecnm** [comment]
@johnrk - @alinadonisa is working on getting the demo done, so this is going too need to wait

**Comment by alinadonisa** [comment]
@johnrk  please close this
