### ISSUE TITLE
Fix "free of Important vulnerabilities" test for Red Hat Marketplace Listing

### ISSUE THREAD

**Issue by johnrk** [cockroachdb/cockroach-operator#399]
According to Red Hat, to fix "free of Important vulnerabilities" test for Red Hat Marketplace Listing, we need to update one of the Red Hat supplied packages in the base image for our container because one of them has a vulnerability in it.

--

Red Hat:

> The the test "free of Important vulnerabilities" - the results for this recently-added test are not presently brought forward to the test results page.
> 
> This means that one of the Red Hat supplied packages in the base image for your container now has a vulnerability that is marked Important. There is an update available to fix that vulnerability.
> 
> From our container policy documentation:
> 
> 5. Red Hat components in the container image cannot contain any critical or important vulnerabilities, as defined at https://access.redhat.com/security/updates/classification
> 
> Test name: free_of_critical_vulnerabilities
> Why? These vulnerabilities introduce risk to your customers
> How? The certification report will indicate if such vulnerabilities are present in your image. It is recommended to use the most recent version of a layer or package, and to update your image content using the following command:
> 
> yum -y update-minimal --security --sec-severity=Important --sec-severity=Critical
> 
> 
> Add a command to run that line above to your Dockerfile before any lines that you may have that clear Yum or DNF caches and rescan your image.Let us know if it stills shows as failed.
> 
> on ubi minimal where there is no yum,you need to add below command.
> 
> RUN microdnf install yum RUN yum -y update-minimal --security --sec-severity=Important --sec-severity=Critical
> 
> RUN microdnf remove yum && microdnf clean all

**Comment by johnrk** [comment]
@chrislovecnm : we need to maintain our own Red Hat UBI image and bazel can build off of that.

**Comment by chrislovecnm** [comment]
Hopefully https://github.com/cockroachdb/cockroach-operator/pull/400 will fix this issue.

**Comment by alinadonisa** [comment]
@johnrk , @keith-mcclellan I think we can close this and open another issue about how to  maintain the latest version of the ubi image with bazel. Now @rail made a temporary fix by running : bazel clean --expunge each time an image is released.
