### ISSUE TITLE
 RestartType api field  should be an annotation added to the CR

### ISSUE THREAD

**Issue by alinadonisa** [cockroachdb/cockroach-operator#405]
RestartType as api field can be triggered once as api fieled. We need to change it to annotation for easier usage and delete the annotation after the restart finishes.

**Comment by alinadonisa** [comment]
@chrislovecnm , @keith-mcclellan  what do you think?

**Comment by keith-mcclellan** [comment]
I think this makes sense please proceed

**Comment by chrislovecnm** [comment]
Yes
