### ISSUE TITLE
Document manual certificate rotation

### ISSUE THREAD

**Issue by alinadonisa** [cockroachdb/cockroach-operator#413]
Create documentation for the manual replacement of the node cert and ca certificate. 

This document should describe:
1. Node certificate manual replacement:
- how the user can see the expiration date of the node certificate checking the  annotation "crdb.io/certexpiration"  from the cr;
- how to generate a new certificate, by doing exec on a pod;
- how to replace the secret with the new cert
- how to restart the cluster by using annotation:
```
kubectl annotate crdb mycr crdb.io/restarttype='rolling'
```
2. CA certificate manual replacement
- how to generate a new certificate, by doing exec on a pod; 
- how to replace the secret with the new cert
- how to restart the cluster by using annotation:
```
kubectl annotate crdb mycr crdb.io/restarttype='fullcluster'
```

**Comment by taroface** [comment]
@alinadonisa, thanks for filing. Can you please add a description for this issue? Links to a relevant Operator issue and CRD would also be helpful.

**Comment by alinadonisa** [comment]
> @alinadonisa, thanks for filing. Can you please add a description for this issue? Links to a relevant Operator issue and CRD would also be helpful.
@taroface  I hope this helps.

**Comment by taroface** [comment]
Very helpful, thank you!

**Comment by pornpoi** [comment]
I'm waiting for these
