### ISSUE TITLE
Not cleaning up PVCs

### ISSUE THREAD

**Issue by chrislovecnm** [cockroachdb/cockroach-operator#42]
When we delete a database we do not seem to delete the PVCs correctly

```
# you need a bad storage class name or request over quota in the example
# this step has to fail
./hack/apply-apply-crdb-example.sh -c test
# then delete
./hack/apply-delete-crdb-example.sh -c test
```

You can then see the hanging PVC

```
$ k get pvc
NAME             STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS   AGE
datadir-crdb-0   Pending                                      crdb-io1       3m43s
```

**Comment by chrislovecnm** [comment]
We are not cleaning up PVCs at all.  The question is what policy do we want to use for cleanup?

**Comment by chrislovecnm** [comment]
@johnrk the operator is not deleting volumes that are attached to the database Pods when it deletes the database.  This is actually a feature of Kubernetes where you have to delete by hand the storage volumes when you delete a stateful set.  There reasoning is that you do not delete the storage automatically, because you might delete data.  I need to know if we want the default k8s behavior or another behavior.

**Comment by johnrk** [comment]
@chrisseto , do you know what behavior we want here?

**Comment by chrislovecnm** [comment]
@johnrk we talked about this on standup. Did we make a decision?

**Comment by chrislovecnm** [comment]
We need to document this as part of the operator.  PVs will not be deleted by the operator.

**Comment by johnrk** [comment]
> We need to document this as part of the operator. PVs will not be deleted by the operator.

^ cc @taroface
