### ISSUE TITLE
RELATED_IMAGE in operator.yaml

### ISSUE THREAD

**Issue by keith-mcclellan** [cockroachdb/cockroach-operator#421]
Before our GA release, we need to start including links to all supported version of the DB in the operator.yaml and clusterserviceversion.yaml files, not just the latest. 

from: https://github.com/cockroachdb/cockroach-operator/blob/master/manifests/operator.yaml

current: 

```
            - name: RELATED_IMAGE_COCKROACH_v20_2_7
              value: cockroachdb/cockroach:v20.2.7
            - name: RELATED_IMAGE_COCKROACH_v20_1_12
              value: cockroachdb/cockroach:v20.1.12
            - name: RELATED_IMAGE_COCKROACH_v19_2_12
              value: cockroachdb/cockroach:v19.2.12
```
Should be

```
            - name: RELATED_IMAGE_COCKROACH_v20_2_7
              value: cockroachdb/cockroach:v20.2.7
            - name: RELATED_IMAGE_COCKROACH_v20_2_6
              value: cockroachdb/cockroach:v20.2.6
            - name: RELATED_IMAGE_COCKROACH_v20_2_5
              value: cockroachdb/cockroach:v20.2.5
...
            - name: RELATED_IMAGE_COCKROACH_v20_1_12
              value: cockroachdb/cockroach:v20.1.12
            - name: RELATED_IMAGE_COCKROACH_v20_1_12
              value: cockroachdb/cockroach:v20.1.11
...
            - name: RELATED_IMAGE_COCKROACH_v19_2_12
              value: cockroachdb/cockroach:v19.2.12
            - name: RELATED_IMAGE_COCKROACH_v19_2_12
              value: cockroachdb/cockroach:v19.2.11
            - name: RELATED_IMAGE_COCKROACH_v19_2_12
              value: cockroachdb/cockroach:v19.2.10
...
```

Only ones we shouldn't be including are releases that were pulled due to a tech advisory.  Otherwise, the cockroachVersion API won't work.

**Comment by rail** [comment]
How do we make that list of supported versions?

It sounds like there is a minimum version that is supported. How about the maximum version?

Random ideas/questions:
* We can probably generate a list of all version by listing the dockerhub repository or some other source of truth
* Do we care about the docker images published to RedHat Connect?
* What happens if a new version of crdb released and it's still no in this list? Do we release another version of the operator or should we use some kind of globging in the checks?

**Comment by keith-mcclellan** [comment]
1) for the red hat releases, we should use the red hat registry for the source of truth instead of docker hub.  Now that we're formally releasing to both channels that should be the same going forward, but historically maybe not
2) If we don't add the release to this list, it won't be supported by the cockroachDBVersion api so they won't be able to select it.  Once nightly tests are running we should make sure we have a test that signals if we have an incompatibility so we don't publish.  

@chrislovecnm thoughts?

**Comment by rail** [comment]
Maybe we should add a GitHub Action to check for new images and create PRs in case there is a change?

**Comment by keith-mcclellan** [comment]
I like that idea @rail

**Comment by rail** [comment]
Not sure I can work on this anytime soon, back to the pool.

**Comment by keith-mcclellan** [comment]
we're going to have to do something manually for the next release then - lets discuss Monday please :-)

**Comment by rail** [comment]
I added manual steps in the [release docs](https://cockroachlabs.atlassian.net/wiki/spaces/KO/pages/1753841712/Cockroach+Operator+Release+Process) until we figure out how to automate this.

**Comment by keith-mcclellan** [comment]
thanks @rail can I close?
