### ISSUE TITLE
Version Checker Job Seemed to Fail during Major Version Upgrade (20.2.7->21.1.0)

### ISSUE THREAD

**Issue by johnrk** [cockroachdb/cockroach-operator#425]
Repro Steps:
1. With the latest version of the Operator (`image: cockroachdb/cockroach-operator:v1.7.1`), ran `kubectl apply -f manifest/operator.yaml`
2. ran `kubectl apply -f examples/example.yaml`
3. Modified example.yaml to have one major version higher of cockroachdb:
```
-    name: cockroachdb/cockroach:v20.2.7
+    name: cockroachdb/cockroach:v21.1.0
```
4. ran `kubectl apply -f examples/example.yaml`
5. to follow rolling upgrade, ran `kubectl get pods -w`

Expected results: no error, cockroachdb cluster with v21.1.0
Actual Result: I received the following error from the version checker job (see screenshot):
<img width="1082" alt="Screen Shot 2021-04-20 at 10 11 54 AM" src="https://user-images.githubusercontent.com/1663752/115411636-a2fa3a00-a1c1-11eb-8da2-2302d5ad7c65.png">

**Comment by keith-mcclellan** [comment]
https://hub.docker.com/layers/cockroachdb/cockroach-unstable/v21.1.0-beta.4/images/sha256-bbf7140e43eddaf0efde73fcbd462ade577cc5213ca8fbe1369c33f70416c948?context=explore

So replace your name with `name: cockroachdb-unstable/cockroach:v21.1.0-beta.4

**Comment by johnrk** [comment]
@keith-mcclellan , that string `name: cockroachdb-unstable/cockroach:v21.1.0-beta.4` works for me.

For the actual release, I assume that the naming with "unstable" and "beta" is temporary, and we will return to our previous version naming pattern: cockroachdb/cockroach:vxx.x.x? 

If it doesn't, and can't rely on our existing supported versions public docs ([Release Support Policy](https://www.cockroachlabs.com/docs/releases/release-support-policy.html)), we should publish a list of supported image names for the Operator. cc @taroface

**Comment by keith-mcclellan** [comment]
Yes this is specific to how we release beta and RCs of cockroachdb, we are testing this to make sure the upgrade supports 21.1 but the actual supported version will be v21.1.0 and will be in the cockroachdb/cockroach channel on docker

**Comment by alinadonisa** [comment]
@johnrk  I think this should be closed
