### ISSUE TITLE
Operator on OpenShift Challenges

### ISSUE THREAD

**Issue by johnrk** [cockroachdb/cockroach-operator#428]
The Operator installation instructions are not working for me. I explored [gcp-install.md](https://github.com/cockroachdb/cockroach-operator/blob/master/docs/openshift/gcp-install.md) and [openshift-dev.md](https://github.com/cockroachdb/cockroach-operator/blob/master/docs/openshift/openshift-dev.md).

I assume the [gcp-install.md](https://github.com/cockroachdb/cockroach-operator/blob/master/docs/openshift/gcp-install.md) are the instructions that we are supposed to be using. Is that correct?

In the other file ([openshift-dev.md](https://github.com/cockroachdb/cockroach-operator/blob/master/docs/openshift/openshift-dev.md)), it instructs one to navigate to the OpenShift web console. Does that require a subscription.

In previous conversations, we talke about OpenShift having two listings:

- [Red Hat marketplace listing that requires a subscription](https://marketplace.redhat.com/en-us/products/cockroachdb-operator)
- [Red Hat Ecosystem Catalog listing](https://catalog.redhat.com/software/operators/detail/5e9872712989e6a90307acd6)

**Questions:**
- Are we still supporting both of these?
- Have we been developing/testing on both of these types of listings?
- With the Ecosystem Catalog Listing, how are we expecting users to access the OpenShift Web Console?

**Repro steps for gcp-install.md**
1. The [Execution creation step](https://github.com/cockroachdb/cockroach-operator/blob/master/docs/openshift/gcp-install.md#execute-the-creation-script) was unclear. I didn't have a DNS domain, so I attempted to create one. What is that for?
2. I ran this command `./openshift-gcp-create.sh -p cockroach-john-277713 -s pull-secret.txt -z cockroachjohn.com. -n cockroachjohn -r us-east1` and received the following error:

```
ERROR Attempted to gather ClusterOperator status after installation failure: listing ClusterOperator objects: Get "https://api.cockroachjohn-openshift.cockroachjohn.com:6443/apis/config.openshift.io/v1/clusteroperators": dial tcp: lookup api.cockroachjohn-openshift.cockroachjohn.com on 192.168.1.1:53: no such host 
DEBUG Fetching Bootstrap SSH Key Pair...           
DEBUG Loading Bootstrap SSH Key Pair...            
DEBUG Using Bootstrap SSH Key Pair loaded from state file 
DEBUG Reusing previously-fetched Bootstrap SSH Key Pair 
DEBUG Fetching Install Config...                   
DEBUG Loading Install Config...                    
DEBUG   Loading SSH Key...                         
DEBUG   Loading Base Domain...                     
DEBUG     Loading Platform...                      
DEBUG   Loading Cluster Name...                    
DEBUG     Loading Base Domain...                   
DEBUG     Loading Platform...                      
DEBUG   Loading Networking...                      
DEBUG     Loading Platform...                      
DEBUG   Loading Pull Secret...                     
DEBUG   Loading Platform...                        
DEBUG Using Install Config loaded from state file  
DEBUG Reusing previously-fetched Install Config    
INFO Pulling debug logs from the bootstrap machine 
DEBUG Using SSH_AUTH_SOCK /private/tmp/com.apple.launchd.gvpQGE0eN7/Listeners to connect to an existing agent 
ERROR Attempted to gather debug logs after installation failure: failed to create SSH client: failed to use pre-existing agent, make sure the appropriate keys exist in the agent for authentication: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain 
FATAL Bootstrap failed to complete: failed waiting for Kubernetes API: Get "https://api.cockroachjohn-openshift.cockroachjohn.com:6443/version?timeout=32s": dial tcp: lookup api.cockroachjohn-openshift.cockroachjohn.com on 192.168.1.1:53: no such host 
Johns-MacBook-Pro:gcp-openshift johnkendall$ 
```

**Comment by johnrk** [comment]
@chrislovecnm will share a command on Slack to get this working.

**Comment by johnrk** [comment]
Hey @keith-mcclellan , I'm following up on this

**Comment by johnrk** [comment]
The Operator doesn't work with the CLI install instructions. And we need to use the GUI.

**Comment by johnrk** [comment]
@keith-mcclellan : the marketplace listing and catalog listing are functionally equivalent.

**Comment by johnrk** [comment]
@keith-mcclellan : don't use the 1.0.1 version because it's old, and we should, in general, use the beta channel.

**Comment by johnrk** [comment]
Now, I'm having issues accessing the web console.

**Comment by johnrk** [comment]
The web console appears to be working for me!

Navigating to find the web console was not intuitive. It will be worth documenting in detail the steps to get it: [Accessing the Web Console](https://docs.openshift.com/container-platform/4.7/web_console/web-console.html) cc @taroface

**Comment by johnrk** [comment]
It appears that the Operator (v 1.7.3) failed to create a cluster for me. @keith-mcclellan , any thoughts on troubleshooting this?

The events page has nothing.

Here's a screenshot of the Cluster status communicating that it's in a failed state:
<img width="1567" alt="Screen Shot 2021-04-22 at 11 46 17 AM" src="https://user-images.githubusercontent.com/1663752/115744419-8d6f4680-a360-11eb-95b1-67f693e7ec24.png">

**Comment by keith-mcclellan** [comment]
did you set cockroachDBVersion in the example? If not it won't know which version to launch.

**Comment by keith-mcclellan** [comment]
I just tested this myself and it worked in my dev env btw
