### ISSUE TITLE
Operator on OpenShift lacks default CockroachDBVersion value

### ISSUE THREAD

**Issue by johnrk** [cockroachdb/cockroach-operator#435]
When creating a CockroachDB Cluster on OpenShfit, the cockraochDBVersion field is listed as "optional" (see screenshot). 

However, the Operator does not treat that field as optional. If you attempt to create a cluster without that field specified, the cluster will enter a "Failed" state (see screenshot).

To address this, we can either make the field required or provide a default value for the CockroachDBVersion field.

<img width="1912" alt="Screen Shot 2021-04-22 at 2 28 54 PM" src="https://user-images.githubusercontent.com/1663752/115767451-2c9f3880-a377-11eb-8937-8455d1f551a5.png">
<img width="1567" alt="Screen Shot 2021-04-22 at 11 46 17 AM" src="https://user-images.githubusercontent.com/1663752/115767461-2e68fc00-a377-11eb-9b55-d55e6610a3b5.png">

**Comment by keith-mcclellan** [comment]
@rail @alinadonisa for the CSV, we need to add (and update) spec.cockroachDBVersion in the alm-example to fix this.  Is this easier to fix in the build process or the release process? Thanks!

**Comment by rail** [comment]
IMO the release process should use files already committed in the repository. Otherwise we would need create release branches in order to commit the changes back.

**Comment by alinadonisa** [comment]
@keith-mcclellan  if you add this field in [config/samples/crdb-tls-example.yaml](https://raw.githubusercontent.com/cockroachdb/cockroach-operator/master/config/samples/crdb-tls-example.yaml) this will be added in automatic when you regenerate the csv
@johnrk  the validation will be done after release when we will implement web hooks validations

**Comment by keith-mcclellan** [comment]
opened https://github.com/cockroachdb/cockroach-operator/pull/438 to make the initial change.  @rail please add keeping this up to date part of the release process!

**Comment by rail** [comment]
https://github.com/cockroachdb/cockroach-operator/pull/438 should fix it
