### ISSUE TITLE
Error: ~/install-config.yaml: No such file or directory

### ISSUE THREAD

**Issue by johnrk** [cockroachdb/cockroach-operator#439]
In the gcp-install.md instructions, executing the [Execute the creation script](https://github.com/cockroachdb/cockroach-operator/blob/master/docs/openshift/gcp-install.md#execute-the-creation-script) step is failing for me.

**Repro steps:**

- Follow all of the steps for [Create OpenShift Cluster on GCP](https://github.com/cockroachdb/cockroach-operator/blob/master/docs/openshift/gcp-install.md#create-an-openshift-cluster-on-gcp)

**Expected Results:**

- OpenShift cluster is created. One can use the oc whoami --show-console command to access the OpenShift Web Console.

**Actual Results**

- During the [Execute the creation script](https://github.com/cockroachdb/cockroach-operator/blob/master/docs/openshift/gcp-install.md#execute-the-creation-script) step, I receive the following message:
created key <key> of type [json] as [/Users/johnkendall/.gcp/osServiceAccount.json] for <service account name and path>
./openshift-gcp-create.sh: line 133: /Users/johnkendall/openshift-acceptancetest3/install-config.yaml: No such file or directory

Based on [OpenShift docs](https://docs.openshift.com/container-platform/4.6/installing/installing_bare_metal_ipi/ipi-install-installation-workflow.html#configuring-the-install-config-file_ipi-install-configuration-files), it appears install-config.yaml is a config file that OpenShift provides and we configure.

**Comment by chrislovecnm** [comment]
Closing
