### ISSUE TITLE
Operator on OpenShift: Minor Version Upgrades (v20.2.7->v20.2.8) Are Not Working

### ISSUE THREAD

**Issue by johnrk** [cockroachdb/cockroach-operator#441]
My attempt to do a minor version upgrade from v20.2.7 to v20.2.8 failed with the Operator on OpenShift. According to @rail , [this page](https://catalog.redhat.com/software/containers/cockroachdb/cockroach/596691854b339a3561489ac2?container-tabs=packages&tag=all) details the supported versions of CockroachDB with the Operator on OpenShift. v20.2.7 and v20.2.8 are listed as supported versions.

**Repro Steps:**
After installing Operator,
1. On "Details" tab/window in the OpenShift Web Console, select "Create instance." Alternatively, on the "CockroachDB Operator" tab, one can click "Create CockroachDB Cluster"
2. In the "Create CrdbCluster" Window, enter 5 nodes and specify "v20.2.7"
3. At the bottom of the page, click "Create" 
4. While in the "Installed Operators" section under "Operators," and in the "CockroachDB" Operator Tab, click on the three dots to select "Edit CrdbCluster"
5. In the "Edit CrdbCluster" window modify "cockroachDBVersion" field with "v20.2.8" and click "Save."

**Expected Results:**

- In the web console, I expected to see the pods do a rolling upgrade to v20.2.8. As discussed in this open issue, the "Pods" page is empty.
- In addition, I expected to see the pods do a rolling upgrade when running `oc get pods -w`
- Lastly, I expected to see the whole CrdbCluster change to v20.2.8 when checking `oc describe CrdbCluster crdb-tls-example-1`

**Actual Results:**

- I received a message that stated `crdb version v20.2.8 not supported` (see screenshot below)
- In addition the OpenShift web console states that the OperatorStatus is in a "Failed" state (see screeenshot below)
 
<img width="1341" alt="Screen Shot 2021-04-26 at 2 54 25 PM" src="https://user-images.githubusercontent.com/1663752/116136758-bbc28e00-a6a0-11eb-86a5-4d962f252415.png">
<img width="1918" alt="Screen Shot 2021-04-26 at 3 11 18 PM" src="https://user-images.githubusercontent.com/1663752/116137589-bd408600-a6a1-11eb-844a-8cbc3f9633c2.png">

**Comment by rail** [comment]
Can you verify if it's fixed by the operator 1.7.4 release please

**Comment by keith-mcclellan** [comment]
I'm running into a problem here too actually - I just tried this with 1.7.4 on a cluster I upgraded from 1.7.3.  I updated the cockroachDBVersion API field - the version checker runs successfully, but when actually rolling the pods I get the following:

`Failed to apply default image tag "cockroachdb/cockroach@sha256:v20.2.8": couldn't parse image reference "cockroachdb/cockroach@sha256:v20.2.8": invalid reference format`

@alinadonisa @chrislovecnm any idea what's going on here?
