### ISSUE TITLE
Enable OpenShift nightly Builds

### ISSUE THREAD

**Issue by chrislovecnm** [cockroachdb/cockroach-operator#444]
Once we have OpenShift e2e running we need to run nightly builds

We will need a service account that has the following roles https://github.com/cockroachdb/cockroach-operator/pull/422/files#diff-26c0f875002514111ada6e9108cbaa62833ebefaa9928beabb55ef991a828816R152

1. Project name: `cockroach-operator-nightlies`
2. Service account: `openshift-nightly@cockroach-operator-nightlies.iam.gserviceaccount.com`
3. Roles assigned:
```
	"compute.admin",
	"dns.admin",
	"iam.securityAdmin",
	"iam.serviceAccountAdmin",
	"iam.serviceAccountUser",
	"iam.serviceAccountKeyAdmin",
	"storage.admin",
	"servicemanagement.quotaViewer",
```
We also need to register a top level domain in order to run these tests.

**Comment by rail** [comment]
Moving to the triage queue.

**Comment by chrislovecnm** [comment]
@rail we are ready for this

**Comment by rail** [comment]
@chrislovecnm may I ask you to add a Makefile target for this task.

**Comment by chrislovecnm** [comment]
@rail target is added

**Comment by udnay** [comment]
There's a way to do it with DNS peering I think but that'll get too confusing I think. We could just buy a domain. `crl-operator.io` and then do something like `nightly.crl-operator.io` for openshift testing, thoughts?

**Comment by chrislovecnm** [comment]
Can we just use the same project?

**Comment by rail** [comment]
I've heard somewhere that it has to be a top level domain. Is this true?

**Comment by udnay** [comment]
> Can we just use the same project?

Yes, I was hoping to have. everything under the same `cockroach-operator-nightlies` but using the `openshift-sandbox` is fine, you're right.

**Comment by rail** [comment]
FTR, this is the current roles of the service account:
```
$ gcloud projects get-iam-policy cockroach-operator-nightlies \
  --flatten="bindings[].members" \
  --format='table(bindings.role)' \
  --filter="bindings.members:openshift-nightly@cockroach-operator-nightlies.iam.gserviceaccount.com"
ROLE
roles/compute.admin
roles/dns.admin
roles/iam.securityAdmin
roles/iam.serviceAccountAdmin
roles/iam.serviceAccountKeyAdmin
roles/iam.serviceAccountUser
roles/servicemanagement.quotaViewer
roles/storage.admin
```

**Comment by rail** [comment]
> I've heard somewhere that it has to be a top level domain. Is this true?

Not true according to https://github.com/openshift/installer/blob/master/docs/user/gcp/dns.md, we can use a subdomain.

**Comment by rail** [comment]
I will also enable some services per https://github.com/openshift/installer/blob/master/docs/user/gcp/apis.md

**Comment by rail** [comment]
Looks like https://github.com/cockroachdb/cockroach-operator/blob/236a1080d28221767d2ea82e0bce412a2b4f8f4d/e2e/kubetest2-openshift/deployer/up.go#L70 is something we should skip for CI - the service account doesn't have permissions to enable/disable APIs.

**Comment by chrislovecnm** [comment]
@rail see https://github.com/cockroachdb/cockroach-operator/pull/651

**Comment by rail** [comment]
This is done now. https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_CockroachOperator_Nightlies_OpenShiftNightly?mode=builds is the TeamCity URL and it will report to slack if the builds fail.
