### ISSUE TITLE
Figure out how to reference operator.yaml from docs

### ISSUE THREAD

**Issue by rail** [cockroachdb/cockroach-operator#450]
Right now [the docs](https://www.cockroachlabs.com/docs/v20.2/orchestrate-a-local-cluster-with-kubernetes.html#install-the-operator) point to [operator.yaml](https://raw.githubusercontent.com/cockroachdb/cockroach-operator/master/manifests/operator.yaml) using the `master` branch.
 
This file may reference unstable operator version what may be not ideal for end users.

There are several options that we can use to "pin" `operator.yaml`:

1) The docs should reference `operator.yaml` using stable links (sha or tag). This may be not that convenient for the docs team - the docs have to be updated with every operator release (every 2 weeks?). On the other hand it will keep the instructions reproducible.

2) Use 2 different `operator.yaml` files for dev and released versions.  This will require an extra step in the release process.

3) Publish `operator.yaml` somewhere else (GCS, S3) as a part of release process.

Anything else?

@jlinder: is there a canonical approach, maybe something that we already use in the crdb release process?

**Comment by chrislovecnm** [comment]
We already are tagging the releases.  In the documentation use the tagged URL.  For instance
https://github.com/cockroachdb/cockroach-operator/blob/v1.7.5/manifests/operator.yaml

**Comment by jlinder** [comment]
I am not aware of a canonical approach at CRL for this. For CRDB, we publish specifically tagged / versioned assets and, as far as I know, don't reference anything in the cockroach repo from the docs. I don't have a strong opinion on which one to follow. 

Updating the docs every release may not be bad (updating them could be automated; we can help docs learn how to do that if they don't already know).

@taroface , do you have any input from the docs team's perspective?

**Comment by johnrk** [comment]
@jlinder , what if we started off with the updating docs every release for now? 

We can incorporate automation over time.

**Comment by jlinder** [comment]
@johnrk, Ah! By automation, I meant using some some `sed` commands (or a similar search and replace functionality) that can be run against the documentation files to change all specifically referenced locations. That is something the doc writer would run against the files manually but it automates the updating of the files.

**Comment by johnrk** [comment]
@jlinder , ok great! Do you have an existing example of this for our current docs infrastructure that we could reuse?

**Comment by taroface** [comment]
@jlinder We do currently reference the `cockroach` repo in several places in our docs, using `remote_include` syntax. Examples:

Builtins: https://github.com/cockroachdb/docs/blob/b2a2f720057a4fff5cf1f2513c4a20c80537289f/v21.1/functions-and-operators.md

Cluster settings: https://github.com/cockroachdb/docs/blob/b2a2f720057a4fff5cf1f2513c4a20c80537289f/v21.1/cluster-settings.md

I was thinking it would be ideal to use `remote_include` to reference the "latest" Operator manifests:

- https://raw.githubusercontent.com/cockroachdb/cockroach-operator/master/manifests/operator.yaml
- https://github.com/cockroachdb/cockroach-operator/blob/master/examples/example.yaml (unless we don't plan to version this, cc @rail)
- https://github.com/cockroachdb/cockroach-operator/blob/master/config/crd/bases/crdb.cockroachlabs.com_crdbclusters.yaml (ditto)

**Comment by taroface** [comment]
@jlinder @rail If `remote_include` will work for this, what should our next steps be?

**Comment by rail** [comment]
TBH, I'm not quite sure how `remote_include` would help here. You still need to reference a remote URL which can be either stable (with tag or sha in it) or pointing to "latest". My fear that using "latest" would just hide the issue of non deterministic content and will hit us in another way.

**Comment by jlinder** [comment]
Ah. I misread how `remote_include` works. The way I initially thought it worked is: 

- Files exist in the docs repo containing only the link/text/code for the link to each of the yaml files for a specific operator version
- All the places in the documentation that would show that link have an include (not sure of the name in the templating language being used) that imports the link/text/code from that file

If you need to include the text of the yaml files directly in the documentation pages, a possible scenario could be:

- Make a file for each of the yaml files for a specific operator version that `remote_include`s the file
- Everywhere the text for one of the yaml files needs to be included, "include" the file that `remote_include`s the yaml file

This way there is only one file that needs to be edited when a new operator version comes out and everywhere the text is actually displayed will be automatically updated when the site is built.

Does that help?

**Comment by taroface** [comment]
cc @udnay

**Comment by udnay** [comment]
Can we use `latest` tag like in docker so that whenever we cut a release we move `latest` something like.
```
git tag -d latest
git tag latest v1.7.12
```
Then we could reference https://github.com/cockroachdb/cockroach-operator/blob/latest/manifests/operator.yaml and always pull an up to date stable version.

**Comment by rail** [comment]
I have vague memories of "never push the same tag", but maybe I'm wrong. We can try this approach.

**Comment by pseudomuto** [comment]
Resolved via https://github.com/cockroachdb/docs/pull/11763. There's a site variable in the docs that references a specific tag. After releasing a new version we can open a one line PR to bump the version.

If we end up releasing often enough, we can look into more automated options
