### ISSUE TITLE
Two Version Checker Jobs Are Running | GKE

### ISSUE THREAD

**Issue by johnrk** [cockroachdb/cockroach-operator#459]
When I attempted to do a minor upgrade (v20.2.7->v20.2.8), there appear to be two version checker jobs running. Is that expected?

Screenshot:
<img width="1276" alt="Screen Shot 2021-04-28 at 3 59 27 PM" src="https://user-images.githubusercontent.com/1663752/116465195-e8121200-a83a-11eb-9a1f-75d8e4798fd7.png">

**Comment by keith-mcclellan** [comment]
I think this is part of what @alinadonisa was talking about yesterday, adding the init job has messed up some of the timings.  Things work, but not quite like they should.

**Comment by chrislovecnm** [comment]
@keith-mcclellan there should be two jobs.  

1. when you create the db
2. when you update the db

So I think this is as expected.

**Comment by alinadonisa** [comment]
@johnrk the 5th node when did you added? Did you created earlier, and after that did the upgrade? Please describe the complete scenario. The first version checker that is terminating, was triggered almost 4 minutes prior to the moment you did the print screen. You triggered the creation of the 5th node probably, and after that did the upgrade?

**Comment by johnrk** [comment]
@alinadonisa , I do not recall the exact sequence of events. Before attempting this upgrade, I believe that I had scaled from 3 to 5 nodes or deployed with 5 nodes on 20.2.7 and then performed an upgrade.

If this is insufficient information, we can delete this bug.

**Comment by alinadonisa** [comment]
@johnrk  I think we can delete this bug

**Comment by keith-mcclellan** [comment]
closing, will reopen if this reoccurs
