### ISSUE TITLE
Use k3s for CI on PRs and GKE for CI on Tags

### ISSUE THREAD

**Issue by chrislovecnm** [cockroachdb/cockroach-operator#46]
When we do a PR, using k3s is a great idea.
When we release a tag I recommend doing full platform testing, including GKE.

**Comment by johnrk** [comment]
@chrislovecnm , What is k3? Is it the lightweight version of Kubernetes "k3s"?

**Comment by chrislovecnm** [comment]
@johnrk sorry I typo'ed it.  cockroachdb uses https://github.com/rancher/k3s for some testing.  And the project uses some of it now, but I am still coming up to speed.

**Comment by chrislovecnm** [comment]
We may have some of this already in the project.  I am still figuring out all of the testing.

**Comment by chrislovecnm** [comment]
cc @jlinder you can track this to implement in the other place you need to.

**Comment by udnay** [comment]
This can be closed, we do CI using kind on all PRs plus nightly on GKE as well
