### ISSUE TITLE
Deleting CSR docs

### ISSUE THREAD

**Issue by timveil** [cockroachdb/cockroach-operator#467]
The docs here don't make much sense for GKE/Operator

https://www.cockroachlabs.com/docs/v20.2/orchestrate-cockroachdb-with-kubernetes.html#stop-the-cluster

step 1 "Delete the previously created custom resource:" makes sense

step 2 "Remove the Operator:" makes sense

step 3 "Get the names of any CSRs for the cluster:" makes sense

step 4 "Delete any CSRs that you created:" is quite confusing...

its not clear from step 3 which `csr`'s i created and should delete vs ones that i didn't create and SHOULD NOT delete.  furthermore, the example command `kubectl delete csr node.cockroachdb.default.svc.cluster.local root.cockroachdb.default.svc.cluster.local ` no longer works because the listed CSR's do not exist with this install pattern (GKE/operator).

we need to clarify what if any CSR's should be deleted for this pattern.

**Comment by taroface** [comment]
Closing, as this was resolved recently with a set of K8s docs updates.
