### ISSUE TITLE
Instructions for starting GKE cluster need to include --region or --zone setting

### ISSUE THREAD

**Issue by chudro** [cockroachdb/cockroach-operator#468]
In the "Orchestrate CockroachDB in a Single Kubernetes Cluster", for hosted GKE, the cluster creation command is missing the --region or --zone setting. Here is the command in docs:

$ gcloud container clusters create cockroachdb --machine-type n1-standard-4

Here is the error message:

ERROR: (gcloud.container.clusters.create) One of [--zone, --region] must be supplied: Please specify location.

**Comment by chudro** [comment]
This also refers to the cluster delete command as well:

**Comment by chrislovecnm** [comment]
The user can their default region and zone, and then the commands do not require those flags. @taroface is this issue in the correct repo?

**Comment by taroface** [comment]
Yes, I clarified the `gcloud` install steps to recommend setting a default region/zone. Most of these issues should technically be cockroachdb/docs issues, but I'm still able to see them because they were added to the Deployments & Operations project.
