### ISSUE TITLE
Intial CI configured in Teamcity

### ISSUE THREAD

**Issue by chrislovecnm** [cockroachdb/cockroach-operator#47]
When we have a PR we need to run the following make targets

- `make docker/build/operator-ubi`
- `make docker/build/test-runner`
- `make test`
- `make lint`

**Comment by chrislovecnm** [comment]
@johnrk I'm blocked on this because of my permissions with TeamCity and GitHub.  I cannot configure this.  I believe we have a ticket in to change this, but I wanted to note this as blocked.

**Comment by chrislovecnm** [comment]
Unable to run make lint

**Comment by chrislovecnm** [comment]
@johnrk the initial CI is running.  I have issues open for the next steps. You can open a PR and now your code is tested 🥳

**Comment by johnrk** [comment]
@chrislovecnm , is this issue safe to close?

**Comment by chrislovecnm** [comment]
Yes.  I have other issues filed for more work on the CI
