### ISSUE TITLE
Statefulsets should use `Parallel` pod management

### ISSUE THREAD

**Issue by chrisseto** [cockroachdb/cockroach-operator#470]
The underlying statefulset that is created by the operator is has its pod management policy set to `OrderReady` rather than `Parallel`. We've seen that `OrderReady` can lead to cluster unavailability when all node happen to crash within a short interval.

For example, if a query can cause nodes to OOM (more comment in previous CRDB iterations) it may very well take down nodes one after the other if it's being continuously retried. In such a case, pod ordinal 0 may never mark itself as ready due to the inability to contact other CRDB nodes. When using `OrderReady` the other CRDB nodes won't be rescheduled until pods with a lower ordinal have marked themselves as ready, leading to a deadlock.

**Comment by chrislovecnm** [comment]
Can we close this @johnrk?

**Comment by chrisseto** [comment]
Closed via https://github.com/cockroachdb/cockroach-operator/commit/998fbf7f18c9f4b27ae6de1043f980739956bc5e
