### ISSUE TITLE
Future CI

### ISSUE THREAD

**Issue by chrislovecnm** [cockroachdb/cockroach-operator#48]
We need

- e2e testing
- testing to ensure that `make generate` does not produce new code
- spell check
- go fmt https://github.com/kubernetes/kops/blob/master/hack/verify-gofmt.sh
- go imports https://github.com/kubernetes/kops/blob/master/hack/verify-goimports
- go mods https://github.com/kubernetes/kops/blob/master/hack/verify-gomod.sh
- spelling https://github.com/kubernetes/kops/blob/master/hack/verify-spelling.sh
- static check https://github.com/kubernetes/kops/blob/master/hack/verify-spelling.sh

**Comment by udnay** [comment]
This is done
