### ISSUE TITLE
Publish CRDB 21.1 beta to Red Hat

### ISSUE THREAD

**Issue by johnrk** [cockroachdb/cockroach-operator#487]
At the moment, the Operator does not support using CockroachDB 21.1.x beta versions. We need to publish 21.1.x to Red Hat in order to use it.

This is important for our own internal testing and to enable external users to use 21.1.x.

**Comment by johnrk** [comment]
One of the issues around this is there no clear way to distinguish between beta and non-beta versions of images.

**Comment by johnrk** [comment]
@alinadonisa says we should follow up with @keith-mcclellan on how to manage the beta and stable channels within Red Hat.

**Comment by johnrk** [comment]
To have not tested the Operator on v21.1 and then make it generally available with 21.1 would be a significant quality risk.

**Comment by johnrk** [comment]
After yesterday's standup, we were able to find a way to test 21.1 on GKE by using the beta/unstable version that is published on DockerHub: https://hub.docker.com/r/cockroachdb/cockroach-unstable/tags?page=1&ordering=last_updated

**Comment by rail** [comment]
I'm going to close this, because we ended up not using special builds. We may consider to have a temporary repo with repackaged/rebuilt versions of alpha/betas of crdb in the future.
