### ISSUE TITLE
Minor Version Upgrades/Downgrades

### ISSUE THREAD

**Issue by johnrk** [cockroachdb/cockroach-operator#50]
As an operator, I can perform minor version upgrades via rolling restarts,
so that my application can start using a more stable version of
CockroachDB without losing availability.

Minor version upgrades do not require a finalization step.

**Comment by chrislovecnm** [comment]
@johnrk I should be able to demo this, but I think this is already in the operator.  We need more testing around this feature, but I think it already is working.  To be clear a minor version upgrade is working.

**Comment by chrislovecnm** [comment]
@vladdy https://www.cockroachlabs.com/docs/stable/upgrade-cockroach-version.html are all the steps on this page implemented

**Comment by chrislovecnm** [comment]
@johnrk this is complete.  Closing issue
