### ISSUE TITLE
unable to scale cluster

### ISSUE THREAD

**Issue by taroface** [cockroachdb/cockroach-operator#500]
When attempting to scale a cluster by changing `nodes: 3` to `nodes: 4` and applying the custom resource, the latest pod `cockroachdb-3` is stuck:

```
cockroachdb-3                         0/1     Pending   0          4m15s
```

and shows:

```
Events:
  Type     Reason            Age                  From               Message
  ----     ------            ----                 ----               -------
  Warning  FailedScheduling  65s (x6 over 5m19s)  default-scheduler  0/3 nodes are available: 3 Insufficient cpu, 3 Insufficient memory.
```

I'm using the default memory settings and `n2-standard-4` machines:

```
  resources:
    requests:
      cpu: "2"
      memory: "8Gi"
    limits:
      cpu: "2"
      memory: "8Gi"
```

This is using the Operator version currently at https://github.com/cockroachdb/cockroach-operator/blob/master/manifests/operator.yaml on GKE and CRDB v20.2.8.

**Comment by taroface** [comment]
Actually, I am seeing the same issue when starting a new cluster with `nodes: 4`. Perhaps it's an issue with my Kubernetes cluster?

**Comment by udnay** [comment]
From the above error message it looks like you’re just running out of
resources on your machine. Are you running this on your laptop or a small
cluster that can’t add nodes?

**Comment by taroface** [comment]
Yes, it turns out I just had to scale my GKE cluster first. For some reason, this wasn't an issue on the previous Operator beta, but maybe my GKE cluster was big enough and I didn't know it. Closing this!
