### ISSUE TITLE
Issue scaling down cluster from 6 to 3 nodes - OpenShift w/ Operator

### ISSUE THREAD

**Issue by jhatcher9999** [cockroachdb/cockroach-operator#504]
I installed the CRDB Operator on an OpenShift cluster (during the 5/17/21 bug bash)

I started with a 5-node cluster and scaled to 6-node using these steps:
```
oc get pods - to verify you have 5 pods

oc get crdbcluster crdb-tls-example -o yaml > crdb-tls-example.yaml

vim crdb-tls-example.yaml (edit nodes to be 6)

oc apply -f crdb-tls-example.yaml

oc get pods - to verify you have 6 pods

oc exec -it crdb-tls-example-0 -- cockroach sql --certs-dir cockroach-certs/ -e "select * from test.users;"
```

Then, I tried to scale down from 6 nodes to 3 using similar steps:
```
oc get pods - to verify you have 5 pods

oc get crdbcluster crdb-tls-example -o yaml > crdb-tls-example.yaml

vim crdb-tls-example.yaml (edit nodes to be 3)

oc apply -f crdb-tls-example.yaml

oc get pods - to verify you have 3 pods
```

The operator got rid of the last 3 nodes, but the remaining three nodes were in a non-running state (note the `0/1` below) -- and the CRDB nodes were unreachable via SQL shell or DB Console:
```
JimH-MacBook-Pro:operator_bugbash jimhatcher$ oc get pods -w
NAME                                  READY   STATUS    RESTARTS   AGE
cockroach-operator-7cd9bd6dc5-48hjw   1/1     Running   0          33m
crdb-tls-example-0                    0/1     Running   0          29m
crdb-tls-example-1                    0/1     Running   0          29m
crdb-tls-example-2                    0/1     Running   0          28m
```
If you describe the pods, they say that they've failed the readiness probe with a 503 error.

I then tried to scale back up to 5 nodes, but the operator didn't change the number of pods at all (I'm guessing because it couldn't talk to the Cockroach nodes to verify some cluster state ?? )

I also tried to delete all the pods.  Once I had deleted 

The logs from the crdb-tls-example-2 pod are attached.
[crdb-tls-example-2-logs.txt](https://github.com/cockroachdb/cockroach-operator/files/6496071/crdb-tls-example-2-logs.txt)

Going from 6 pods to 3 pods is probably not a great idea since you're probably not able to maintain a quorum of all the ranges.  But, it seems like the operator could be used to recover from that state.

**Comment by keith-mcclellan** [comment]
@chrislovecnm @udnay we need to make sure that scale down operations run safely - this is likely because a `cockroach node decommission` didn't occur.  We should discuss how we want this to work since there could be a use case where a customer may not want to decommission the nodes during a scale down too but I think that would be rare.

**Comment by keith-mcclellan** [comment]
@johnrk @udnay  Do you all consider this to be a release blocker?  We could "fix" this for the release with a docs callout @taroface fyi

**Comment by keith-mcclellan** [comment]
@taroface shared https://deploy-preview-10578--cockroachdb-docs.netlify.app/docs/v21.1/kubernetes-operation which calls out that a scale operation doesn't explicitly decommission nodes

**Comment by keith-mcclellan** [comment]
This should be working in the next release now that #514 is merged.
