### ISSUE TITLE
CockroachDB License Configuration

### ISSUE THREAD

**Issue by johnrk** [cockroachdb/cockroach-operator#51]
As an operator, I can configure CockroachDB license on a new
CockroachDB cluster in Kubernetes, so that I initialize a cluster that
meets my expected deployment needs.

Customers need to be able to apply an enterprise license that exist in [cluster settings (enterprise.license)](https://www.cockroachlabs.com/docs/stable/cluster-settings.html).

**Comment by johnrk** [comment]
@keith-mcclellan , isn't this required for our certifications?

**Comment by chrislovecnm** [comment]
@johnrk they can add the license was as an argument. Can we please test this?

**Comment by keith-mcclellan** [comment]
The only way I know of to do this would be to set an environment variable argument in the CR, which would expose the license as plain text to anyone with access to the openshift namespace.  Not sure that's what we want to recommend here.

**Comment by pseudomuto** [comment]
This has gone kind of stale, so I'm going to close it for now. Feel free to reopen if you think the operator needs to handle this.

For now, since this is a one time operation, I think people can do the following:

```
# deploy the secure client
kubectl create \
  -f https://raw.githubusercontent.com/cockroachdb/cockroach-operator/master/examples/client-secure-operator.yaml

# open db console
kubectl exec -it cockroachdb-client-secure \
  -- ./cockroach sql \
  --certs-dir=/cockroach/cockroach-certs \
  --host=cockroachdb-public

# set license details
SET CLUSTER SETTING cluster.organization = '<YOUR_ORG>';
SET CLUSTER SETTING enterprise.license = '<YOUR_LICENCE_KEY>';
```
