### ISSUE TITLE
Nodes value in the API might be a tad confusing

### ISSUE THREAD

**Issue by chrislovecnm** [cockroachdb/cockroach-operator#54]
We have the following value in the API

https://github.com/cockroachdb/cockroach-operator/blob/bbfc23a928c1c1d39f167057ac814756a1c5d00f/api/v1alpha1/cluster_types.go#L14-L15

The term Node and Nodes are also used by Kubernetes 

https://kubernetes.io/docs/concepts/architecture/nodes/

@johnrk I recommend renaming this to something like PodReplicaCount, Replicas, or something else that does not use the term Node.

I am not the best at figuring out names that make sense, but I am good at figuring out overloaded terms, and this one is overloaded.

**Comment by johnrk** [comment]
Fair point. let's discuss this during our next Standup.

**Comment by vladdy** [comment]
Just as a comment, I chosen `nodes` instead of replicas as the field name because this is how CockroachDB calls its each instance in the documents. Probably, `NodeCount` could be a compromise.

**Comment by chrislovecnm** [comment]
@vladdy I completely understand as Nodes is a common term with databases as well.

CoachroachNodes?? or CRNodes??? I do like the count.  I come from the k8s world, so whenever I talk about a DB running on top of k8s, it is fun to talk about Nodes :)

**Comment by vladdy** [comment]
Yeah, naming is one of the hardest things.

It could be `CockroachDBNodes`, but in such case assuming that we are already in the "cockroachdb domain" of the custom resource, it could be also reduced to `nodes` and although k8s has such term, I'm not convinced that it is something one would think about editing a database resource. However, `replicas` or something like that would be a new term which would be hard to find in the database documents or compare against non k8s install. 

I would recommend to run it buy a number of people and see what they think if they see such name.

**Comment by chrislovecnm** [comment]
> I would recommend to run it buy a number of people and see what they think if they see such name.

Yes run it buy some of the devops people who will use this product ;)

**Comment by chrislovecnm** [comment]
@keith-mcclellan we should think about renaming this.  Also, I think this is a duplicate

**Comment by keith-mcclellan** [comment]
whats the LOE on renaming?  "nodes" is what we call it when provisioned outside of k8s so I want to keep that but adding a prefix to make it clear isn't a bad idea.  that being said, this is a breaking change from an api perspective.

**Comment by chrislovecnm** [comment]
Replicas is the usual term. The probably is that we have k8s nodes as well

**Comment by chrislovecnm** [comment]
Closing as we are cutting a GA
