### ISSUE TITLE
[regression] installing a new cluster using the operator launches multiple vcheck jobs

### ISSUE THREAD

**Issue by keith-mcclellan** [cockroachdb/cockroach-operator#545]
I am seeing more than 1 vcheck job, even though the first job ran successfully and the crdb cluster started.  The second job does not terminate properly.  

steps to reproduce:
create a new cluster

![Screen Shot 2021-05-28 at 12 38 25 PM](https://user-images.githubusercontent.com/4730669/120015867-dfd00280-bfb1-11eb-8064-c08db3023b76.png)

[vcheck-multi-fire.log](https://github.com/cockroachdb/cockroach-operator/files/6562220/vcheck-multi-fire.log)

**Comment by alinadonisa** [comment]
@keith-mcclellan  "crdb-tls-example-vcheck-27036997" is missing from the logs

**Comment by udnay** [comment]
What's the job problem we're seeing in CI? Looking at the logs this might be another race condition. I see errors that the operator is unable to pull the DB's CR. In any case I don't think this is a release blocker, not sure how we test this though?
