### ISSUE TITLE
[Regression] Cannot upgrade cluster by updating CockroachDBVersion API field

### ISSUE THREAD

**Issue by keith-mcclellan** [cockroachdb/cockroach-operator#546]
![Screen Shot 2021-05-28 at 12 59 44 PM](https://user-images.githubusercontent.com/4730669/120018004-93d28d00-bfb4-11eb-9be5-8bd453fc0baf.png)
![Screen Shot 2021-05-28 at 1 00 10 PM](https://user-images.githubusercontent.com/4730669/120018051-a3ea6c80-bfb4-11eb-8828-a2093ec53fec.png)

Steps to recreate:
Install cockroachdb version 20.2.10 using cockroachDBVersion API field
After cluster is started and healthy, update value to v21.1.0

The weird thing is that the init container gets the right SHA, but its not getting replaced for the actual db container image.
[failed-upgrade.log](https://github.com/cockroachdb/cockroach-operator/files/6562331/failed-upgrade.log)

**Comment by chrislovecnm** [comment]
We need this in one of our e2e tests

**Comment by alinadonisa** [comment]
@keith can you show me the value from the status for field crdbcontainerimage please? Also the annotation for containerimage. This are on the CR

**Comment by chrislovecnm** [comment]
@udnay removing release-blocker, but adding label that we need testing
