### ISSUE TITLE
Consider using something other than `sed` for templating

### ISSUE THREAD

**Issue by rail** [cockroachdb/cockroach-operator#549]
Files like `hack/update-csv.sh` and `hack/update-pkg-manifest.sh` use `sed` in order to replace some values in generated YAML files.

There are some issues with this approach:

* When the `sed` expression is too long, it fails with "not terminated" error.
* We need to update the CRDB versions in multiple places.

We can create a tool that would:

* read a single file with CRDB versions (`crdb-versions.txt` can be refactored as a YAML file)
* verify the versions
* sort using calver
* define the latest version that can be used in some files (`manifest/operator.yaml`, etc)
* process templates (we can use go templates) and inject all needed values (list of supported crdb versions, latest crdb version)

This way we can replace sed with something that would make the build system more human and automation friendly :)

**Comment by meridional** [comment]
Seems like this was fixed.
