### ISSUE TITLE
Create GKE and Openshift test harness for running tests in GCP

### ISSUE THREAD

**Issue by udnay** [cockroachdb/cockroach-operator#551]
Currently all e2e tests are run as github actions and running against KinD. We need to run e2e tests on supported platforms currently GKE and Openshift at a minimum nightly.
At a minimum we should have a separate k8s cluster for both platforms. Maybe with a node autoscaler and using preemtible VMs. If easier we can use kubetest2 to spin up and teardown the clusters. For openshift it might be easier to just leave a cluster with minimal resources idling and just scale the nodepools up and down.

**Comment by udnay** [comment]
Thoughts @chrislovecnm and @keith-mcclellan

**Comment by chrislovecnm** [comment]
Closing as this is done
