### ISSUE TITLE
Multiple Version Checker Jobs Appear to Hang in Pending State

### ISSUE THREAD

**Issue by johnrk** [cockroachdb/cockroach-operator#566]
**Overview**
Using the latest Operator (1.7.11), I attempted to perform a minor version upgrade (21.1.1->21.1.2). After appearing to successfully performing the upgrade, there are three version checker jobs that appear to be hang in a pending state.

**Repro Steps:**
1. Apply CRD: `kubectl apply -f config/crd/bases/crdb.cockroachlabs.com_crdbclusters.yaml`
2. Apply Operator Manifest: `kubectl apply -f manifests/operator.yaml` 
3. Apply example.yaml with v21.1.1: `kubectl apply -f examples/example.yaml`
4. Apply example.yaml with v21.1.2: `kubectl apply -f examples/example.yaml`

**Expected Results:**
A rolling upgrade to v21.1.2 with the version checker jobs disappearing from the kubectl get pods status

**Actual Results:**
Three version checker jobs continue to appear in a "PENDING" State.
<img width="855" alt="Screen Shot 2021-06-09 at 11 09 47 AM" src="https://user-images.githubusercontent.com/1663752/121381362-a8e3e000-c913-11eb-93f1-0cc56f239ecd.png">

A few minutes later, now there are 6 version checker jobs in a PENDING state:
<img width="823" alt="Screen Shot 2021-06-09 at 11 14 49 AM" src="https://user-images.githubusercontent.com/1663752/121381788-0415d280-c914-11eb-8e2f-b4234704f1fb.png">

**Comment by alinadonisa** [comment]
@johnrk  do you have enough resources on the cluster to run  3 nodes of the crdb + version checker = 4?   Also please run:
```
 kubectl describe job  cochroachdb-vcheck-27054194
```

**Comment by chrislovecnm** [comment]
John what is the size of nodes you are running on k8s?

**Comment by johnrk** [comment]
@chrislovecnm , @alinadonisa ,

It appears to be a result of there being insufficient resources:

```
Johns-MBP:cockroach-operator johnkendall$ kubectl describe pod cockroachdb-vcheck-27055530-nbz9p
Name:           cockroachdb-vcheck-27055530-nbz9p
Namespace:      default
Priority:       0
Node:           <none>
Labels:         app.kubernetes.io/component=database
                app.kubernetes.io/instance=cockroachdb
                app.kubernetes.io/name=cockroachdb
                controller-uid=eb07c716-804d-4124-8c04-f47bb3d88370
                job-name=cockroachdb-vcheck-27055530
Annotations:    <none>
Status:         Pending
IP:             
IPs:            <none>
Controlled By:  Job/cockroachdb-vcheck-27055530
Containers:
  crdb:
    Image:      cockroachdb/cockroach:v21.1.2
    Port:       <none>
    Host Port:  <none>
    Command:
      /bin/bash
    Args:
      -c
      /cockroach/cockroach.sh version | grep 'Build Tag:'| awk '{print $3}'; sleep 150
    Limits:
      cpu:     2
      memory:  8Gi
    Requests:
      cpu:        2
      memory:     8Gi
    Environment:  <none>
    Mounts:       <none>
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:         <none>
QoS Class:       Guaranteed
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason            Age                From               Message
  ----     ------            ----               ----               -------
  Warning  FailedScheduling  73s (x2 over 73s)  default-scheduler  0/3 nodes are available: 3 Insufficient cpu, 3 Insufficient memory.

```

**Comment by alinadonisa** [comment]
@johnrk  yes... usually when you see pending states and after 2 minutes another job is created actually there are no resources to create the job. The operator retries and recreates a new version checker job after 2 minutes. The job it is not deleted because it is not successful and left to be deleted manually.

**Comment by udnay** [comment]
I think either we close this issue or potentially we drop the request sizes for the version checker, we shouldn't need 2vcpu and 8g to see what version we're running, right?

**Comment by chrislovecnm** [comment]
I opened https://github.com/cockroachdb/cockroach-operator/issues/570 to improve the user experience. @johnrk, can you confirm that increasing the GKE node size fixes this problem, please.

**Comment by chrislovecnm** [comment]
@davidwding can we close this?

**Comment by davidwding** [comment]
Yes.
