### ISSUE TITLE
[Docs] GA release will have PVC pruning turned off by default

### ISSUE THREAD

**Issue by udnay** [cockroachdb/cockroach-operator#598]
There is currently an issue where decommission can fail and cause a node not be fully decommissioned but has its replica removed. The volume claim of for that replica will be orphaned and so is eligible for being deleted. This can lead to a loss of data. For GA we have deleted the automatic pruning of PVCs and so a user must manually delete existing PVC in their cluster before scaling a cluster back up after a scale down event.

@taroface should we document the flag to enable the pruning behaviour?

**Comment by taroface** [comment]
@udnay What's the flag to enable PVC pruning, and how is it used?
