### ISSUE TITLE
Create API to allow users to configure log flag on CRBD startup

### ISSUE THREAD

**Issue by piyush-singh** [cockroachdb/cockroach-operator#623]
We have currently hard coded the logging configuration for each CRDB node in the K8s operator. We'd like to make this end user configurable via an  API that allows users to pass their own logging configurations to the operator. Because logging behavior changed in 21.1, we likely want to implement this for 21.1 and newer versions of CRDB to sidestep compatibility issues.

Some things to consider:
1. Although logging can be configured inline using a flag on the cockroach start command, there is also a yaml file based option. Log configs can be quite long and unwieldy to format as a single line, so it may be worth considering how to handle yaml file based configs.
2. Reloading new logging configs will require a node restart.
3. We'll need to consider how users can configure network based logging in addition to the existing disk and stderr based sinks

**Comment by chrislovecnm** [comment]
@piyush-singh status on this?
