### ISSUE TITLE
package.yaml is not being built properly

### ISSUE THREAD

**Issue by keith-mcclellan** [cockroachdb/cockroach-operator#633]
https://sdk.operatorframework.io/docs/olm-integration/generation/#upgrade-your-operator

Apparently we are supposed to be declaring upgrade paths in the package.yaml to allow the operator container to auto-upgrade.  We need to be doing this going forward from 2.0.0

**Comment by keith-mcclellan** [comment]
https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/how-to-update-operators.md

I was referred here for definitive guidance on how to set the CSV upgrade paths

**Comment by pseudomuto** [comment]
With the updated process this will be handled by the index image created by RH
