### ISSUE TITLE
Create a Cockroach Operator release process

### ISSUE THREAD

**Issue by chrislovecnm** [cockroachdb/cockroach-operator#64]
This project will need a release process.  We probably want a stable, beta, and dev versions.

- [x] documentation for the process, WIP
- [ ] container registry
- [X] [version naming](https://github.com/cockroachdb/cockroach-operator/pull/378)
- [X] manifest to deploy the operator
- [ ] manifest to deploy the API object crds
- [ ] cdb version support - what versions of cdb will be supported by which versions of the operator
- [x] [Release automation in TeamCity](https://github.com/cockroachdb/cockroach-operator/pull/352)

**Comment by JuanLeon1** [comment]
I think we need to break this down and assign people other than Dev Infra for some of the resulting pieces, as well as define the ones we can define a little better.

**Comment by jlinder** [comment]
Linking the [release process notes doc](https://docs.google.com/document/d/1rtDsXrXT8IyHVDJD1uNNofuaXZBYzPjy59F7t9FVUwY/edit#heading=h.ql40hnym3g6i) we created in November.

**Comment by rail** [comment]
@chrislovecnm Can you add comments to clarify what you meant by 
* container registry
* version naming
* cdb version support - what versions of cdb will be supported by which versions of the operator
Not sure if they should be a part of this issue.

**Comment by rail** [comment]
Listing the issues and PRs that we needed to resolve in order to resolve this issue:

* Move version to standalone file #378
* Update all ubi packages #429 
* Update bundle image attributes #426 
* Clean up bazel cache for release builds #423 
* Specify ":ubi_update" as a layer #418 
* Fix versionbump steps #414 
* Add release automation #352

**Comment by rail** [comment]
All done here IMO. Let's celebrate! 🍾
