### ISSUE TITLE
Acceptance testing platforms

### ISSUE THREAD

**Issue by chrislovecnm** [cockroachdb/cockroach-operator#65]
@johnrk what platforms does this operator needs to be tested against?  We are building this to support on-prem as well as cloud-deployed k8s.  What type of on-prem installations? I think this is a shortlist of testing that we can start with:

- Kind (baseline)
- GKE
- EKS
- kops on AWS
- Some bare metal / VMware / Openstack

**Comment by udnay** [comment]
Closing, we're testing on the GA targets for now
