### ISSUE TITLE
Examples/client-secure-operator.yaml breaks service on example.yaml

### ISSUE THREAD

**Issue by Hydrar** [cockroachdb/cockroach-operator#657]
Currently the stable documentation shows how to set up using example.yaml, and then access it with client-secure-operator.yaml.
The labels applied on client-secure-operator seems to be identical to what the operator creates for the cockroachdb-public service, so requests will occasionally end up loadbalanced onto the client pod, causing spurious "connection refused" errors that were very hard to debug.

I have not yet checked if this is fixed if you rename the instance in example to something else than cockroachdb, but is there a reason for the labels applied to the client at all?

**Comment by chrislovecnm** [comment]
@taroface can we update the documentation and remove the labels?

**Comment by chrislovecnm** [comment]
@Hydrar thanks for taking the time to file an issue!  We should not have the labels on that pod in the same manner, so we will update the documentation.
