### ISSUE TITLE
Pod security with manifest that is deployed

### ISSUE THREAD

**Issue by chrislovecnm** [cockroachdb/cockroach-operator#66]
I need to look at the Pod manifest that we are deploying with the operator.  I think it still has the auth token mounted.  I should also double-check the container security as well.  I might be wrong on the auth token, but we may need to remove it.

**Comment by chrislovecnm** [comment]
@chrisseto where is the Dockerfile for crdb?

**Comment by chrisseto** [comment]
Here is the [Dockerfile](https://github.com/cockroachdb/cockroach/blob/master/build/deploy/Dockerfile). 

The build process is handled outside of that specific dockerfile and the binary is just copied in.

It's [documented fairly well](https://github.com/cockroachdb/cockroach/tree/master/build) but I'm happy to track down answers for any questions you might have!
