### ISSUE TITLE
OpenShift Nightly test won't remove openshift-sa-bazel-test@ service account

### ISSUE THREAD

**Issue by rail** [cockroachdb/cockroach-operator#667]
After the nightlies are finished, the test leaves the `openshift-sa-bazel-test@cockroach-operator-nightlies.iam.gserviceaccount.com` service account in the system, what causes the next nightly to fail.

**Comment by chrislovecnm** [comment]
@rail is this fixed or do we need to implement this?

**Comment by rail** [comment]
I don't see the user anymore. Let's call it worksforme! Probably it's not an issue anymore after we started using a static account for the nightly tests.
