### ISSUE TITLE
Mark PersistentVolumeClaimSpec  and PersistentVolumeSource as optional

### ISSUE THREAD

**Issue by ryanzhang-oss** [cockroachdb/cockroach-operator#668]
https://github.com/cockroachdb/cockroach-operator/blob/993431bfde8f0593d69cede974a844c5b6ff979d/apis/v1alpha1/cluster_types.go#L237

These two fields are optional. Simple document fix.

https://github.com/cockroachdb/cockroach-operator/blob/993431bfde8f0593d69cede974a844c5b6ff979d/apis/v1alpha1/cluster_types.go#L92

DataStore should not have "omitempty" Json tag

**Comment by udnay** [comment]
Thanks for filing the issue, we'll take a look.

**Comment by udnay** [comment]
You're right we should remove the `omitempty` tag on `DataStore` I believe as we do not generate defaults.

I'm not sure I fully understand your other comment
> These two fields are optional. Simple document fix.

Which two fields do you mean `VolumClaim` and `HostPath` inside of the `Volume` struct?
