### ISSUE TITLE
SQL Client for testing and upgrades

### ISSUE THREAD

**Issue by chrislovecnm** [cockroachdb/cockroach-operator#73]
We need to implement a SQL client that is used for both e2e testing, and also the operator uses the same client to make the SQL command between major version upgrade.

**Comment by chrislovecnm** [comment]
We have a sql client that is used by 

https://github.com/cockroachdb/cockroach-operator/blob/14682f2f9140db8a8bc66538c68e993acf28cbd0/pkg/actor/upgrade.go#L96

We need to use it during testing

**Comment by chrislovecnm** [comment]
@vladdy you are checking the that the pods are alive after an upgrade and other e2e tests, but are you making SQL calls into them?

**Comment by vladdy** [comment]
I did not do that as I'm unaware of a query with a result that can guarantee that a pod or the entire cluster is healthy. I relayed on the assumption that the database will have improvements around health reporting if it is needed.

**Comment by chrislovecnm** [comment]
This is already implemented.  Closing
