### ISSUE TITLE
Implement code for major version upgrade

### ISSUE THREAD

**Issue by chrislovecnm** [cockroachdb/cockroach-operator#74]
The operator must

1. detect a major version upgrade
2. make a SQL call into the cluster
3. upgrade the container

Testing

We need to write e2e tests for this as well

**Comment by vladdy** [comment]
Maybe you have plans on different implementation, but the operator already does that already as well as e2e tests exists:

https://github.com/cockroachdb/cockroach-operator/blob/master/e2e/e2e_test.go#L165
https://github.com/cockroachdb/cockroach-operator/blob/master/e2e/e2e_test.go#L208

(although the names of the second step in the tests need to be fixed)

**Comment by chrislovecnm** [comment]
Does the operator make the sql call into the database? There is some field we need to set

**Comment by vladdy** [comment]
If you are talking about setting the `cluster.preserve_downgrade_option`, then it does:

https://github.com/cockroachdb/cockroach-operator/blob/master/pkg/actor/upgrade.go#L183

**Comment by chrislovecnm** [comment]
I'm seeing that you are doing it 😄

https://github.com/cockroachdb/cockroach-operator/blob/14682f2f9140db8a8bc66538c68e993acf28cbd0/pkg/actor/upgrade.go#L96

**Comment by johnrk** [comment]
This is a duplicate: https://github.com/cockroachdb/cockroach-operator/issues/30

**Comment by chrislovecnm** [comment]
I opened this for the implementation, but I will close this and comment on the other issue.

**Comment by chrislovecnm** [comment]
This is completed and behind a feature flag.  closing issue
