### ISSUE TITLE
Operator v21.1 pod crashing on startup on OpenShift

### ISSUE THREAD

**Issue by stevemul** [cockroachdb/cockroach-operator#779]
OpenShift cluster versions tried: 4.8, 4.6 
Cockroach Operator version from Operator Hub: 21.1

I'm having a problem when deploying the Operator into a new OpenShift cluster. I've tried on two different versions on different platforms and am seeing the same issue. The operator pod goes into a crash loop. The logs show the following errors (and more besides) each time:

`Failed to fetch webhook configuration","resource":"mutating-webhook-configuration","error":"mutatingwebhookconfigurations.admissionregistration.k8s.io
failed to setup TLS","error":"failed to patch the CABundle for the webhooks: failed to fetch mutating webhook configuration:`

I've put the full log example in this [gist](https://gist.githubusercontent.com/stevemul/6d7852b8e7f3918e224b00ede725a0cd/raw/79cd17cfc03472e802e22ba17e1bd54a24ce4dd2/cockroach%2520logs
) for now as I'm not sure how you'd prefer me to share the log details. 

Both these clusters are fresh deployments and several other operators deploy successfully so I've no reason to suspect the problem is the cluster configuration at this stage. I don't know of a way to specify a different Operator version so I haven't been able to tell if this is a new version issue or something else.

**Comment by pseudomuto** [comment]
> I'll test against a v4.8 cluster when I do, sorry to be a pain.

You're definitely not being a pain. We really appreciate you taking the time to raise this issue and test it out.

**Comment by pseudomuto** [comment]
@ethan-gallant thanks so much for providing these details. Just to make sure I'm following the same procedure as you are, can you show me how you're generating/pushing the index and bundle images. I just want to me sure I'm using the same procedure so I can repro
