### ISSUE TITLE
PodDisruptionBudget

### ISSUE THREAD

**Issue by chrislovecnm** [cockroachdb/cockroach-operator#79]
Add API values to control PDB, and implement PDB.

```
maxUnavailable: 1
```

Probably need to default to a value that will keep quorum.

**Comment by chrislovecnm** [comment]
@johnrk requirements questions.  We do not allow the user to set `minAvailable`, in the helm chart, instead of `maxUnavailable` in the PDB.  I have implemented the capability for a user to set both.  Thoughts?

If the size of the database is just a single pod we do not create the PDB. 

Open question.  Do we allow the user to not have a PDB at all?  It is a valid use case, but I would not recommend the edge case, but you never know with users :)

**Comment by chrisseto** [comment]
> If the size of the database is just a single pod we do not create the PDB.

We should probably note somewhere that single node clusters are not suitable for production use?

> Do we allow the user to not have a PDB at all? It is a valid use case,

What cases do you have in mind besides a single node cluster?

**Comment by chrislovecnm** [comment]
@chrisseto 

> What cases do you have in mind besides a single node cluster?

Some users do not like PDBs, it is personal preference tbh.

**Comment by chrislovecnm** [comment]
> We should probably note somewhere that single node clusters are not suitable for production use?

Is this not documented in the DB docs?

**Comment by vladdy** [comment]
so if some users do not like it, why do we need to support it? There is nothing what prevents the user from creating a CR with the budget they need along with cockroachdb cluster. 

The only pro of supporting PDBs in the operator I see is it allows to remove the logic of ensuring that the db cluster has enough of healthy nodes out of the operator. However, it is unclear how this is going to play with auto-scaling. Hopefully, these things won't intersect =).

**Comment by chrislovecnm** [comment]
@johnrk we want the parity with the helm chart for PDBs?  I am adding a feature and will have parity as well.  Do we want to allow the user to disable the PDB?

**Comment by chrislovecnm** [comment]
@johnrk the initial code is in, but I have testing that I am planning.

**Comment by chrislovecnm** [comment]
Closing this, as we have other issues open for testing

**Comment by johnrk** [comment]
@chrislovecnm , I'm just now catching up with this issue. Let's go for parity with the Helm Chart. What initial code is in? What did we land on here?

**Comment by keith-mcclellan** [comment]
@chrislovecnm what's the status on this? we should be defaulting this to be the number of cockroachdb nodes -1 by default since the default RF = 3

**Comment by chrislovecnm** [comment]
Fixed
