### ISSUE TITLE
Specifying VolumeMode other than Filesystem causes infinite reconciliation

### ISSUE THREAD

**Issue by ethan-gallant** [cockroachdb/cockroach-operator#790]
To reproduce:

- Install Operator as normal
- Edit example.yaml and remove the `volumeMode: Filesystem` field
- Get smacked with 100 logs per second and an angry operator

Effect: 
- Operator fails to reconcile the cluster or update any resources
- Operator continuously updates the CRDBCluster, re-annotating it with the previous version causing the version to rapidly. (~50 reconsiles per second)
- The pods in the cluster remain in a non-ready state.

Logs:
(one entry for the operator and one for a DB pod)
https://gist.github.com/ethan-gallant/a3cafad99250bcd8214e8b9cbf58e03f

**Comment by meridional** [comment]
This is partially addressed in #851, where we reject new clusters without the correct `volumeMode` setting.
