### ISSUE TITLE
Documentation Improvements

### ISSUE THREAD

**Issue by chrislovecnm** [cockroachdb/cockroach-operator#80]
There is a lot of documentation that needs to be improved.  I'm opening this issue to track the improvements.

- [ ] README.md - needs to be turned into a user guide. It is now more a developer guide.
- [ ] Developer.md - needs to be improved to talk about testing and code layout.
- [ ] Code Comments - improvement is required.
- [ ] Release process - needs to be documented

**Comment by chrislovecnm** [comment]
@vladdy @johnrk @chrisseto what other improvements are required?

**Comment by vladdy** [comment]
I would say that the user guide should be a part of the main website along with other k8s related docs, but it is up to @johnrk to decide.

**Comment by johnrk** [comment]
Yes, for the MVP, the priority is having a README that's detailed enough to get a new user running. Based on my conversation with Ryan, the user guide/public documentation will be started in Q3.

I'll break these items out into separate issues.
