### ISSUE TITLE
GCP API Enable Instructions

### ISSUE THREAD

**Issue by johnrk** [cockroachdb/cockroach-operator#84]
For running on a GCP Account, we need to update the README to inform users to enable GCP API. 

**cloudresourcemanager.googleapis.com**

**Comment by chrislovecnm** [comment]
@taroface we have multiple APIs that have to be enabled to run the demo.  Is this something that you can document?

**Comment by taroface** [comment]
@chrislovecnm I can add it to my backlog if this is something we need for the CRDB docs and/or README. However, I would need to prioritize it against a higher-priority project that just started and will take up most of my time for at least the next several weeks.

**Comment by keith-mcclellan** [comment]
@johnrk is this necessary for the next release? If not I'd like to move to backlog

**Comment by johnrk** [comment]
Since we're focused on OpenShift, no I don't think so. @chrislovecnm , thoughts?

**Comment by udnay** [comment]
@taroface can we close this? The tutorials seem to cover having k8s up and running
