### ISSUE TITLE
operator is using an old UBI image

### ISSUE THREAD

**Issue by dbist** [cockroachdb/cockroach-operator#860]
using the following bash function

```bash
function ubi-version() {
    docker pull cockroachdb/cockroach-operator:${1}
    local tag=$(docker inspect cockroachdb/cockroach-operator:${1} | grep '"url"' | sort | uniq | awk -F '/' '{print $9}' | sed -e 's/".*$//')
    echo
    echo "docker pull registry.access.redhat.com/ubi8/ubi-minimal:${tag}"
    echo "https://catalog.redhat.com/software/containers/ubi8/ubi-minimal/5c359a62bed8bd75a2c3fba8?tag=${tag}"
}


ubi-version v2.5.0
v2.5.0: Pulling from cockroachdb/cockroach-operator
131f1a26eef0: Pull complete 
16b78ed2e822: Pull complete 
2d3ef9c85968: Pull complete 
4653f0476614: Pull complete 
d55f0a4a0ca7: Pull complete 
1bdd61071f60: Pull complete 
Digest: sha256:075580add4d698230546d0db2a09c1cf8773d45f8f1f664a51cae7ea685670ef
Status: Downloaded newer image for cockroachdb/cockroach-operator:v2.5.0
docker.io/cockroachdb/cockroach-operator:v2.5.0

docker pull registry.access.redhat.com/ubi8/ubi-minimal:8.5-218
https://catalog.redhat.com/software/containers/ubi8/ubi-minimal/5c359a62bed8bd75a2c3fba8?tag=8.5-218
```

it shows that operator is using a 2 months old version of UBI base image. This image is old and RHEL advises to upgrade to the latest available as of today, March 3rd, 2022.
![image](https://user-images.githubusercontent.com/461296/156624625-5c94ae7e-71d4-4d85-8d43-dbf6e387d30a.png)

**Comment by pseudomuto** [comment]
Hey @dbist, thanks for letting us know. This corresponds with the timing for our last release (~2m ago). We'll be publishing a new release this week, which should take care of updating the UBI image. I'll add a note here once it's released.

**Comment by pseudomuto** [comment]
I'm in the process of cutting a new release right now, but the docker image is up. If you run your script above with `v2.5.1` you'll see the base image has been updated to the latest version of the UBI base image (`8.5-230.1645809059`).
