### ISSUE TITLE
`--join` in `additionalArgs` is applied below initial `--join` causing cluster to form early

### ISSUE THREAD

**Issue by ADustyOldMuffin** [cockroachdb/cockroach-operator#887]
Hello!

## Problem
We are trying to use the Operator to get nodes to join to an existing cluster which I know isn't officially supported currently. We've have issues doing this since when you put `--join` after the `--join` created by the operator the crdb nodes will join to the nodes made by the operator and create a happy cluster outside of the existing one.

### Proposed Solution

To add some validation that if additional args have `--join` in them then we shouldn't generate a new `--join` argument. This would allow a solution without any CRD changes.

### Other Solutions

You could add a field specifically for this in the CRD called `existingNodes` that accepts an array of nodes, and instead put these in front of the other nodes in the created `--join`. This would allow us to keep the other statefulset nodes as well.

**Comment by chrisseto** [comment]
Close as https://github.com/cockroachdb/cockroach-operator/pull/886 has been merged. Please re-open if we need to revisit this issue.
