### ISSUE TITLE
Operator isn't listening for changes in the dataStore custom resource (e.g.  storage: 50Gi->60Gi)

### ISSUE THREAD

**Issue by johnrk** [cockroachdb/cockroach-operator#91]
After successfully creating a 3 node cluster with **config/examples/3-nodes-secure-kube-cert.yaml** , I changed modified the Storage field under dataStore from 60Gi to 50Gi. I expected the persistent volumes and persistent volume claims to change to my desired state, but they didn't.

Screenshots:
<img width="432" alt="Screen Shot 2020-07-17 at 1 25 15 PM" src="https://user-images.githubusercontent.com/1663752/87814338-8e9fa000-c831-11ea-9f74-46caea97eaef.png">
<img width="1257" alt="Screen Shot 2020-07-17 at 1 25 38 PM" src="https://user-images.githubusercontent.com/1663752/87814335-8ba4af80-c831-11ea-8e02-150be8f0dafa.png">

**Comment by chrislovecnm** [comment]
Need to research this, but this may not be feasible on all platforms. This is not a big but a feature that is not implemented

**Comment by chrislovecnm** [comment]
Does the helm chart support this?

**Comment by chrislovecnm** [comment]
This is not supported under all use cases. A list of supported platforms:

> AWS-EBS, GCE-PD, Azure Disk, Azure File, Glusterfs, Cinder, Portworx, and Ceph RBD

Not certain this list is the full list, but we need to mention this.

We also need to determine how this impact database performance?

**Comment by chrisseto** [comment]
@johnrk increasing disk sizes should be supported but decreasing them isn't something the operator (Or kubernetes for that matter) can do.

**Comment by johnrk** [comment]
@chrislovecnm , can you clarify the steps a user is supposed to take to increase disk size?

Right now, it's successfully installing a CRDB cluster with the correct disk size. But it still doesn't appear to change when I do kubectl edit Crdbcluster <cluster name> or editing the yaml file.

In addition, I'm trying to delete the pv,pvc --all when the pods are still running, but it appears to hang.

**Comment by chrislovecnm** [comment]
@johnrk I have not tested it TBH.  All you theoretically should have to do is edit the CRD.

**Comment by chrisseto** [comment]
The operator may have to restart all the CRDB pods? Once a PVC is resized, the actual FS won't be resized until the pod it's attached to is restarted/recreated.

**Comment by chrislovecnm** [comment]
cc @alinadonisa

**Comment by johnrk** [comment]
@taroface , this issue is still open.
