### ISSUE TITLE
Push arm64 images to Docker Hub

### ISSUE THREAD

**Issue by markus-k** [cockroachdb/cockroach-operator#979]
With arm64-servers becoming more common, it'd be nice to be able run the cockroach-operator in arm64 kubernetes-clusters.

Currently, images pushed to Docker Hub are [only available for amd64](https://hub.docker.com/r/cockroachdb/cockroach-operator/tags). The `cockroachdb/cockroach` image is already available for arm64.

`cockroachdb/cockroach-operator` should also be pushed for arm64.

**Comment by DWSR** [comment]
Dupe of #942

**Comment by markus-k** [comment]
Whoops I somehow missed that, good job GitHub search :)
