### ISSUE TITLE
[bug] Can not upgrade to 23.1.1 due to vcheck job OOM 

### ISSUE THREAD

**Issue by kangzhang** [cockroachdb/cockroach-operator#983]
We run a cockroach cluster (22.2.2) using this operator and things have been great. We recent tried to upgrade to 23.1.1 but the operator kept failing on version checks and we could not upgrade. 

After taking a closer look - it seems that the [resource constraint here](https://github.com/cockroachdb/cockroach-operator/commit/04c59a316dbe5abb395038c34c31ad8fe9985346) is too low for latest cockroach binary. It consistently fails on our cluster and never pass for 23.1.1 images. 

Wonder if you could help to bump the limit and release a new version of operator that comes with higher limits. 

Thank you!

**Comment by lingdie** [comment]
I've encountered the same issue. Modifying using the cockroachDBVersion flag indeed allows skipping the vcheck job. However, I noticed that the commands executed by the vcheck job are quite simple. Why would the job get OOM killed?
