### ISSUE TITLE
Operator image v2.11.0 not found

### ISSUE THREAD

**Issue by WoodyWoodsta** [cockroachdb/cockroach-operator#995]
The changelog and tags suggest that operator v2.11.0 is ready to be used. However, when attempting to upgrade, it became apparent that `cockroachdb/cockroach-operator:v2.11.0` does not exist on Docker Hub.

When should we expect this to be available?

**Comment by WoodyWoodsta** [comment]
@prafull01 Is there something we can do to help here?

**Comment by prafull01** [comment]
It is available now.
